package whatisnewin.java.lang.module;

import java.lang.module.ResolvedModule;
import java.lang.module.Configuration;
import java.lang.module.ModuleReference;
import java.util.Set;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link ResolvedModule}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link ResolvedModule} is a completely new class.
 * @since 9
 * @see ResolvedModule
 */
public final class WhatIsNewInResolvedModule
{
  /**
   * Example call to new method {@link ResolvedModule#configuration()}.
   * @since 9
   * @see ResolvedModule#configuration()
   */
  public Configuration configuration()
  {
    ResolvedModule testee = $$$();

    Configuration result = testee.configuration();
    return result;
  }

  /**
   * Example call to new method {@link ResolvedModule#reference()}.
   * @since 9
   * @see ResolvedModule#reference()
   */
  public ModuleReference reference()
  {
    ResolvedModule testee = $$$();

    ModuleReference result = testee.reference();
    return result;
  }

  /**
   * Example call to new method {@link ResolvedModule#name()}.
   * @since 9
   * @see ResolvedModule#name()
   */
  public String name()
  {
    ResolvedModule testee = $$$();

    String result = testee.name();
    return result;
  }

  /**
   * Example call to new method {@link ResolvedModule#reads()}.
   * @since 9
   * @see ResolvedModule#reads()
   */
  public Set<ResolvedModule> reads()
  {
    ResolvedModule testee = $$$();

    Set<ResolvedModule> result = testee.reads();
    return result;
  }

  private ResolvedModule $$$()
  {
    return null;
  }
}
