package whatisnewin.java.lang.module;

import java.lang.module.FindException;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link FindException}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link FindException} is a completely new class.
 * @since 9
 * @see FindException
 */
public final class WhatIsNewInFindException
{
  /**
   * Example call to new constructor {@link FindException#FindException()}.
   * @since 9
   * @see FindException#FindException()
   */
  public WhatIsNewInFindException()
  {
    FindException testee = new FindException();
  }

  /**
   * Example call to new constructor {@link FindException#FindException(String)}.
   * @since 9
   * @see FindException#FindException(String)
   */
  public WhatIsNewInFindException(String msg)
  {
    FindException testee = new FindException(msg);
  }

  /**
   * Example call to new constructor {@link FindException#FindException(Throwable)}.
   * @since 9
   * @see FindException#FindException(Throwable)
   */
  public WhatIsNewInFindException(Throwable cause)
  {
    FindException testee = new FindException(cause);
  }

  /**
   * Example call to new constructor {@link FindException#FindException(String, Throwable)}.
   * @since 9
   * @see FindException#FindException(String, Throwable)
   */
  public WhatIsNewInFindException(String msg, Throwable cause)
  {
    FindException testee = new FindException(msg, cause);
  }

}
