package whatisnewin.java.lang.module;

import java.lang.module.ModuleDescriptor.Version;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link Version}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link Version} is a completely new class.
 * @since 9
 * @see Version
 */
public final class WhatIsNewInModuleDescriptor$Version
{
  /**
   * Example call to new method {@link Version#parse(String)}.
   * @since 9
   * @see Version#parse(String)
   */
  public static Version parse(String v)
  {
    Version result = Version.parse(v);
    return result;
  }

  /**
   * Example call to new method {@link Version#compareTo(Version)}.
   * @since 9
   * @see Version#compareTo(Version)
   */
  public int compareTo(Version that)
  {
    Version testee = $$$();

    int result = testee.compareTo(that);
    return result;
  }

  private Version $$$()
  {
    return null;
  }
}
