package whatisnewin.javax.lang.model.util;

import javax.lang.model.util.SimpleAnnotationValueVisitor9;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link SimpleAnnotationValueVisitor9}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link SimpleAnnotationValueVisitor9} is a completely new class.
 * @since 9
 * @see SimpleAnnotationValueVisitor9
 */
public final class WhatIsNewInSimpleAnnotationValueVisitor9<R, P>
{
}
