package whatisnewin.javax.lang.model.util;

import javax.lang.model.util.AbstractTypeVisitor9;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link AbstractTypeVisitor9}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link AbstractTypeVisitor9} is a completely new class
 * @since 9
 * @see AbstractTypeVisitor9
 */
public final class WhatIsNewInAbstractTypeVisitor9<R, P>
{
}
