package whatisnewin.javax.lang.model.util;

import javax.lang.model.util.ElementKindVisitor9;
import javax.lang.model.element.ModuleElement;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link ElementKindVisitor9}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link ElementKindVisitor9} is a completely new class
 * @since 9
 * @see ElementKindVisitor9
 */
public final class WhatIsNewInElementKindVisitor9<R, P>
{
  /**
   * Example call to new method {@link ElementKindVisitor9#visitModule}
   * @since 9
   * @see ElementKindVisitor9#visitModule
   */
  public R visitModule(ModuleElement e, P p)
  {
    ElementKindVisitor9<R, P> testee = $$$();

    R result = testee.visitModule(e, p);
    return result;
  }

  private ElementKindVisitor9 $$$()
  {
    return null;
  }
}
