package whatisnewin.javax.lang.model.util;

import javax.lang.model.util.AbstractAnnotationValueVisitor9;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link AbstractAnnotationValueVisitor9}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link AbstractAnnotationValueVisitor9} is a completely new class.
 * @since 9
 * @see AbstractAnnotationValueVisitor9
 */
public final class WhatIsNewInAbstractAnnotationValueVisitor9<R, P>
{
}
