package whatisnewin.java.security.cert;

import java.security.cert.URICertStoreParameters;
import java.net.URI;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link URICertStoreParameters}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link URICertStoreParameters} is a completely new class.
 * @since 9
 * @see URICertStoreParameters
 */
public final class WhatIsNewInURICertStoreParameters
{
  /**
   * Example call to new constructor {@link URICertStoreParameters#URICertStoreParameters(URI)}.
   * @since 9
   * @see URICertStoreParameters#URICertStoreParameters(URI)
   */
  public WhatIsNewInURICertStoreParameters(URI uri)
  {
    URICertStoreParameters testee = new URICertStoreParameters(uri);
  }

  /**
   * Example call to new method {@link URICertStoreParameters#getURI()}.
   * @since 9
   * @see URICertStoreParameters#getURI()
   */
  public URI getURI()
  {
    URICertStoreParameters testee = $$$();

    URI result = testee.getURI();
    return result;
  }

  private URICertStoreParameters $$$()
  {
    return null;
  }
}
