package whatisnewin.javax.xml.catalog;

import javax.xml.catalog.CatalogException;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link CatalogException}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link CatalogException} is a completely new class.
 * @since 9
 * @see CatalogException
 */
public final class WhatIsNewInCatalogException
{
  /**
   * Example call to new constructor {@link CatalogException#CatalogException(String)}.
   * @since 9
   * @see CatalogException#CatalogException(String)
   */
  public WhatIsNewInCatalogException(String message)
  {
    CatalogException testee = new CatalogException(message);
  }

  /**
   * Example call to new constructor {@link CatalogException#CatalogException(String, Throwable)}.
   * @since 9
   * @see CatalogException#CatalogException(String, Throwable)
   */
  public WhatIsNewInCatalogException(String message, Throwable cause)
  {
    CatalogException testee = new CatalogException(message, cause);
  }

}
