package whatisnewin.java.awt.image;

import java.awt.image.BaseMultiResolutionImage;
import java.awt.Image;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link BaseMultiResolutionImage}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link BaseMultiResolutionImage} is a completely new class.
 * @since 9
 * @see BaseMultiResolutionImage
 */
public final class WhatIsNewInBaseMultiResolutionImage
{
  /**
   * Example call to new constructor {@link BaseMultiResolutionImage#BaseMultiResolutionImage(Image...)}.
   * @since 9
   * @see BaseMultiResolutionImage#BaseMultiResolutionImage(Image...)
   */
  public WhatIsNewInBaseMultiResolutionImage(Image... resolutionVariants)
  {
    BaseMultiResolutionImage testee = new BaseMultiResolutionImage(resolutionVariants);
  }

  /**
   * Example call to new constructor {@link BaseMultiResolutionImage#BaseMultiResolutionImage(int, Image...)}.
   * @since 9
   * @see BaseMultiResolutionImage#BaseMultiResolutionImage(int, Image...)
   */
  public WhatIsNewInBaseMultiResolutionImage(int baseImageIndex, Image... resolutionVariants)
  {
    BaseMultiResolutionImage testee = new BaseMultiResolutionImage(baseImageIndex, resolutionVariants);
  }

}
