package whatisnewin.java.awt.image;

import java.awt.image.AbstractMultiResolutionImage;
import java.awt.image.ImageObserver;
import java.awt.image.ImageProducer;
import java.awt.Graphics;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link AbstractMultiResolutionImage}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link AbstractMultiResolutionImage} is a completely new class.
 * @since 9
 * @see AbstractMultiResolutionImage
 */
public final class WhatIsNewInAbstractMultiResolutionImage
{
  /**
   * Example call to new method {@link AbstractMultiResolutionImage#getWidth(ImageObserver)}.
   * @since 9
   * @see AbstractMultiResolutionImage#getWidth(ImageObserver)
   */
  public int getWidth(ImageObserver observer)
  {
    AbstractMultiResolutionImage testee = $$$();

    int result = testee.getWidth(observer);
    return result;
  }

  /**
   * Example call to new method {@link AbstractMultiResolutionImage#getHeight(ImageObserver)}.
   * @since 9
   * @see AbstractMultiResolutionImage#getHeight(ImageObserver)
   */
  public int getHeight(ImageObserver observer)
  {
    AbstractMultiResolutionImage testee = $$$();

    int result = testee.getHeight(observer);
    return result;
  }

  /**
   * Example call to new method {@link AbstractMultiResolutionImage#getSource()}.
   * @since 9
   * @see AbstractMultiResolutionImage#getSource()
   */
  public ImageProducer getSource()
  {
    AbstractMultiResolutionImage testee = $$$();

    ImageProducer result = testee.getSource();
    return result;
  }

  /**
   * Example call to new method {@link AbstractMultiResolutionImage#getGraphics()}.
   * @since 9
   * @see AbstractMultiResolutionImage#getGraphics()
   */
  public Graphics getGraphics()
  {
    AbstractMultiResolutionImage testee = $$$();

    Graphics result = testee.getGraphics();
    return result;
  }

  /**
   * Example call to new method {@link AbstractMultiResolutionImage#getProperty(String, ImageObserver)}.
   * @since 9
   * @see AbstractMultiResolutionImage#getProperty(String, ImageObserver)
   */
  public Object getProperty(String name, ImageObserver observer)
  {
    AbstractMultiResolutionImage testee = $$$();

    Object result = testee.getProperty(name, observer);
    return result;
  }

  private AbstractMultiResolutionImage $$$()
  {
    return null;
  }
}
