package whatisnewin.javax.swing;

import javax.swing.SwingContainer;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link SwingContainer}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link SwingContainer} is a completely new class.
 * @since 9
 * @see SwingContainer
 */
public final class WhatIsNewInSwingContainer
{
  /**
   * Example call to new method {@link SwingContainer#value()}.
   * @since 9
   * @see SwingContainer#value()
   */
  public boolean value()
  {
    SwingContainer testee = $$$();

    boolean result = testee.value();
    return result;
  }

  /**
   * Example call to new method {@link SwingContainer#delegate()}.
   * @since 9
   * @see SwingContainer#delegate()
   */
  public String delegate()
  {
    SwingContainer testee = $$$();

    String result = testee.delegate();
    return result;
  }

  private SwingContainer $$$()
  {
    return null;
  }
}
