package whatisnewin.javax.swing;

import javax.swing.ButtonModel;
import javax.swing.ButtonGroup;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link ButtonModel}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link ButtonModel} is an old class but has new fields, constructors or methods
 * @since 1.2
 * @see ButtonModel
 */
public final class WhatIsNewInButtonModel
{
  /**
   * Example call to new method {@link ButtonModel#getGroup}
   * @since 10
   * @see ButtonModel#getGroup
   */
  public ButtonGroup getGroup()
  {
    ButtonModel testee = $$$();

    ButtonGroup result = testee.getGroup();
    return result;
  }

  private ButtonModel $$$()
  {
    return null;
  }
}
