package whatisnewin.jdk.nashorn.api.tree;

import jdk.nashorn.api.tree.BinaryTree;
import jdk.nashorn.api.tree.ExpressionTree;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link BinaryTree}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link BinaryTree} is a completely new class.
 * @since 9
 * @see BinaryTree
 */
public final class WhatIsNewInBinaryTree
{
  /**
   * Example call to new method {@link BinaryTree#getLeftOperand()}.
   * @since 9
   * @see BinaryTree#getLeftOperand()
   */
  public ExpressionTree getLeftOperand()
  {
    BinaryTree testee = $$$();

    ExpressionTree result = testee.getLeftOperand();
    return result;
  }

  /**
   * Example call to new method {@link BinaryTree#getRightOperand()}.
   * @since 9
   * @see BinaryTree#getRightOperand()
   */
  public ExpressionTree getRightOperand()
  {
    BinaryTree testee = $$$();

    ExpressionTree result = testee.getRightOperand();
    return result;
  }

  private BinaryTree $$$()
  {
    return null;
  }
}
