package whatisnewin.jdk.nashorn.api.tree;

import jdk.nashorn.api.tree.TryTree;
import jdk.nashorn.api.tree.BlockTree;
import java.util.List;
import jdk.nashorn.api.tree.CatchTree;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link TryTree}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link TryTree} is a completely new class.
 * @since 9
 * @see TryTree
 */
public final class WhatIsNewInTryTree
{
  /**
   * Example call to new method {@link TryTree#getBlock()}.
   * @since 9
   * @see TryTree#getBlock()
   */
  public BlockTree getBlock()
  {
    TryTree testee = $$$();

    BlockTree result = testee.getBlock();
    return result;
  }

  /**
   * Example call to new method {@link TryTree#getCatches()}.
   * @since 9
   * @see TryTree#getCatches()
   */
  public List<? extends CatchTree> getCatches()
  {
    TryTree testee = $$$();

    List<? extends CatchTree> result = testee.getCatches();
    return result;
  }

  /**
   * Example call to new method {@link TryTree#getFinallyBlock()}.
   * @since 9
   * @see TryTree#getFinallyBlock()
   */
  public BlockTree getFinallyBlock()
  {
    TryTree testee = $$$();

    BlockTree result = testee.getFinallyBlock();
    return result;
  }

  private TryTree $$$()
  {
    return null;
  }
}
