package whatisnewin.jdk.nashorn.api.tree;

import jdk.nashorn.api.tree.ClassDeclarationTree;
import jdk.nashorn.api.tree.IdentifierTree;
import java.util.List;
import jdk.nashorn.api.tree.PropertyTree;
import jdk.nashorn.api.tree.ExpressionTree;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link ClassDeclarationTree}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link ClassDeclarationTree} is a completely new class.
 * @since 9
 * @see ClassDeclarationTree
 */
public final class WhatIsNewInClassDeclarationTree
{
  /**
   * Example call to new method {@link ClassDeclarationTree#getName()}.
   * @since 9
   * @see ClassDeclarationTree#getName()
   */
  public IdentifierTree getName()
  {
    ClassDeclarationTree testee = $$$();

    IdentifierTree result = testee.getName();
    return result;
  }

  /**
   * Example call to new method {@link ClassDeclarationTree#getClassElements()}.
   * @since 9
   * @see ClassDeclarationTree#getClassElements()
   */
  public List<? extends PropertyTree> getClassElements()
  {
    ClassDeclarationTree testee = $$$();

    List<? extends PropertyTree> result = testee.getClassElements();
    return result;
  }

  /**
   * Example call to new method {@link ClassDeclarationTree#getClassHeritage()}.
   * @since 9
   * @see ClassDeclarationTree#getClassHeritage()
   */
  public ExpressionTree getClassHeritage()
  {
    ClassDeclarationTree testee = $$$();

    ExpressionTree result = testee.getClassHeritage();
    return result;
  }

  /**
   * Example call to new method {@link ClassDeclarationTree#getConstructor()}.
   * @since 9
   * @see ClassDeclarationTree#getConstructor()
   */
  public PropertyTree getConstructor()
  {
    ClassDeclarationTree testee = $$$();

    PropertyTree result = testee.getConstructor();
    return result;
  }

  private ClassDeclarationTree $$$()
  {
    return null;
  }
}
