package whatisnewin.jdk.nashorn.api.tree;

import jdk.nashorn.api.tree.ForLoopTree;
import jdk.nashorn.api.tree.ExpressionTree;
import jdk.nashorn.api.tree.StatementTree;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link ForLoopTree}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link ForLoopTree} is a completely new class.
 * @since 9
 * @see ForLoopTree
 */
public final class WhatIsNewInForLoopTree
{
  /**
   * Example call to new method {@link ForLoopTree#getCondition()}.
   * @since 9
   * @see ForLoopTree#getCondition()
   */
  public ExpressionTree getCondition()
  {
    ForLoopTree testee = $$$();

    ExpressionTree result = testee.getCondition();
    return result;
  }

  /**
   * Example call to new method {@link ForLoopTree#getUpdate()}.
   * @since 9
   * @see ForLoopTree#getUpdate()
   */
  public ExpressionTree getUpdate()
  {
    ForLoopTree testee = $$$();

    ExpressionTree result = testee.getUpdate();
    return result;
  }

  /**
   * Example call to new method {@link ForLoopTree#getInitializer()}.
   * @since 9
   * @see ForLoopTree#getInitializer()
   */
  public ExpressionTree getInitializer()
  {
    ForLoopTree testee = $$$();

    ExpressionTree result = testee.getInitializer();
    return result;
  }

  /**
   * Example call to new method {@link ForLoopTree#getStatement()}.
   * @since 9
   * @see ForLoopTree#getStatement()
   */
  public StatementTree getStatement()
  {
    ForLoopTree testee = $$$();

    StatementTree result = testee.getStatement();
    return result;
  }

  private ForLoopTree $$$()
  {
    return null;
  }
}
