package whatisnewin.jdk.nashorn.api.tree;

import jdk.nashorn.api.tree.ArrayAccessTree;
import jdk.nashorn.api.tree.ExpressionTree;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link ArrayAccessTree}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link ArrayAccessTree} is a completely new class.
 * @since 9
 * @see ArrayAccessTree
 */
public final class WhatIsNewInArrayAccessTree
{
  /**
   * Example call to new method {@link ArrayAccessTree#getIndex()}.
   * @since 9
   * @see ArrayAccessTree#getIndex()
   */
  public ExpressionTree getIndex()
  {
    ArrayAccessTree testee = $$$();

    ExpressionTree result = testee.getIndex();
    return result;
  }

  /**
   * Example call to new method {@link ArrayAccessTree#getExpression()}.
   * @since 9
   * @see ArrayAccessTree#getExpression()
   */
  public ExpressionTree getExpression()
  {
    ArrayAccessTree testee = $$$();

    ExpressionTree result = testee.getExpression();
    return result;
  }

  private ArrayAccessTree $$$()
  {
    return null;
  }
}
