package whatisnewin.jdk.nashorn.api.tree;

import jdk.nashorn.api.tree.UnaryTree;
import jdk.nashorn.api.tree.ExpressionTree;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link UnaryTree}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link UnaryTree} is a completely new class
 * @since 9
 * @see UnaryTree
 */
public final class WhatIsNewInUnaryTree
{
  /**
   * Example call to new method {@link UnaryTree#getExpression}
   * @since 9
   * @see UnaryTree#getExpression
   */
  public ExpressionTree getExpression()
  {
    UnaryTree testee = $$$();

    ExpressionTree result = testee.getExpression();
    return result;
  }

  private UnaryTree $$$()
  {
    return null;
  }
}
