package whatisnewin.jdk.nashorn.api.tree;

import jdk.nashorn.api.tree.BreakTree;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link BreakTree}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link BreakTree} is a completely new class.
 * @since 9
 * @see BreakTree
 */
public final class WhatIsNewInBreakTree
{
  /**
   * Example call to new method {@link BreakTree#getLabel()}.
   * @since 9
   * @see BreakTree#getLabel()
   */
  public String getLabel()
  {
    BreakTree testee = $$$();

    String result = testee.getLabel();
    return result;
  }

  private BreakTree $$$()
  {
    return null;
  }
}
