package whatisnewin.jdk.nashorn.api.tree;

import jdk.nashorn.api.tree.TemplateLiteralTree;
import java.util.List;
import jdk.nashorn.api.tree.ExpressionTree;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link TemplateLiteralTree}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link TemplateLiteralTree} is a completely new class.
 * @since 9
 * @see TemplateLiteralTree
 */
public final class WhatIsNewInTemplateLiteralTree
{
  /**
   * Example call to new method {@link TemplateLiteralTree#getExpressions()}.
   * @since 9
   * @see TemplateLiteralTree#getExpressions()
   */
  public List<? extends ExpressionTree> getExpressions()
  {
    TemplateLiteralTree testee = $$$();

    List<? extends ExpressionTree> result = testee.getExpressions();
    return result;
  }

  private TemplateLiteralTree $$$()
  {
    return null;
  }
}
