package whatisnewin.jdk.nashorn.api.tree;

import jdk.nashorn.api.tree.ForOfLoopTree;
import jdk.nashorn.api.tree.ExpressionTree;
import jdk.nashorn.api.tree.StatementTree;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link ForOfLoopTree}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link ForOfLoopTree} is a completely new class.
 * @since 9
 * @see ForOfLoopTree
 */
public final class WhatIsNewInForOfLoopTree
{
  /**
   * Example call to new method {@link ForOfLoopTree#getVariable()}.
   * @since 9
   * @see ForOfLoopTree#getVariable()
   */
  public ExpressionTree getVariable()
  {
    ForOfLoopTree testee = $$$();

    ExpressionTree result = testee.getVariable();
    return result;
  }

  /**
   * Example call to new method {@link ForOfLoopTree#getExpression()}.
   * @since 9
   * @see ForOfLoopTree#getExpression()
   */
  public ExpressionTree getExpression()
  {
    ForOfLoopTree testee = $$$();

    ExpressionTree result = testee.getExpression();
    return result;
  }

  /**
   * Example call to new method {@link ForOfLoopTree#getStatement()}.
   * @since 9
   * @see ForOfLoopTree#getStatement()
   */
  public StatementTree getStatement()
  {
    ForOfLoopTree testee = $$$();

    StatementTree result = testee.getStatement();
    return result;
  }

  private ForOfLoopTree $$$()
  {
    return null;
  }
}
