package whatisnewin.jdk.nashorn.api.tree;

import jdk.nashorn.api.tree.RegExpLiteralTree;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link RegExpLiteralTree}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link RegExpLiteralTree} is a completely new class.
 * @since 9
 * @see RegExpLiteralTree
 */
public final class WhatIsNewInRegExpLiteralTree
{
  /**
   * Example call to new method {@link RegExpLiteralTree#getOptions()}.
   * @since 9
   * @see RegExpLiteralTree#getOptions()
   */
  public String getOptions()
  {
    RegExpLiteralTree testee = $$$();

    String result = testee.getOptions();
    return result;
  }

  /**
   * Example call to new method {@link RegExpLiteralTree#getPattern()}.
   * @since 9
   * @see RegExpLiteralTree#getPattern()
   */
  public String getPattern()
  {
    RegExpLiteralTree testee = $$$();

    String result = testee.getPattern();
    return result;
  }

  private RegExpLiteralTree $$$()
  {
    return null;
  }
}
