package whatisnewin.jdk.nashorn.api.tree;

import jdk.nashorn.api.tree.LoopTree;
import jdk.nashorn.api.tree.StatementTree;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link LoopTree}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link LoopTree} is a completely new class.
 * @since 9
 * @see LoopTree
 */
public final class WhatIsNewInLoopTree
{
  /**
   * Example call to new method {@link LoopTree#getStatement()}.
   * @since 9
   * @see LoopTree#getStatement()
   */
  public StatementTree getStatement()
  {
    LoopTree testee = $$$();

    StatementTree result = testee.getStatement();
    return result;
  }

  private LoopTree $$$()
  {
    return null;
  }
}
