package whatisnewin.jdk.nashorn.api.tree;

import jdk.nashorn.api.tree.ThrowTree;
import jdk.nashorn.api.tree.ExpressionTree;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link ThrowTree}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link ThrowTree} is a completely new class
 * @since 9
 * @see ThrowTree
 */
public final class WhatIsNewInThrowTree
{
  /**
   * Example call to new method {@link ThrowTree#getExpression}
   * @since 9
   * @see ThrowTree#getExpression
   */
  public ExpressionTree getExpression()
  {
    ThrowTree testee = $$$();

    ExpressionTree result = testee.getExpression();
    return result;
  }

  private ThrowTree $$$()
  {
    return null;
  }
}
