package whatisnewin.jdk.nashorn.api.tree;

import jdk.nashorn.api.tree.ParenthesizedTree;
import jdk.nashorn.api.tree.ExpressionTree;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link ParenthesizedTree}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link ParenthesizedTree} is a completely new class
 * @since 9
 * @see ParenthesizedTree
 */
public final class WhatIsNewInParenthesizedTree
{
  /**
   * Example call to new method {@link ParenthesizedTree#getExpression}
   * @since 9
   * @see ParenthesizedTree#getExpression
   */
  public ExpressionTree getExpression()
  {
    ParenthesizedTree testee = $$$();

    ExpressionTree result = testee.getExpression();
    return result;
  }

  private ParenthesizedTree $$$()
  {
    return null;
  }
}
