package whatisnewin.jdk.nashorn.api.tree;

import jdk.nashorn.api.tree.YieldTree;
import jdk.nashorn.api.tree.ExpressionTree;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link YieldTree}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link YieldTree} is a completely new class
 * @since 9
 * @see YieldTree
 */
public final class WhatIsNewInYieldTree
{
  /**
   * Example call to new method {@link YieldTree#getExpression}
   * @since 9
   * @see YieldTree#getExpression
   */
  public ExpressionTree getExpression()
  {
    YieldTree testee = $$$();

    ExpressionTree result = testee.getExpression();
    return result;
  }

  /**
   * Example call to new method {@link YieldTree#isStar}
   * @since 9
   * @see YieldTree#isStar
   */
  public boolean isStar()
  {
    YieldTree testee = $$$();

    boolean result = testee.isStar();
    return result;
  }

  private YieldTree $$$()
  {
    return null;
  }
}
