package whatisnewin.javax.imageio.plugins.tiff;

import javax.imageio.plugins.tiff.ExifInteroperabilityTagSet;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link ExifInteroperabilityTagSet}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link ExifInteroperabilityTagSet} is a completely new class
 * @since 9
 * @see ExifInteroperabilityTagSet
 */
public final class WhatIsNewInExifInteroperabilityTagSet
{
  /**
   * Example usage of the new field {@link ExifInteroperabilityTagSet#TAG_INTEROPERABILITY_INDEX}
   * @since 9
   * @see ExifInteroperabilityTagSet#TAG_INTEROPERABILITY_INDEX
   */
  public static  final int TAG_INTEROPERABILITY_INDEX = ExifInteroperabilityTagSet.TAG_INTEROPERABILITY_INDEX;

  /**
   * Example usage of the new field {@link ExifInteroperabilityTagSet#INTEROPERABILITY_INDEX_R98}
   * @since 9
   * @see ExifInteroperabilityTagSet#INTEROPERABILITY_INDEX_R98
   */
  public static  final String INTEROPERABILITY_INDEX_R98 = ExifInteroperabilityTagSet.INTEROPERABILITY_INDEX_R98;

  /**
   * Example usage of the new field {@link ExifInteroperabilityTagSet#INTEROPERABILITY_INDEX_THM}
   * @since 9
   * @see ExifInteroperabilityTagSet#INTEROPERABILITY_INDEX_THM
   */
  public static  final String INTEROPERABILITY_INDEX_THM = ExifInteroperabilityTagSet.INTEROPERABILITY_INDEX_THM;

  /**
   * Example call to new method {@link ExifInteroperabilityTagSet#getInstance}
   * @since 9
   * @see ExifInteroperabilityTagSet#getInstance
   */
  public static ExifInteroperabilityTagSet getInstance()
  {
    ExifInteroperabilityTagSet result = ExifInteroperabilityTagSet.getInstance();
    return result;
  }

}
