package whatisnewin.javax.imageio.plugins.tiff;

import javax.imageio.plugins.tiff.FaxTIFFTagSet;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link FaxTIFFTagSet}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link FaxTIFFTagSet} is a completely new class
 * @since 9
 * @see FaxTIFFTagSet
 */
public final class WhatIsNewInFaxTIFFTagSet
{
  /**
   * Example usage of the new field {@link FaxTIFFTagSet#TAG_BAD_FAX_LINES}
   * @since 9
   * @see FaxTIFFTagSet#TAG_BAD_FAX_LINES
   */
  public static  final int TAG_BAD_FAX_LINES = FaxTIFFTagSet.TAG_BAD_FAX_LINES;

  /**
   * Example usage of the new field {@link FaxTIFFTagSet#TAG_CLEAN_FAX_DATA}
   * @since 9
   * @see FaxTIFFTagSet#TAG_CLEAN_FAX_DATA
   */
  public static  final int TAG_CLEAN_FAX_DATA = FaxTIFFTagSet.TAG_CLEAN_FAX_DATA;

  /**
   * Example usage of the new field {@link FaxTIFFTagSet#CLEAN_FAX_DATA_NO_ERRORS}
   * @since 9
   * @see FaxTIFFTagSet#CLEAN_FAX_DATA_NO_ERRORS
   */
  public static  final int CLEAN_FAX_DATA_NO_ERRORS = FaxTIFFTagSet.CLEAN_FAX_DATA_NO_ERRORS;

  /**
   * Example usage of the new field {@link FaxTIFFTagSet#CLEAN_FAX_DATA_ERRORS_CORRECTED}
   * @since 9
   * @see FaxTIFFTagSet#CLEAN_FAX_DATA_ERRORS_CORRECTED
   */
  public static  final int CLEAN_FAX_DATA_ERRORS_CORRECTED = FaxTIFFTagSet.CLEAN_FAX_DATA_ERRORS_CORRECTED;

  /**
   * Example usage of the new field {@link FaxTIFFTagSet#CLEAN_FAX_DATA_ERRORS_UNCORRECTED}
   * @since 9
   * @see FaxTIFFTagSet#CLEAN_FAX_DATA_ERRORS_UNCORRECTED
   */
  public static  final int CLEAN_FAX_DATA_ERRORS_UNCORRECTED = FaxTIFFTagSet.CLEAN_FAX_DATA_ERRORS_UNCORRECTED;

  /**
   * Example usage of the new field {@link FaxTIFFTagSet#TAG_CONSECUTIVE_BAD_LINES}
   * @since 9
   * @see FaxTIFFTagSet#TAG_CONSECUTIVE_BAD_LINES
   */
  public static  final int TAG_CONSECUTIVE_BAD_LINES = FaxTIFFTagSet.TAG_CONSECUTIVE_BAD_LINES;

  /**
   * Example call to new method {@link FaxTIFFTagSet#getInstance}
   * @since 9
   * @see FaxTIFFTagSet#getInstance
   */
  public static FaxTIFFTagSet getInstance()
  {
    FaxTIFFTagSet result = FaxTIFFTagSet.getInstance();
    return result;
  }

}
