package whatisnewin.javax.imageio.plugins.tiff;

import javax.imageio.plugins.tiff.ExifParentTIFFTagSet;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link ExifParentTIFFTagSet}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link ExifParentTIFFTagSet} is a completely new class.
 * @since 9
 * @see ExifParentTIFFTagSet
 */
public final class WhatIsNewInExifParentTIFFTagSet
{
  /**
   * Example usage of the new field {@link ExifParentTIFFTagSet#TAG_EXIF_IFD_POINTER}.
   * @since 9
   * @see ExifParentTIFFTagSet#TAG_EXIF_IFD_POINTER
   */
  public static final int TAG_EXIF_IFD_POINTER = ExifParentTIFFTagSet.TAG_EXIF_IFD_POINTER;

  /**
   * Example usage of the new field {@link ExifParentTIFFTagSet#TAG_GPS_INFO_IFD_POINTER}.
   * @since 9
   * @see ExifParentTIFFTagSet#TAG_GPS_INFO_IFD_POINTER
   */
  public static final int TAG_GPS_INFO_IFD_POINTER = ExifParentTIFFTagSet.TAG_GPS_INFO_IFD_POINTER;

  /**
   * Example call to new method {@link ExifParentTIFFTagSet#getInstance()}.
   * @since 9
   * @see ExifParentTIFFTagSet#getInstance()
   */
  public static ExifParentTIFFTagSet getInstance()
  {
    ExifParentTIFFTagSet result = ExifParentTIFFTagSet.getInstance();
    return result;
  }

}
