package whatisnewin.javax.imageio.plugins.tiff;

import javax.imageio.plugins.tiff.BaselineTIFFTagSet;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link BaselineTIFFTagSet}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link BaselineTIFFTagSet} is a completely new class.
 * @since 9
 * @see BaselineTIFFTagSet
 */
public final class WhatIsNewInBaselineTIFFTagSet
{
  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_NEW_SUBFILE_TYPE}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_NEW_SUBFILE_TYPE
   */
  public static final int TAG_NEW_SUBFILE_TYPE = BaselineTIFFTagSet.TAG_NEW_SUBFILE_TYPE;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#NEW_SUBFILE_TYPE_REDUCED_RESOLUTION}.
   * @since 9
   * @see BaselineTIFFTagSet#NEW_SUBFILE_TYPE_REDUCED_RESOLUTION
   */
  public static final int NEW_SUBFILE_TYPE_REDUCED_RESOLUTION = BaselineTIFFTagSet.NEW_SUBFILE_TYPE_REDUCED_RESOLUTION;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#NEW_SUBFILE_TYPE_SINGLE_PAGE}.
   * @since 9
   * @see BaselineTIFFTagSet#NEW_SUBFILE_TYPE_SINGLE_PAGE
   */
  public static final int NEW_SUBFILE_TYPE_SINGLE_PAGE = BaselineTIFFTagSet.NEW_SUBFILE_TYPE_SINGLE_PAGE;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#NEW_SUBFILE_TYPE_TRANSPARENCY}.
   * @since 9
   * @see BaselineTIFFTagSet#NEW_SUBFILE_TYPE_TRANSPARENCY
   */
  public static final int NEW_SUBFILE_TYPE_TRANSPARENCY = BaselineTIFFTagSet.NEW_SUBFILE_TYPE_TRANSPARENCY;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_SUBFILE_TYPE}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_SUBFILE_TYPE
   */
  public static final int TAG_SUBFILE_TYPE = BaselineTIFFTagSet.TAG_SUBFILE_TYPE;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#SUBFILE_TYPE_FULL_RESOLUTION}.
   * @since 9
   * @see BaselineTIFFTagSet#SUBFILE_TYPE_FULL_RESOLUTION
   */
  public static final int SUBFILE_TYPE_FULL_RESOLUTION = BaselineTIFFTagSet.SUBFILE_TYPE_FULL_RESOLUTION;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#SUBFILE_TYPE_REDUCED_RESOLUTION}.
   * @since 9
   * @see BaselineTIFFTagSet#SUBFILE_TYPE_REDUCED_RESOLUTION
   */
  public static final int SUBFILE_TYPE_REDUCED_RESOLUTION = BaselineTIFFTagSet.SUBFILE_TYPE_REDUCED_RESOLUTION;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#SUBFILE_TYPE_SINGLE_PAGE}.
   * @since 9
   * @see BaselineTIFFTagSet#SUBFILE_TYPE_SINGLE_PAGE
   */
  public static final int SUBFILE_TYPE_SINGLE_PAGE = BaselineTIFFTagSet.SUBFILE_TYPE_SINGLE_PAGE;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_IMAGE_WIDTH}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_IMAGE_WIDTH
   */
  public static final int TAG_IMAGE_WIDTH = BaselineTIFFTagSet.TAG_IMAGE_WIDTH;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_IMAGE_LENGTH}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_IMAGE_LENGTH
   */
  public static final int TAG_IMAGE_LENGTH = BaselineTIFFTagSet.TAG_IMAGE_LENGTH;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_BITS_PER_SAMPLE}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_BITS_PER_SAMPLE
   */
  public static final int TAG_BITS_PER_SAMPLE = BaselineTIFFTagSet.TAG_BITS_PER_SAMPLE;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_COMPRESSION}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_COMPRESSION
   */
  public static final int TAG_COMPRESSION = BaselineTIFFTagSet.TAG_COMPRESSION;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#COMPRESSION_NONE}.
   * @since 9
   * @see BaselineTIFFTagSet#COMPRESSION_NONE
   */
  public static final int COMPRESSION_NONE = BaselineTIFFTagSet.COMPRESSION_NONE;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#COMPRESSION_CCITT_RLE}.
   * @since 9
   * @see BaselineTIFFTagSet#COMPRESSION_CCITT_RLE
   */
  public static final int COMPRESSION_CCITT_RLE = BaselineTIFFTagSet.COMPRESSION_CCITT_RLE;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#COMPRESSION_CCITT_T_4}.
   * @since 9
   * @see BaselineTIFFTagSet#COMPRESSION_CCITT_T_4
   */
  public static final int COMPRESSION_CCITT_T_4 = BaselineTIFFTagSet.COMPRESSION_CCITT_T_4;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#COMPRESSION_CCITT_T_6}.
   * @since 9
   * @see BaselineTIFFTagSet#COMPRESSION_CCITT_T_6
   */
  public static final int COMPRESSION_CCITT_T_6 = BaselineTIFFTagSet.COMPRESSION_CCITT_T_6;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#COMPRESSION_LZW}.
   * @since 9
   * @see BaselineTIFFTagSet#COMPRESSION_LZW
   */
  public static final int COMPRESSION_LZW = BaselineTIFFTagSet.COMPRESSION_LZW;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#COMPRESSION_OLD_JPEG}.
   * @since 9
   * @see BaselineTIFFTagSet#COMPRESSION_OLD_JPEG
   */
  public static final int COMPRESSION_OLD_JPEG = BaselineTIFFTagSet.COMPRESSION_OLD_JPEG;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#COMPRESSION_JPEG}.
   * @since 9
   * @see BaselineTIFFTagSet#COMPRESSION_JPEG
   */
  public static final int COMPRESSION_JPEG = BaselineTIFFTagSet.COMPRESSION_JPEG;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#COMPRESSION_ZLIB}.
   * @since 9
   * @see BaselineTIFFTagSet#COMPRESSION_ZLIB
   */
  public static final int COMPRESSION_ZLIB = BaselineTIFFTagSet.COMPRESSION_ZLIB;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#COMPRESSION_PACKBITS}.
   * @since 9
   * @see BaselineTIFFTagSet#COMPRESSION_PACKBITS
   */
  public static final int COMPRESSION_PACKBITS = BaselineTIFFTagSet.COMPRESSION_PACKBITS;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#COMPRESSION_DEFLATE}.
   * @since 9
   * @see BaselineTIFFTagSet#COMPRESSION_DEFLATE
   */
  public static final int COMPRESSION_DEFLATE = BaselineTIFFTagSet.COMPRESSION_DEFLATE;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_PHOTOMETRIC_INTERPRETATION}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_PHOTOMETRIC_INTERPRETATION
   */
  public static final int TAG_PHOTOMETRIC_INTERPRETATION = BaselineTIFFTagSet.TAG_PHOTOMETRIC_INTERPRETATION;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#PHOTOMETRIC_INTERPRETATION_WHITE_IS_ZERO}.
   * @since 9
   * @see BaselineTIFFTagSet#PHOTOMETRIC_INTERPRETATION_WHITE_IS_ZERO
   */
  public static final int PHOTOMETRIC_INTERPRETATION_WHITE_IS_ZERO = BaselineTIFFTagSet.PHOTOMETRIC_INTERPRETATION_WHITE_IS_ZERO;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#PHOTOMETRIC_INTERPRETATION_BLACK_IS_ZERO}.
   * @since 9
   * @see BaselineTIFFTagSet#PHOTOMETRIC_INTERPRETATION_BLACK_IS_ZERO
   */
  public static final int PHOTOMETRIC_INTERPRETATION_BLACK_IS_ZERO = BaselineTIFFTagSet.PHOTOMETRIC_INTERPRETATION_BLACK_IS_ZERO;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#PHOTOMETRIC_INTERPRETATION_RGB}.
   * @since 9
   * @see BaselineTIFFTagSet#PHOTOMETRIC_INTERPRETATION_RGB
   */
  public static final int PHOTOMETRIC_INTERPRETATION_RGB = BaselineTIFFTagSet.PHOTOMETRIC_INTERPRETATION_RGB;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#PHOTOMETRIC_INTERPRETATION_PALETTE_COLOR}.
   * @since 9
   * @see BaselineTIFFTagSet#PHOTOMETRIC_INTERPRETATION_PALETTE_COLOR
   */
  public static final int PHOTOMETRIC_INTERPRETATION_PALETTE_COLOR = BaselineTIFFTagSet.PHOTOMETRIC_INTERPRETATION_PALETTE_COLOR;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#PHOTOMETRIC_INTERPRETATION_TRANSPARENCY_MASK}.
   * @since 9
   * @see BaselineTIFFTagSet#PHOTOMETRIC_INTERPRETATION_TRANSPARENCY_MASK
   */
  public static final int PHOTOMETRIC_INTERPRETATION_TRANSPARENCY_MASK = BaselineTIFFTagSet.PHOTOMETRIC_INTERPRETATION_TRANSPARENCY_MASK;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#PHOTOMETRIC_INTERPRETATION_CMYK}.
   * @since 9
   * @see BaselineTIFFTagSet#PHOTOMETRIC_INTERPRETATION_CMYK
   */
  public static final int PHOTOMETRIC_INTERPRETATION_CMYK = BaselineTIFFTagSet.PHOTOMETRIC_INTERPRETATION_CMYK;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#PHOTOMETRIC_INTERPRETATION_Y_CB_CR}.
   * @since 9
   * @see BaselineTIFFTagSet#PHOTOMETRIC_INTERPRETATION_Y_CB_CR
   */
  public static final int PHOTOMETRIC_INTERPRETATION_Y_CB_CR = BaselineTIFFTagSet.PHOTOMETRIC_INTERPRETATION_Y_CB_CR;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#PHOTOMETRIC_INTERPRETATION_CIELAB}.
   * @since 9
   * @see BaselineTIFFTagSet#PHOTOMETRIC_INTERPRETATION_CIELAB
   */
  public static final int PHOTOMETRIC_INTERPRETATION_CIELAB = BaselineTIFFTagSet.PHOTOMETRIC_INTERPRETATION_CIELAB;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#PHOTOMETRIC_INTERPRETATION_ICCLAB}.
   * @since 9
   * @see BaselineTIFFTagSet#PHOTOMETRIC_INTERPRETATION_ICCLAB
   */
  public static final int PHOTOMETRIC_INTERPRETATION_ICCLAB = BaselineTIFFTagSet.PHOTOMETRIC_INTERPRETATION_ICCLAB;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_THRESHHOLDING}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_THRESHHOLDING
   */
  public static final int TAG_THRESHHOLDING = BaselineTIFFTagSet.TAG_THRESHHOLDING;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#THRESHHOLDING_NONE}.
   * @since 9
   * @see BaselineTIFFTagSet#THRESHHOLDING_NONE
   */
  public static final int THRESHHOLDING_NONE = BaselineTIFFTagSet.THRESHHOLDING_NONE;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#THRESHHOLDING_ORDERED_DITHER}.
   * @since 9
   * @see BaselineTIFFTagSet#THRESHHOLDING_ORDERED_DITHER
   */
  public static final int THRESHHOLDING_ORDERED_DITHER = BaselineTIFFTagSet.THRESHHOLDING_ORDERED_DITHER;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#THRESHHOLDING_RANDOMIZED_DITHER}.
   * @since 9
   * @see BaselineTIFFTagSet#THRESHHOLDING_RANDOMIZED_DITHER
   */
  public static final int THRESHHOLDING_RANDOMIZED_DITHER = BaselineTIFFTagSet.THRESHHOLDING_RANDOMIZED_DITHER;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_CELL_WIDTH}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_CELL_WIDTH
   */
  public static final int TAG_CELL_WIDTH = BaselineTIFFTagSet.TAG_CELL_WIDTH;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_CELL_LENGTH}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_CELL_LENGTH
   */
  public static final int TAG_CELL_LENGTH = BaselineTIFFTagSet.TAG_CELL_LENGTH;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_FILL_ORDER}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_FILL_ORDER
   */
  public static final int TAG_FILL_ORDER = BaselineTIFFTagSet.TAG_FILL_ORDER;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#FILL_ORDER_LEFT_TO_RIGHT}.
   * @since 9
   * @see BaselineTIFFTagSet#FILL_ORDER_LEFT_TO_RIGHT
   */
  public static final int FILL_ORDER_LEFT_TO_RIGHT = BaselineTIFFTagSet.FILL_ORDER_LEFT_TO_RIGHT;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#FILL_ORDER_RIGHT_TO_LEFT}.
   * @since 9
   * @see BaselineTIFFTagSet#FILL_ORDER_RIGHT_TO_LEFT
   */
  public static final int FILL_ORDER_RIGHT_TO_LEFT = BaselineTIFFTagSet.FILL_ORDER_RIGHT_TO_LEFT;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_DOCUMENT_NAME}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_DOCUMENT_NAME
   */
  public static final int TAG_DOCUMENT_NAME = BaselineTIFFTagSet.TAG_DOCUMENT_NAME;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_IMAGE_DESCRIPTION}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_IMAGE_DESCRIPTION
   */
  public static final int TAG_IMAGE_DESCRIPTION = BaselineTIFFTagSet.TAG_IMAGE_DESCRIPTION;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_MAKE}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_MAKE
   */
  public static final int TAG_MAKE = BaselineTIFFTagSet.TAG_MAKE;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_MODEL}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_MODEL
   */
  public static final int TAG_MODEL = BaselineTIFFTagSet.TAG_MODEL;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_STRIP_OFFSETS}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_STRIP_OFFSETS
   */
  public static final int TAG_STRIP_OFFSETS = BaselineTIFFTagSet.TAG_STRIP_OFFSETS;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_ORIENTATION}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_ORIENTATION
   */
  public static final int TAG_ORIENTATION = BaselineTIFFTagSet.TAG_ORIENTATION;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#ORIENTATION_ROW_0_TOP_COLUMN_0_LEFT}.
   * @since 9
   * @see BaselineTIFFTagSet#ORIENTATION_ROW_0_TOP_COLUMN_0_LEFT
   */
  public static final int ORIENTATION_ROW_0_TOP_COLUMN_0_LEFT = BaselineTIFFTagSet.ORIENTATION_ROW_0_TOP_COLUMN_0_LEFT;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#ORIENTATION_ROW_0_TOP_COLUMN_0_RIGHT}.
   * @since 9
   * @see BaselineTIFFTagSet#ORIENTATION_ROW_0_TOP_COLUMN_0_RIGHT
   */
  public static final int ORIENTATION_ROW_0_TOP_COLUMN_0_RIGHT = BaselineTIFFTagSet.ORIENTATION_ROW_0_TOP_COLUMN_0_RIGHT;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#ORIENTATION_ROW_0_BOTTOM_COLUMN_0_RIGHT}.
   * @since 9
   * @see BaselineTIFFTagSet#ORIENTATION_ROW_0_BOTTOM_COLUMN_0_RIGHT
   */
  public static final int ORIENTATION_ROW_0_BOTTOM_COLUMN_0_RIGHT = BaselineTIFFTagSet.ORIENTATION_ROW_0_BOTTOM_COLUMN_0_RIGHT;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#ORIENTATION_ROW_0_BOTTOM_COLUMN_0_LEFT}.
   * @since 9
   * @see BaselineTIFFTagSet#ORIENTATION_ROW_0_BOTTOM_COLUMN_0_LEFT
   */
  public static final int ORIENTATION_ROW_0_BOTTOM_COLUMN_0_LEFT = BaselineTIFFTagSet.ORIENTATION_ROW_0_BOTTOM_COLUMN_0_LEFT;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#ORIENTATION_ROW_0_LEFT_COLUMN_0_TOP}.
   * @since 9
   * @see BaselineTIFFTagSet#ORIENTATION_ROW_0_LEFT_COLUMN_0_TOP
   */
  public static final int ORIENTATION_ROW_0_LEFT_COLUMN_0_TOP = BaselineTIFFTagSet.ORIENTATION_ROW_0_LEFT_COLUMN_0_TOP;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#ORIENTATION_ROW_0_RIGHT_COLUMN_0_TOP}.
   * @since 9
   * @see BaselineTIFFTagSet#ORIENTATION_ROW_0_RIGHT_COLUMN_0_TOP
   */
  public static final int ORIENTATION_ROW_0_RIGHT_COLUMN_0_TOP = BaselineTIFFTagSet.ORIENTATION_ROW_0_RIGHT_COLUMN_0_TOP;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#ORIENTATION_ROW_0_RIGHT_COLUMN_0_BOTTOM}.
   * @since 9
   * @see BaselineTIFFTagSet#ORIENTATION_ROW_0_RIGHT_COLUMN_0_BOTTOM
   */
  public static final int ORIENTATION_ROW_0_RIGHT_COLUMN_0_BOTTOM = BaselineTIFFTagSet.ORIENTATION_ROW_0_RIGHT_COLUMN_0_BOTTOM;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#ORIENTATION_ROW_0_LEFT_COLUMN_0_BOTTOM}.
   * @since 9
   * @see BaselineTIFFTagSet#ORIENTATION_ROW_0_LEFT_COLUMN_0_BOTTOM
   */
  public static final int ORIENTATION_ROW_0_LEFT_COLUMN_0_BOTTOM = BaselineTIFFTagSet.ORIENTATION_ROW_0_LEFT_COLUMN_0_BOTTOM;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_SAMPLES_PER_PIXEL}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_SAMPLES_PER_PIXEL
   */
  public static final int TAG_SAMPLES_PER_PIXEL = BaselineTIFFTagSet.TAG_SAMPLES_PER_PIXEL;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_ROWS_PER_STRIP}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_ROWS_PER_STRIP
   */
  public static final int TAG_ROWS_PER_STRIP = BaselineTIFFTagSet.TAG_ROWS_PER_STRIP;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_STRIP_BYTE_COUNTS}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_STRIP_BYTE_COUNTS
   */
  public static final int TAG_STRIP_BYTE_COUNTS = BaselineTIFFTagSet.TAG_STRIP_BYTE_COUNTS;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_MIN_SAMPLE_VALUE}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_MIN_SAMPLE_VALUE
   */
  public static final int TAG_MIN_SAMPLE_VALUE = BaselineTIFFTagSet.TAG_MIN_SAMPLE_VALUE;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_MAX_SAMPLE_VALUE}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_MAX_SAMPLE_VALUE
   */
  public static final int TAG_MAX_SAMPLE_VALUE = BaselineTIFFTagSet.TAG_MAX_SAMPLE_VALUE;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_X_RESOLUTION}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_X_RESOLUTION
   */
  public static final int TAG_X_RESOLUTION = BaselineTIFFTagSet.TAG_X_RESOLUTION;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_Y_RESOLUTION}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_Y_RESOLUTION
   */
  public static final int TAG_Y_RESOLUTION = BaselineTIFFTagSet.TAG_Y_RESOLUTION;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_PLANAR_CONFIGURATION}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_PLANAR_CONFIGURATION
   */
  public static final int TAG_PLANAR_CONFIGURATION = BaselineTIFFTagSet.TAG_PLANAR_CONFIGURATION;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#PLANAR_CONFIGURATION_CHUNKY}.
   * @since 9
   * @see BaselineTIFFTagSet#PLANAR_CONFIGURATION_CHUNKY
   */
  public static final int PLANAR_CONFIGURATION_CHUNKY = BaselineTIFFTagSet.PLANAR_CONFIGURATION_CHUNKY;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#PLANAR_CONFIGURATION_PLANAR}.
   * @since 9
   * @see BaselineTIFFTagSet#PLANAR_CONFIGURATION_PLANAR
   */
  public static final int PLANAR_CONFIGURATION_PLANAR = BaselineTIFFTagSet.PLANAR_CONFIGURATION_PLANAR;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_PAGE_NAME}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_PAGE_NAME
   */
  public static final int TAG_PAGE_NAME = BaselineTIFFTagSet.TAG_PAGE_NAME;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_X_POSITION}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_X_POSITION
   */
  public static final int TAG_X_POSITION = BaselineTIFFTagSet.TAG_X_POSITION;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_Y_POSITION}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_Y_POSITION
   */
  public static final int TAG_Y_POSITION = BaselineTIFFTagSet.TAG_Y_POSITION;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_FREE_OFFSETS}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_FREE_OFFSETS
   */
  public static final int TAG_FREE_OFFSETS = BaselineTIFFTagSet.TAG_FREE_OFFSETS;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_FREE_BYTE_COUNTS}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_FREE_BYTE_COUNTS
   */
  public static final int TAG_FREE_BYTE_COUNTS = BaselineTIFFTagSet.TAG_FREE_BYTE_COUNTS;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_GRAY_RESPONSE_UNIT}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_GRAY_RESPONSE_UNIT
   */
  public static final int TAG_GRAY_RESPONSE_UNIT = BaselineTIFFTagSet.TAG_GRAY_RESPONSE_UNIT;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#GRAY_RESPONSE_UNIT_TENTHS}.
   * @since 9
   * @see BaselineTIFFTagSet#GRAY_RESPONSE_UNIT_TENTHS
   */
  public static final int GRAY_RESPONSE_UNIT_TENTHS = BaselineTIFFTagSet.GRAY_RESPONSE_UNIT_TENTHS;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#GRAY_RESPONSE_UNIT_HUNDREDTHS}.
   * @since 9
   * @see BaselineTIFFTagSet#GRAY_RESPONSE_UNIT_HUNDREDTHS
   */
  public static final int GRAY_RESPONSE_UNIT_HUNDREDTHS = BaselineTIFFTagSet.GRAY_RESPONSE_UNIT_HUNDREDTHS;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#GRAY_RESPONSE_UNIT_THOUSANDTHS}.
   * @since 9
   * @see BaselineTIFFTagSet#GRAY_RESPONSE_UNIT_THOUSANDTHS
   */
  public static final int GRAY_RESPONSE_UNIT_THOUSANDTHS = BaselineTIFFTagSet.GRAY_RESPONSE_UNIT_THOUSANDTHS;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#GRAY_RESPONSE_UNIT_TEN_THOUSANDTHS}.
   * @since 9
   * @see BaselineTIFFTagSet#GRAY_RESPONSE_UNIT_TEN_THOUSANDTHS
   */
  public static final int GRAY_RESPONSE_UNIT_TEN_THOUSANDTHS = BaselineTIFFTagSet.GRAY_RESPONSE_UNIT_TEN_THOUSANDTHS;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#GRAY_RESPONSE_UNIT_HUNDRED_THOUSANDTHS}.
   * @since 9
   * @see BaselineTIFFTagSet#GRAY_RESPONSE_UNIT_HUNDRED_THOUSANDTHS
   */
  public static final int GRAY_RESPONSE_UNIT_HUNDRED_THOUSANDTHS = BaselineTIFFTagSet.GRAY_RESPONSE_UNIT_HUNDRED_THOUSANDTHS;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_GRAY_RESPONSE_CURVE}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_GRAY_RESPONSE_CURVE
   */
  public static final int TAG_GRAY_RESPONSE_CURVE = BaselineTIFFTagSet.TAG_GRAY_RESPONSE_CURVE;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_T4_OPTIONS}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_T4_OPTIONS
   */
  public static final int TAG_T4_OPTIONS = BaselineTIFFTagSet.TAG_T4_OPTIONS;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#T4_OPTIONS_2D_CODING}.
   * @since 9
   * @see BaselineTIFFTagSet#T4_OPTIONS_2D_CODING
   */
  public static final int T4_OPTIONS_2D_CODING = BaselineTIFFTagSet.T4_OPTIONS_2D_CODING;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#T4_OPTIONS_UNCOMPRESSED}.
   * @since 9
   * @see BaselineTIFFTagSet#T4_OPTIONS_UNCOMPRESSED
   */
  public static final int T4_OPTIONS_UNCOMPRESSED = BaselineTIFFTagSet.T4_OPTIONS_UNCOMPRESSED;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#T4_OPTIONS_EOL_BYTE_ALIGNED}.
   * @since 9
   * @see BaselineTIFFTagSet#T4_OPTIONS_EOL_BYTE_ALIGNED
   */
  public static final int T4_OPTIONS_EOL_BYTE_ALIGNED = BaselineTIFFTagSet.T4_OPTIONS_EOL_BYTE_ALIGNED;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_T6_OPTIONS}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_T6_OPTIONS
   */
  public static final int TAG_T6_OPTIONS = BaselineTIFFTagSet.TAG_T6_OPTIONS;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#T6_OPTIONS_UNCOMPRESSED}.
   * @since 9
   * @see BaselineTIFFTagSet#T6_OPTIONS_UNCOMPRESSED
   */
  public static final int T6_OPTIONS_UNCOMPRESSED = BaselineTIFFTagSet.T6_OPTIONS_UNCOMPRESSED;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_RESOLUTION_UNIT}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_RESOLUTION_UNIT
   */
  public static final int TAG_RESOLUTION_UNIT = BaselineTIFFTagSet.TAG_RESOLUTION_UNIT;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#RESOLUTION_UNIT_NONE}.
   * @since 9
   * @see BaselineTIFFTagSet#RESOLUTION_UNIT_NONE
   */
  public static final int RESOLUTION_UNIT_NONE = BaselineTIFFTagSet.RESOLUTION_UNIT_NONE;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#RESOLUTION_UNIT_INCH}.
   * @since 9
   * @see BaselineTIFFTagSet#RESOLUTION_UNIT_INCH
   */
  public static final int RESOLUTION_UNIT_INCH = BaselineTIFFTagSet.RESOLUTION_UNIT_INCH;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#RESOLUTION_UNIT_CENTIMETER}.
   * @since 9
   * @see BaselineTIFFTagSet#RESOLUTION_UNIT_CENTIMETER
   */
  public static final int RESOLUTION_UNIT_CENTIMETER = BaselineTIFFTagSet.RESOLUTION_UNIT_CENTIMETER;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_PAGE_NUMBER}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_PAGE_NUMBER
   */
  public static final int TAG_PAGE_NUMBER = BaselineTIFFTagSet.TAG_PAGE_NUMBER;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_TRANSFER_FUNCTION}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_TRANSFER_FUNCTION
   */
  public static final int TAG_TRANSFER_FUNCTION = BaselineTIFFTagSet.TAG_TRANSFER_FUNCTION;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_SOFTWARE}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_SOFTWARE
   */
  public static final int TAG_SOFTWARE = BaselineTIFFTagSet.TAG_SOFTWARE;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_DATE_TIME}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_DATE_TIME
   */
  public static final int TAG_DATE_TIME = BaselineTIFFTagSet.TAG_DATE_TIME;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_ARTIST}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_ARTIST
   */
  public static final int TAG_ARTIST = BaselineTIFFTagSet.TAG_ARTIST;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_HOST_COMPUTER}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_HOST_COMPUTER
   */
  public static final int TAG_HOST_COMPUTER = BaselineTIFFTagSet.TAG_HOST_COMPUTER;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_PREDICTOR}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_PREDICTOR
   */
  public static final int TAG_PREDICTOR = BaselineTIFFTagSet.TAG_PREDICTOR;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#PREDICTOR_NONE}.
   * @since 9
   * @see BaselineTIFFTagSet#PREDICTOR_NONE
   */
  public static final int PREDICTOR_NONE = BaselineTIFFTagSet.PREDICTOR_NONE;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#PREDICTOR_HORIZONTAL_DIFFERENCING}.
   * @since 9
   * @see BaselineTIFFTagSet#PREDICTOR_HORIZONTAL_DIFFERENCING
   */
  public static final int PREDICTOR_HORIZONTAL_DIFFERENCING = BaselineTIFFTagSet.PREDICTOR_HORIZONTAL_DIFFERENCING;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_WHITE_POINT}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_WHITE_POINT
   */
  public static final int TAG_WHITE_POINT = BaselineTIFFTagSet.TAG_WHITE_POINT;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_PRIMARY_CHROMATICITES}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_PRIMARY_CHROMATICITES
   */
  public static final int TAG_PRIMARY_CHROMATICITES = BaselineTIFFTagSet.TAG_PRIMARY_CHROMATICITES;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_COLOR_MAP}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_COLOR_MAP
   */
  public static final int TAG_COLOR_MAP = BaselineTIFFTagSet.TAG_COLOR_MAP;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_HALFTONE_HINTS}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_HALFTONE_HINTS
   */
  public static final int TAG_HALFTONE_HINTS = BaselineTIFFTagSet.TAG_HALFTONE_HINTS;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_TILE_WIDTH}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_TILE_WIDTH
   */
  public static final int TAG_TILE_WIDTH = BaselineTIFFTagSet.TAG_TILE_WIDTH;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_TILE_LENGTH}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_TILE_LENGTH
   */
  public static final int TAG_TILE_LENGTH = BaselineTIFFTagSet.TAG_TILE_LENGTH;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_TILE_OFFSETS}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_TILE_OFFSETS
   */
  public static final int TAG_TILE_OFFSETS = BaselineTIFFTagSet.TAG_TILE_OFFSETS;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_TILE_BYTE_COUNTS}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_TILE_BYTE_COUNTS
   */
  public static final int TAG_TILE_BYTE_COUNTS = BaselineTIFFTagSet.TAG_TILE_BYTE_COUNTS;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_INK_SET}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_INK_SET
   */
  public static final int TAG_INK_SET = BaselineTIFFTagSet.TAG_INK_SET;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#INK_SET_CMYK}.
   * @since 9
   * @see BaselineTIFFTagSet#INK_SET_CMYK
   */
  public static final int INK_SET_CMYK = BaselineTIFFTagSet.INK_SET_CMYK;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#INK_SET_NOT_CMYK}.
   * @since 9
   * @see BaselineTIFFTagSet#INK_SET_NOT_CMYK
   */
  public static final int INK_SET_NOT_CMYK = BaselineTIFFTagSet.INK_SET_NOT_CMYK;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_INK_NAMES}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_INK_NAMES
   */
  public static final int TAG_INK_NAMES = BaselineTIFFTagSet.TAG_INK_NAMES;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_NUMBER_OF_INKS}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_NUMBER_OF_INKS
   */
  public static final int TAG_NUMBER_OF_INKS = BaselineTIFFTagSet.TAG_NUMBER_OF_INKS;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_DOT_RANGE}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_DOT_RANGE
   */
  public static final int TAG_DOT_RANGE = BaselineTIFFTagSet.TAG_DOT_RANGE;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_TARGET_PRINTER}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_TARGET_PRINTER
   */
  public static final int TAG_TARGET_PRINTER = BaselineTIFFTagSet.TAG_TARGET_PRINTER;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_EXTRA_SAMPLES}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_EXTRA_SAMPLES
   */
  public static final int TAG_EXTRA_SAMPLES = BaselineTIFFTagSet.TAG_EXTRA_SAMPLES;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#EXTRA_SAMPLES_UNSPECIFIED}.
   * @since 9
   * @see BaselineTIFFTagSet#EXTRA_SAMPLES_UNSPECIFIED
   */
  public static final int EXTRA_SAMPLES_UNSPECIFIED = BaselineTIFFTagSet.EXTRA_SAMPLES_UNSPECIFIED;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#EXTRA_SAMPLES_ASSOCIATED_ALPHA}.
   * @since 9
   * @see BaselineTIFFTagSet#EXTRA_SAMPLES_ASSOCIATED_ALPHA
   */
  public static final int EXTRA_SAMPLES_ASSOCIATED_ALPHA = BaselineTIFFTagSet.EXTRA_SAMPLES_ASSOCIATED_ALPHA;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#EXTRA_SAMPLES_UNASSOCIATED_ALPHA}.
   * @since 9
   * @see BaselineTIFFTagSet#EXTRA_SAMPLES_UNASSOCIATED_ALPHA
   */
  public static final int EXTRA_SAMPLES_UNASSOCIATED_ALPHA = BaselineTIFFTagSet.EXTRA_SAMPLES_UNASSOCIATED_ALPHA;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_SAMPLE_FORMAT}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_SAMPLE_FORMAT
   */
  public static final int TAG_SAMPLE_FORMAT = BaselineTIFFTagSet.TAG_SAMPLE_FORMAT;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#SAMPLE_FORMAT_UNSIGNED_INTEGER}.
   * @since 9
   * @see BaselineTIFFTagSet#SAMPLE_FORMAT_UNSIGNED_INTEGER
   */
  public static final int SAMPLE_FORMAT_UNSIGNED_INTEGER = BaselineTIFFTagSet.SAMPLE_FORMAT_UNSIGNED_INTEGER;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#SAMPLE_FORMAT_SIGNED_INTEGER}.
   * @since 9
   * @see BaselineTIFFTagSet#SAMPLE_FORMAT_SIGNED_INTEGER
   */
  public static final int SAMPLE_FORMAT_SIGNED_INTEGER = BaselineTIFFTagSet.SAMPLE_FORMAT_SIGNED_INTEGER;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#SAMPLE_FORMAT_FLOATING_POINT}.
   * @since 9
   * @see BaselineTIFFTagSet#SAMPLE_FORMAT_FLOATING_POINT
   */
  public static final int SAMPLE_FORMAT_FLOATING_POINT = BaselineTIFFTagSet.SAMPLE_FORMAT_FLOATING_POINT;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#SAMPLE_FORMAT_UNDEFINED}.
   * @since 9
   * @see BaselineTIFFTagSet#SAMPLE_FORMAT_UNDEFINED
   */
  public static final int SAMPLE_FORMAT_UNDEFINED = BaselineTIFFTagSet.SAMPLE_FORMAT_UNDEFINED;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_S_MIN_SAMPLE_VALUE}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_S_MIN_SAMPLE_VALUE
   */
  public static final int TAG_S_MIN_SAMPLE_VALUE = BaselineTIFFTagSet.TAG_S_MIN_SAMPLE_VALUE;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_S_MAX_SAMPLE_VALUE}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_S_MAX_SAMPLE_VALUE
   */
  public static final int TAG_S_MAX_SAMPLE_VALUE = BaselineTIFFTagSet.TAG_S_MAX_SAMPLE_VALUE;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_TRANSFER_RANGE}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_TRANSFER_RANGE
   */
  public static final int TAG_TRANSFER_RANGE = BaselineTIFFTagSet.TAG_TRANSFER_RANGE;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_JPEG_TABLES}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_JPEG_TABLES
   */
  public static final int TAG_JPEG_TABLES = BaselineTIFFTagSet.TAG_JPEG_TABLES;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_JPEG_PROC}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_JPEG_PROC
   */
  public static final int TAG_JPEG_PROC = BaselineTIFFTagSet.TAG_JPEG_PROC;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#JPEG_PROC_BASELINE}.
   * @since 9
   * @see BaselineTIFFTagSet#JPEG_PROC_BASELINE
   */
  public static final int JPEG_PROC_BASELINE = BaselineTIFFTagSet.JPEG_PROC_BASELINE;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#JPEG_PROC_LOSSLESS}.
   * @since 9
   * @see BaselineTIFFTagSet#JPEG_PROC_LOSSLESS
   */
  public static final int JPEG_PROC_LOSSLESS = BaselineTIFFTagSet.JPEG_PROC_LOSSLESS;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_JPEG_INTERCHANGE_FORMAT}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_JPEG_INTERCHANGE_FORMAT
   */
  public static final int TAG_JPEG_INTERCHANGE_FORMAT = BaselineTIFFTagSet.TAG_JPEG_INTERCHANGE_FORMAT;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_JPEG_INTERCHANGE_FORMAT_LENGTH}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_JPEG_INTERCHANGE_FORMAT_LENGTH
   */
  public static final int TAG_JPEG_INTERCHANGE_FORMAT_LENGTH = BaselineTIFFTagSet.TAG_JPEG_INTERCHANGE_FORMAT_LENGTH;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_JPEG_RESTART_INTERVAL}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_JPEG_RESTART_INTERVAL
   */
  public static final int TAG_JPEG_RESTART_INTERVAL = BaselineTIFFTagSet.TAG_JPEG_RESTART_INTERVAL;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_JPEG_LOSSLESS_PREDICTORS}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_JPEG_LOSSLESS_PREDICTORS
   */
  public static final int TAG_JPEG_LOSSLESS_PREDICTORS = BaselineTIFFTagSet.TAG_JPEG_LOSSLESS_PREDICTORS;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_JPEG_POINT_TRANSFORMS}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_JPEG_POINT_TRANSFORMS
   */
  public static final int TAG_JPEG_POINT_TRANSFORMS = BaselineTIFFTagSet.TAG_JPEG_POINT_TRANSFORMS;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_JPEG_Q_TABLES}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_JPEG_Q_TABLES
   */
  public static final int TAG_JPEG_Q_TABLES = BaselineTIFFTagSet.TAG_JPEG_Q_TABLES;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_JPEG_DC_TABLES}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_JPEG_DC_TABLES
   */
  public static final int TAG_JPEG_DC_TABLES = BaselineTIFFTagSet.TAG_JPEG_DC_TABLES;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_JPEG_AC_TABLES}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_JPEG_AC_TABLES
   */
  public static final int TAG_JPEG_AC_TABLES = BaselineTIFFTagSet.TAG_JPEG_AC_TABLES;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_Y_CB_CR_COEFFICIENTS}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_Y_CB_CR_COEFFICIENTS
   */
  public static final int TAG_Y_CB_CR_COEFFICIENTS = BaselineTIFFTagSet.TAG_Y_CB_CR_COEFFICIENTS;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_Y_CB_CR_SUBSAMPLING}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_Y_CB_CR_SUBSAMPLING
   */
  public static final int TAG_Y_CB_CR_SUBSAMPLING = BaselineTIFFTagSet.TAG_Y_CB_CR_SUBSAMPLING;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_Y_CB_CR_POSITIONING}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_Y_CB_CR_POSITIONING
   */
  public static final int TAG_Y_CB_CR_POSITIONING = BaselineTIFFTagSet.TAG_Y_CB_CR_POSITIONING;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#Y_CB_CR_POSITIONING_CENTERED}.
   * @since 9
   * @see BaselineTIFFTagSet#Y_CB_CR_POSITIONING_CENTERED
   */
  public static final int Y_CB_CR_POSITIONING_CENTERED = BaselineTIFFTagSet.Y_CB_CR_POSITIONING_CENTERED;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#Y_CB_CR_POSITIONING_COSITED}.
   * @since 9
   * @see BaselineTIFFTagSet#Y_CB_CR_POSITIONING_COSITED
   */
  public static final int Y_CB_CR_POSITIONING_COSITED = BaselineTIFFTagSet.Y_CB_CR_POSITIONING_COSITED;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_REFERENCE_BLACK_WHITE}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_REFERENCE_BLACK_WHITE
   */
  public static final int TAG_REFERENCE_BLACK_WHITE = BaselineTIFFTagSet.TAG_REFERENCE_BLACK_WHITE;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_COPYRIGHT}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_COPYRIGHT
   */
  public static final int TAG_COPYRIGHT = BaselineTIFFTagSet.TAG_COPYRIGHT;

  /**
   * Example usage of the new field {@link BaselineTIFFTagSet#TAG_ICC_PROFILE}.
   * @since 9
   * @see BaselineTIFFTagSet#TAG_ICC_PROFILE
   */
  public static final int TAG_ICC_PROFILE = BaselineTIFFTagSet.TAG_ICC_PROFILE;

  /**
   * Example call to new method {@link BaselineTIFFTagSet#getInstance()}.
   * @since 9
   * @see BaselineTIFFTagSet#getInstance()
   */
  public static BaselineTIFFTagSet getInstance()
  {
    BaselineTIFFTagSet result = BaselineTIFFTagSet.getInstance();
    return result;
  }

}
