package whatisnewin.javax.imageio.plugins.tiff;

import javax.imageio.plugins.tiff.TIFFTagSet;
import java.util.List;
import javax.imageio.plugins.tiff.TIFFTag;
import java.util.SortedSet;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link TIFFTagSet}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link TIFFTagSet} is a completely new class.
 * @since 9
 * @see TIFFTagSet
 */
public final class WhatIsNewInTIFFTagSet
{
  /**
   * Example call to new constructor {@link TIFFTagSet#TIFFTagSet(List)}.
   * @since 9
   * @see TIFFTagSet#TIFFTagSet(List)
   */
  public WhatIsNewInTIFFTagSet(List<TIFFTag> tags)
  {
    TIFFTagSet testee = new TIFFTagSet(tags);
  }

  /**
   * Example call to new method {@link TIFFTagSet#getTagNames()}.
   * @since 9
   * @see TIFFTagSet#getTagNames()
   */
  public SortedSet<String> getTagNames()
  {
    TIFFTagSet testee = $$$();

    SortedSet<String> result = testee.getTagNames();
    return result;
  }

  /**
   * Example call to new method {@link TIFFTagSet#getTag(int)}.
   * @since 9
   * @see TIFFTagSet#getTag(int)
   */
  public TIFFTag getTag(int tagNumber)
  {
    TIFFTagSet testee = $$$();

    TIFFTag result = testee.getTag(tagNumber);
    return result;
  }

  /**
   * Example call to new method {@link TIFFTagSet#getTag(String)}.
   * @since 9
   * @see TIFFTagSet#getTag(String)
   */
  public TIFFTag getTag(String tagName)
  {
    TIFFTagSet testee = $$$();

    TIFFTag result = testee.getTag(tagName);
    return result;
  }

  /**
   * Example call to new method {@link TIFFTagSet#getTagNumbers()}.
   * @since 9
   * @see TIFFTagSet#getTagNumbers()
   */
  public SortedSet<Integer> getTagNumbers()
  {
    TIFFTagSet testee = $$$();

    SortedSet<Integer> result = testee.getTagNumbers();
    return result;
  }

  private TIFFTagSet $$$()
  {
    return null;
  }
}
