package whatisnewin.java.sql;

import java.sql.DatabaseMetaData;
import java.sql.SQLException;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link DatabaseMetaData}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link DatabaseMetaData} is an old class but has new fields, constructors or methods.
 * @since 1.1
 * @see DatabaseMetaData
 */
public final class WhatIsNewInDatabaseMetaData
{
  /**
   * Example call to new method {@link DatabaseMetaData#supportsSharding()}.
   * @since 9
   * @see DatabaseMetaData#supportsSharding()
   */
  public boolean supportsSharding() throws SQLException
  {
    DatabaseMetaData testee = $$$();

    boolean result = testee.supportsSharding();
    return result;
  }

  private DatabaseMetaData $$$()
  {
    return null;
  }
}
