package whatisnewin.java.awt.desktop;

import java.awt.desktop.OpenFilesEvent;
import java.util.List;
import java.io.File;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link OpenFilesEvent}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link OpenFilesEvent} is a completely new class
 * @since 9
 * @see OpenFilesEvent
 */
public final class WhatIsNewInOpenFilesEvent
{
  /**
   * Example call to new constructor {@link OpenFilesEvent#OpenFilesEvent}
   * @since 9
   * @see OpenFilesEvent#OpenFilesEvent
   */
  public WhatIsNewInOpenFilesEvent(List<File> files, String searchTerm)
  {
    OpenFilesEvent testee = new OpenFilesEvent(files, searchTerm);
  }

  /**
   * Example call to new method {@link OpenFilesEvent#getSearchTerm}
   * @since 9
   * @see OpenFilesEvent#getSearchTerm
   */
  public String getSearchTerm()
  {
    OpenFilesEvent testee = $$$();

    String result = testee.getSearchTerm();
    return result;
  }

  private OpenFilesEvent $$$()
  {
    return null;
  }
}
