package whatisnewin.java.awt.desktop;

import java.awt.desktop.AboutEvent;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link AboutEvent}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link AboutEvent} is a completely new class
 * @since 9
 * @see AboutEvent
 */
public final class WhatIsNewInAboutEvent
{
  /**
   * Example call to new constructor {@link AboutEvent#AboutEvent}
   * @since 9
   * @see AboutEvent#AboutEvent
   */
  public WhatIsNewInAboutEvent()
  {
    AboutEvent testee = new AboutEvent();
  }

}
