package whatisnewin.java.awt.desktop;

import java.awt.desktop.OpenURIHandler;
import java.awt.desktop.OpenURIEvent;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link OpenURIHandler}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link OpenURIHandler} is a completely new class.
 * @since 9
 * @see OpenURIHandler
 */
public final class WhatIsNewInOpenURIHandler
{
  /**
   * Example call to new method {@link OpenURIHandler#openURI(OpenURIEvent)}.
   * @since 9
   * @see OpenURIHandler#openURI(OpenURIEvent)
   */
  public void openURI(OpenURIEvent e)
  {
    OpenURIHandler testee = $$$();

    testee.openURI(e);
  }

  private OpenURIHandler $$$()
  {
    return null;
  }
}
