package whatisnewin.java.awt.desktop;

import java.awt.desktop.QuitStrategy;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link QuitStrategy}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link QuitStrategy} is a completely new class.
 * @since 9
 * @see QuitStrategy
 */
public final class WhatIsNewInQuitStrategy
{
  /**
   * Example usage of the new field {@link QuitStrategy#NORMAL_EXIT}.
   * @since 9
   * @see QuitStrategy#NORMAL_EXIT
   */
  public static final QuitStrategy NORMAL_EXIT = QuitStrategy.NORMAL_EXIT;

  /**
   * Example usage of the new field {@link QuitStrategy#CLOSE_ALL_WINDOWS}.
   * @since 9
   * @see QuitStrategy#CLOSE_ALL_WINDOWS
   */
  public static final QuitStrategy CLOSE_ALL_WINDOWS = QuitStrategy.CLOSE_ALL_WINDOWS;

  /**
   * Example call to new method {@link QuitStrategy#values()}.
   * @since 9
   * @see QuitStrategy#values()
   */
  public static QuitStrategy[] values()
  {
    QuitStrategy[] result = QuitStrategy.values();
    return result;
  }

  /**
   * Example call to new method {@link QuitStrategy#valueOf(String)}.
   * @since 9
   * @see QuitStrategy#valueOf(String)
   */
  public static QuitStrategy valueOf(String name)
  {
    QuitStrategy result = QuitStrategy.valueOf(name);
    return result;
  }

}
