package whatisnewin.java.awt.desktop;

import java.awt.desktop.AppHiddenEvent;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link AppHiddenEvent}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link AppHiddenEvent} is a completely new class.
 * @since 9
 * @see AppHiddenEvent
 */
public final class WhatIsNewInAppHiddenEvent
{
  /**
   * Example call to new constructor {@link AppHiddenEvent#AppHiddenEvent()}.
   * @since 9
   * @see AppHiddenEvent#AppHiddenEvent()
   */
  public WhatIsNewInAppHiddenEvent()
  {
    AppHiddenEvent testee = new AppHiddenEvent();
  }

}
