package whatisnewin.java.awt.desktop;

import java.awt.desktop.AppReopenedEvent;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link AppReopenedEvent}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link AppReopenedEvent} is a completely new class.
 * @since 9
 * @see AppReopenedEvent
 */
public final class WhatIsNewInAppReopenedEvent
{
  /**
   * Example call to new constructor {@link AppReopenedEvent#AppReopenedEvent()}.
   * @since 9
   * @see AppReopenedEvent#AppReopenedEvent()
   */
  public WhatIsNewInAppReopenedEvent()
  {
    AppReopenedEvent testee = new AppReopenedEvent();
  }

}
