package whatisnewin.java.awt.desktop;

import java.awt.desktop.ScreenSleepListener;
import java.awt.desktop.ScreenSleepEvent;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link ScreenSleepListener}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link ScreenSleepListener} is a completely new class
 * @since 9
 * @see ScreenSleepListener
 */
public final class WhatIsNewInScreenSleepListener
{
  /**
   * Example call to new method {@link ScreenSleepListener#screenAwoke}
   * @since 9
   * @see ScreenSleepListener#screenAwoke
   */
  public void screenAwoke(ScreenSleepEvent e)
  {
    ScreenSleepListener testee = $$$();

    testee.screenAwoke(e);
  }

  /**
   * Example call to new method {@link ScreenSleepListener#screenAboutToSleep}
   * @since 9
   * @see ScreenSleepListener#screenAboutToSleep
   */
  public void screenAboutToSleep(ScreenSleepEvent e)
  {
    ScreenSleepListener testee = $$$();

    testee.screenAboutToSleep(e);
  }

  private ScreenSleepListener $$$()
  {
    return null;
  }
}
