package whatisnewin.java.awt.desktop;

import java.awt.desktop.AboutHandler;
import java.awt.desktop.AboutEvent;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link AboutHandler}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link AboutHandler} is a completely new class.
 * @since 9
 * @see AboutHandler
 */
public final class WhatIsNewInAboutHandler
{
  /**
   * Example call to new method {@link AboutHandler#handleAbout(AboutEvent)}.
   * @since 9
   * @see AboutHandler#handleAbout(AboutEvent)
   */
  public void handleAbout(AboutEvent e)
  {
    AboutHandler testee = $$$();

    testee.handleAbout(e);
  }

  private AboutHandler $$$()
  {
    return null;
  }
}
