package whatisnewin.java.awt.desktop;

import java.awt.desktop.SystemSleepEvent;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link SystemSleepEvent}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link SystemSleepEvent} is a completely new class.
 * @since 9
 * @see SystemSleepEvent
 */
public final class WhatIsNewInSystemSleepEvent
{
  /**
   * Example call to new constructor {@link SystemSleepEvent#SystemSleepEvent()}.
   * @since 9
   * @see SystemSleepEvent#SystemSleepEvent()
   */
  public WhatIsNewInSystemSleepEvent()
  {
    SystemSleepEvent testee = new SystemSleepEvent();
  }

}
