package whatisnewin.java.awt.desktop;

import java.awt.desktop.OpenURIEvent;
import java.net.URI;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link OpenURIEvent}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link OpenURIEvent} is a completely new class
 * @since 9
 * @see OpenURIEvent
 */
public final class WhatIsNewInOpenURIEvent
{
  /**
   * Example call to new constructor {@link OpenURIEvent#OpenURIEvent}
   * @since 9
   * @see OpenURIEvent#OpenURIEvent
   */
  public WhatIsNewInOpenURIEvent(URI uri)
  {
    OpenURIEvent testee = new OpenURIEvent(uri);
  }

  /**
   * Example call to new method {@link OpenURIEvent#getURI}
   * @since 9
   * @see OpenURIEvent#getURI
   */
  public URI getURI()
  {
    OpenURIEvent testee = $$$();

    URI result = testee.getURI();
    return result;
  }

  private OpenURIEvent $$$()
  {
    return null;
  }
}
