package whatisnewin.java.awt.desktop;

import java.awt.desktop.PrintFilesHandler;
import java.awt.desktop.PrintFilesEvent;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link PrintFilesHandler}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link PrintFilesHandler} is a completely new class
 * @since 9
 * @see PrintFilesHandler
 */
public final class WhatIsNewInPrintFilesHandler
{
  /**
   * Example call to new method {@link PrintFilesHandler#printFiles}
   * @since 9
   * @see PrintFilesHandler#printFiles
   */
  public void printFiles(PrintFilesEvent e)
  {
    PrintFilesHandler testee = $$$();

    testee.printFiles(e);
  }

  private PrintFilesHandler $$$()
  {
    return null;
  }
}
