package whatisnewin.java.awt.desktop;

import java.awt.desktop.PrintFilesEvent;
import java.util.List;
import java.io.File;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link PrintFilesEvent}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link PrintFilesEvent} is a completely new class.
 * @since 9
 * @see PrintFilesEvent
 */
public final class WhatIsNewInPrintFilesEvent
{
  /**
   * Example call to new constructor {@link PrintFilesEvent#PrintFilesEvent(List)}.
   * @since 9
   * @see PrintFilesEvent#PrintFilesEvent(List)
   */
  public WhatIsNewInPrintFilesEvent(List<File> files)
  {
    PrintFilesEvent testee = new PrintFilesEvent(files);
  }

}
