package whatisnewin.jdk.javadoc.doclet;

import jdk.javadoc.doclet.DocletEnvironment.ModuleMode;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link ModuleMode}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link ModuleMode} is a completely new class.
 * @since 9
 * @see ModuleMode
 */
public final class WhatIsNewInDocletEnvironment$ModuleMode
{
  /**
   * Example usage of the new field {@link ModuleMode#API}.
   * @since 9
   * @see ModuleMode#API
   */
  public static final ModuleMode API = ModuleMode.API;

  /**
   * Example usage of the new field {@link ModuleMode#ALL}.
   * @since 9
   * @see ModuleMode#ALL
   */
  public static final ModuleMode ALL = ModuleMode.ALL;

  /**
   * Example call to new method {@link ModuleMode#values()}.
   * @since 9
   * @see ModuleMode#values()
   */
  public static ModuleMode[] values()
  {
    ModuleMode[] result = ModuleMode.values();
    return result;
  }

  /**
   * Example call to new method {@link ModuleMode#valueOf(String)}.
   * @since 9
   * @see ModuleMode#valueOf(String)
   */
  public static ModuleMode valueOf(String name)
  {
    ModuleMode result = ModuleMode.valueOf(name);
    return result;
  }

}
