package whatisnewin.jdk.javadoc.doclet;

import jdk.javadoc.doclet.Doclet;
import java.util.Locale;
import jdk.javadoc.doclet.Reporter;
import java.util.Set;
import jdk.javadoc.doclet.Doclet.Option;
import javax.lang.model.SourceVersion;
import jdk.javadoc.doclet.DocletEnvironment;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link Doclet}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link Doclet} is a completely new class.
 * @since 9
 * @see Doclet
 */
public final class WhatIsNewInDoclet
{
  /**
   * Example call to new method {@link Doclet#init(Locale, Reporter)}.
   * @since 9
   * @see Doclet#init(Locale, Reporter)
   */
  public void init(Locale locale, Reporter reporter)
  {
    Doclet testee = $$$();

    testee.init(locale, reporter);
  }

  /**
   * Example call to new method {@link Doclet#getName()}.
   * @since 9
   * @see Doclet#getName()
   */
  public String getName()
  {
    Doclet testee = $$$();

    String result = testee.getName();
    return result;
  }

  /**
   * Example call to new method {@link Doclet#getSupportedOptions()}.
   * @since 9
   * @see Doclet#getSupportedOptions()
   */
  public Set<? extends Option> getSupportedOptions()
  {
    Doclet testee = $$$();

    Set<? extends Option> result = testee.getSupportedOptions();
    return result;
  }

  /**
   * Example call to new method {@link Doclet#getSupportedSourceVersion()}.
   * @since 9
   * @see Doclet#getSupportedSourceVersion()
   */
  public SourceVersion getSupportedSourceVersion()
  {
    Doclet testee = $$$();

    SourceVersion result = testee.getSupportedSourceVersion();
    return result;
  }

  /**
   * Example call to new method {@link Doclet#run(DocletEnvironment)}.
   * @since 9
   * @see Doclet#run(DocletEnvironment)
   */
  public boolean run(DocletEnvironment environment)
  {
    Doclet testee = $$$();

    boolean result = testee.run(environment);
    return result;
  }

  private Doclet $$$()
  {
    return null;
  }
}
