package whatisnewin.com.sun.management;

import com.sun.management.VMOption.Origin;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link Origin}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link Origin} is an old class but has new fields, constructors or methods
 * @since 1.6
 * @see Origin
 */
public final class WhatIsNewInVMOption$Origin
{
  /**
   * Example usage of the new field {@link Origin#ATTACH_ON_DEMAND}
   * @since 9
   * @see Origin#ATTACH_ON_DEMAND
   */
  public static  final Origin ATTACH_ON_DEMAND = Origin.ATTACH_ON_DEMAND;

}
