package whatisnewin.jdk.jshell.spi;

import jdk.jshell.spi.ExecutionControl.ResolutionException;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link ResolutionException}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link ResolutionException} is a completely new class.
 * @since 9
 * @see ResolutionException
 */
public final class WhatIsNewInExecutionControl$ResolutionException
{
  /**
   * Example call to new constructor {@link ResolutionException#ResolutionException(int, StackTraceElement[])}.
   * @since 9
   * @see ResolutionException#ResolutionException(int, StackTraceElement[])
   */
  public WhatIsNewInExecutionControl$ResolutionException(int id, StackTraceElement[] stackElements)
  {
    ResolutionException testee = new ResolutionException(id, stackElements);
  }

  /**
   * Example call to new method {@link ResolutionException#id()}.
   * @since 9
   * @see ResolutionException#id()
   */
  public int id()
  {
    ResolutionException testee = $$$();

    int result = testee.id();
    return result;
  }

  private ResolutionException $$$()
  {
    return null;
  }
}
