package whatisnewin.java.time;

import java.time.OffsetTime;
import java.time.LocalDate;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link OffsetTime}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link OffsetTime} is an old class but has new fields, constructors or methods.
 * @since 1.8
 * @see OffsetTime
 */
public final class WhatIsNewInOffsetTime
{
  /**
   * Example call to new method {@link OffsetTime#toEpochSecond(LocalDate)}.
   * @since 9
   * @see OffsetTime#toEpochSecond(LocalDate)
   */
  public long toEpochSecond(LocalDate date)
  {
    OffsetTime testee = $$$();

    long result = testee.toEpochSecond(date);
    return result;
  }

  private OffsetTime $$$()
  {
    return null;
  }
}
