package whatisnewin.com.sun.source.doctree;

import com.sun.source.doctree.DocTypeTree;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link DocTypeTree}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link DocTypeTree} is a completely new class
 * @since 10
 * @see DocTypeTree
 */
public final class WhatIsNewInDocTypeTree
{
  /**
   * Example call to new method {@link DocTypeTree#getText}
   * @since 10
   * @see DocTypeTree#getText
   */
  public String getText()
  {
    DocTypeTree testee = $$$();

    String result = testee.getText();
    return result;
  }

  private DocTypeTree $$$()
  {
    return null;
  }
}
