package whatisnewin.com.sun.source.doctree;

import com.sun.source.doctree.IndexTree;
import com.sun.source.doctree.DocTree;
import java.util.List;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link IndexTree}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link IndexTree} is a completely new class
 * @since 9
 * @see IndexTree
 */
public final class WhatIsNewInIndexTree
{
  /**
   * Example call to new method {@link IndexTree#getSearchTerm}
   * @since 9
   * @see IndexTree#getSearchTerm
   */
  public DocTree getSearchTerm()
  {
    IndexTree testee = $$$();

    DocTree result = testee.getSearchTerm();
    return result;
  }

  /**
   * Example call to new method {@link IndexTree#getDescription}
   * @since 9
   * @see IndexTree#getDescription
   */
  public List<? extends DocTree> getDescription()
  {
    IndexTree testee = $$$();

    List<? extends DocTree> result = testee.getDescription();
    return result;
  }

  private IndexTree $$$()
  {
    return null;
  }
}
