package whatisnewin.javax.xml.datatype;

import javax.xml.datatype.DatatypeFactory;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link DatatypeFactory}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link DatatypeFactory} is an old class but has new fields, constructors or methods
 * @since 1.5
 * @see DatatypeFactory
 */
public final class WhatIsNewInDatatypeFactory
{
  /**
   * Example call to new method {@link DatatypeFactory#newDefaultInstance}
   * @since 9
   * @see DatatypeFactory#newDefaultInstance
   */
  public static DatatypeFactory newDefaultInstance()
  {
    DatatypeFactory result = DatatypeFactory.newDefaultInstance();
    return result;
  }

}
