package whatisnewin.javax.sql;

import javax.sql.CommonDataSource;
import java.sql.ShardingKeyBuilder;
import java.sql.SQLException;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link CommonDataSource}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link CommonDataSource} is an old class but has new fields, constructors or methods.
 * @since 1.6
 * @see CommonDataSource
 */
public final class WhatIsNewInCommonDataSource
{
  /**
   * Example call to new method {@link CommonDataSource#createShardingKeyBuilder()}.
   * @since 9
   * @see CommonDataSource#createShardingKeyBuilder()
   */
  public ShardingKeyBuilder createShardingKeyBuilder() throws SQLException
  {
    CommonDataSource testee = $$$();

    ShardingKeyBuilder result = testee.createShardingKeyBuilder();
    return result;
  }

  private CommonDataSource $$$()
  {
    return null;
  }
}
