package whatisnewin.javax.sql;

import javax.sql.XADataSource;
import javax.sql.XAConnectionBuilder;
import java.sql.SQLException;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link XADataSource}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link XADataSource} is an old class but has new fields, constructors or methods.
 * @since 1.4
 * @see XADataSource
 */
public final class WhatIsNewInXADataSource
{
  /**
   * Example call to new method {@link XADataSource#createXAConnectionBuilder()}.
   * @since 9
   * @see XADataSource#createXAConnectionBuilder()
   */
  public XAConnectionBuilder createXAConnectionBuilder() throws SQLException
  {
    XADataSource testee = $$$();

    XAConnectionBuilder result = testee.createXAConnectionBuilder();
    return result;
  }

  private XADataSource $$$()
  {
    return null;
  }
}
