package whatisnewin.javax.xml;

import javax.xml.XMLConstants;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link XMLConstants}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link XMLConstants} is an old class but has new fields, constructors or methods.
 * @since 1.5
 * @see XMLConstants
 */
public final class WhatIsNewInXMLConstants
{
  /**
   * Example usage of the new field {@link XMLConstants#USE_CATALOG}.
   * @since 9
   * @see XMLConstants#USE_CATALOG
   */
  public static final String USE_CATALOG = XMLConstants.USE_CATALOG;

}
