package whatisnewin.java.lang.invoke;

import java.lang.invoke.MethodType;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link MethodType}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link MethodType} is an old class but has new fields, constructors or methods
 * @since 1.7
 * @see MethodType
 */
public final class WhatIsNewInMethodType
{
  /**
   * Example call to new method {@link MethodType#lastParameterType}
   * @since 10
   * @see MethodType#lastParameterType
   */
  public Class<?> lastParameterType()
  {
    MethodType testee = $$$();

    Class<?> result = testee.lastParameterType();
    return result;
  }

  private MethodType $$$()
  {
    return null;
  }
}
