package whatisnewin.java.lang.invoke;

import java.lang.invoke.StringConcatException;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link StringConcatException}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link StringConcatException} is a completely new class
 * @since 9
 * @see StringConcatException
 */
public final class WhatIsNewInStringConcatException
{
  /**
   * Example call to new constructor {@link StringConcatException#StringConcatException}
   * @since 9
   * @see StringConcatException#StringConcatException
   */
  public WhatIsNewInStringConcatException(String msg)
  {
    StringConcatException testee = new StringConcatException(msg);
  }

  /**
   * Example call to new constructor {@link StringConcatException#StringConcatException}
   * @since 9
   * @see StringConcatException#StringConcatException
   */
  public WhatIsNewInStringConcatException(String msg, Throwable cause)
  {
    StringConcatException testee = new StringConcatException(msg, cause);
  }

}
