package whatisnewin.javax.xml.stream;

import javax.xml.stream.XMLInputFactory;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link XMLInputFactory}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link XMLInputFactory} is an old class but has new fields, constructors or methods.
 * @since 1.6
 * @see XMLInputFactory
 */
public final class WhatIsNewInXMLInputFactory
{
  /**
   * Example call to new method {@link XMLInputFactory#newDefaultFactory()}.
   * @since 9
   * @see XMLInputFactory#newDefaultFactory()
   */
  public static XMLInputFactory newDefaultFactory()
  {
    XMLInputFactory result = XMLInputFactory.newDefaultFactory();
    return result;
  }

}
