package whatisnewin.javax.xml.transform;

import javax.xml.transform.TransformerFactory;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link TransformerFactory}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link TransformerFactory} is an old class but has new fields, constructors or methods.
 * @since 1.5
 * @see TransformerFactory
 */
public final class WhatIsNewInTransformerFactory
{
  /**
   * Example call to new method {@link TransformerFactory#newDefaultInstance()}.
   * @since 9
   * @see TransformerFactory#newDefaultInstance()
   */
  public static TransformerFactory newDefaultInstance()
  {
    TransformerFactory result = TransformerFactory.newDefaultInstance();
    return result;
  }

}
