package whatisnewin.jdk.jshell.execution;

import jdk.jshell.execution.JdiExecutionControl;
import jdk.jshell.spi.ExecutionControl.ClassBytecodes;
import jdk.jshell.spi.ExecutionControl.ClassInstallException;
import jdk.jshell.spi.ExecutionControl.EngineTerminationException;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link JdiExecutionControl}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link JdiExecutionControl} is a completely new class.
 * @since 9
 * @see JdiExecutionControl
 */
public final class WhatIsNewInJdiExecutionControl
{
  /**
   * Example call to new method {@link JdiExecutionControl#redefine(jdk.jshell.spi.ExecutionControl.ClassBytecodes[])}.
   * @since 9
   * @see JdiExecutionControl#redefine(jdk.jshell.spi.ExecutionControl.ClassBytecodes[])
   */
  public void redefine(ClassBytecodes[] cbcs) throws ClassInstallException, EngineTerminationException
  {
    JdiExecutionControl testee = $$$();

    testee.redefine(cbcs);
  }

  private JdiExecutionControl $$$()
  {
    return null;
  }
}
