package whatisnewin.jdk.jshell.execution;

import jdk.jshell.execution.LocalExecutionControl;
import jdk.jshell.execution.LoaderDelegate;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link LocalExecutionControl}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link LocalExecutionControl} is a completely new class
 * @since 9
 * @see LocalExecutionControl
 */
public final class WhatIsNewInLocalExecutionControl
{
  /**
   * Example call to new constructor {@link LocalExecutionControl#LocalExecutionControl}
   * @since 9
   * @see LocalExecutionControl#LocalExecutionControl
   */
  public WhatIsNewInLocalExecutionControl(LoaderDelegate loaderDelegate)
  {
    LocalExecutionControl testee = new LocalExecutionControl(loaderDelegate);
  }

  /**
   * Example call to new constructor {@link LocalExecutionControl#LocalExecutionControl}
   * @since 9
   * @see LocalExecutionControl#LocalExecutionControl
   */
  public WhatIsNewInLocalExecutionControl()
  {
    LocalExecutionControl testee = new LocalExecutionControl();
  }

}
