package whatisnewin.jdk.jshell.execution;

import jdk.jshell.execution.JdiExecutionControlProvider;
import java.util.Map;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link JdiExecutionControlProvider}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link JdiExecutionControlProvider} is a completely new class
 * @since 9
 * @see JdiExecutionControlProvider
 */
public final class WhatIsNewInJdiExecutionControlProvider
{
  /**
   * Example usage of the new field {@link JdiExecutionControlProvider#PARAM_REMOTE_AGENT}
   * @since 9
   * @see JdiExecutionControlProvider#PARAM_REMOTE_AGENT
   */
  public static  final String PARAM_REMOTE_AGENT = JdiExecutionControlProvider.PARAM_REMOTE_AGENT;

  /**
   * Example usage of the new field {@link JdiExecutionControlProvider#PARAM_TIMEOUT}
   * @since 9
   * @see JdiExecutionControlProvider#PARAM_TIMEOUT
   */
  public static  final String PARAM_TIMEOUT = JdiExecutionControlProvider.PARAM_TIMEOUT;

  /**
   * Example usage of the new field {@link JdiExecutionControlProvider#PARAM_HOST_NAME}
   * @since 9
   * @see JdiExecutionControlProvider#PARAM_HOST_NAME
   */
  public static  final String PARAM_HOST_NAME = JdiExecutionControlProvider.PARAM_HOST_NAME;

  /**
   * Example usage of the new field {@link JdiExecutionControlProvider#PARAM_LAUNCH}
   * @since 9
   * @see JdiExecutionControlProvider#PARAM_LAUNCH
   */
  public static  final String PARAM_LAUNCH = JdiExecutionControlProvider.PARAM_LAUNCH;

  /**
   * Example call to new constructor {@link JdiExecutionControlProvider#JdiExecutionControlProvider}
   * @since 9
   * @see JdiExecutionControlProvider#JdiExecutionControlProvider
   */
  public WhatIsNewInJdiExecutionControlProvider()
  {
    JdiExecutionControlProvider testee = new JdiExecutionControlProvider();
  }

  /**
   * Example call to new method {@link JdiExecutionControlProvider#name}
   * @since 9
   * @see JdiExecutionControlProvider#name
   */
  public String name()
  {
    JdiExecutionControlProvider testee = $$$();

    String result = testee.name();
    return result;
  }

  /**
   * Example call to new method {@link JdiExecutionControlProvider#defaultParameters}
   * @since 9
   * @see JdiExecutionControlProvider#defaultParameters
   */
  public Map<String, String> defaultParameters()
  {
    JdiExecutionControlProvider testee = $$$();

    Map<String, String> result = testee.defaultParameters();
    return result;
  }

  private JdiExecutionControlProvider $$$()
  {
    return null;
  }
}
