package whatisnewin.java.net;

import java.net.URLEncoder;
import java.nio.charset.Charset;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link URLEncoder}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link URLEncoder} is an old class but has new fields, constructors or methods.
 * @since 1.0
 * @see URLEncoder
 */
public final class WhatIsNewInURLEncoder
{
  /**
   * Example call to new method {@link URLEncoder#encode(String, Charset)}.
   * @since 10
   * @see URLEncoder#encode(String, Charset)
   */
  public static String encode(String s, Charset charset)
  {
    String result = URLEncoder.encode(s, charset);
    return result;
  }

}
