package whatisnewin.java.net;

import java.net.SocketImpl;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link SocketImpl}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link SocketImpl} is an old class but has new fields, constructors or methods.
 * @since 1.0
 * @see SocketImpl
 */
public final class WhatIsNewInSocketImpl
{
}
