package whatisnewin.java.net;

import java.net.URLDecoder;
import java.nio.charset.Charset;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link URLDecoder}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link URLDecoder} is an old class but has new fields, constructors or methods.
 * @since 1.2
 * @see URLDecoder
 */
public final class WhatIsNewInURLDecoder
{
  /**
   * Example call to new method {@link URLDecoder#decode(String, Charset)}.
   * @since 10
   * @see URLDecoder#decode(String, Charset)
   */
  public static String decode(String s, Charset charset)
  {
    String result = URLDecoder.decode(s, charset);
    return result;
  }

}
