package whatisnewin.java.net;

import java.net.HttpURLConnection;
import java.net.Authenticator;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link HttpURLConnection}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link HttpURLConnection} is an old class but has new fields, constructors or methods.
 * @since 1.1
 * @see HttpURLConnection
 */
public final class WhatIsNewInHttpURLConnection
{
  /**
   * Example call to new method {@link HttpURLConnection#setAuthenticator(Authenticator)}.
   * @since 9
   * @see HttpURLConnection#setAuthenticator(Authenticator)
   */
  public void setAuthenticator(Authenticator auth)
  {
    HttpURLConnection testee = $$$();

    testee.setAuthenticator(auth);
  }

  private HttpURLConnection $$$()
  {
    return null;
  }
}
