package whatisnewin.java.net;

import java.net.StandardSocketOptions;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link StandardSocketOptions}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link StandardSocketOptions} is an old class but has new fields, constructors or methods.
 * @since 1.7
 * @see StandardSocketOptions
 */
public final class WhatIsNewInStandardSocketOptions
{
  /**
   * Example usage of the new field {@link StandardSocketOptions#SO_REUSEPORT}.
   * @since 9
   * @see StandardSocketOptions#SO_REUSEPORT
   */
  public static final java.net.SocketOption<Boolean> SO_REUSEPORT = StandardSocketOptions.SO_REUSEPORT;

}
