package whatisnewin.java.lang;


/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link Long}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link Long} is an old class but has new fields, constructors or methods.
 * @since 1.0
 * @see Long
 */
public final class WhatIsNewInLong
{
  /**
   * Example call to new method {@link Long#parseUnsignedLong(CharSequence, int, int, int)}.
   * @since 9
   * @see Long#parseUnsignedLong(CharSequence, int, int, int)
   */
  public static long parseUnsignedLong(CharSequence s, int beginIndex, int endIndex, int radix) throws NumberFormatException
  {
    long result = Long.parseUnsignedLong(s, beginIndex, endIndex, radix);
    return result;
  }

  /**
   * Example call to new method {@link Long#parseLong(CharSequence, int, int, int)}.
   * @since 9
   * @see Long#parseLong(CharSequence, int, int, int)
   */
  public static long parseLong(CharSequence s, int beginIndex, int endIndex, int radix) throws NumberFormatException
  {
    long result = Long.parseLong(s, beginIndex, endIndex, radix);
    return result;
  }

}
