package whatisnewin.java.lang;


/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link Short}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link Short} is an old class but has new fields, constructors or methods
 * @since 1.1
 * @see Short
 */
public final class WhatIsNewInShort
{
  /**
   * Example call to new method {@link Short#compareUnsigned}
   * @since 9
   * @see Short#compareUnsigned
   */
  public static int compareUnsigned(short x, short y)
  {
    int result = Short.compareUnsigned(x, y);
    return result;
  }

}
