package whatisnewin.java.lang;

import java.lang.Runtime.Version;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link Runtime}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link Runtime} is an old class but has new fields, constructors or methods.
 * @since 1.0
 * @see Runtime
 */
public final class WhatIsNewInRuntime
{
  /**
   * Example call to new method {@link Runtime#version()}.
   * @since 9
   * @see Runtime#version()
   */
  public static Version version()
  {
    Version result = Runtime.version();
    return result;
  }

}
