package whatisnewin.java.lang;


/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link Math}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link Math} is an old class but has new fields, constructors or methods
 * @since 1.0
 * @see Math
 */
public final class WhatIsNewInMath
{
  /**
   * Example call to new method {@link Math#fma}
   * @since 9
   * @see Math#fma
   */
  public static double fma(double a, double b, double c)
  {
    double result = Math.fma(a, b, c);
    return result;
  }

  /**
   * Example call to new method {@link Math#fma}
   * @since 9
   * @see Math#fma
   */
  public static float fma(float a, float b, float c)
  {
    float result = Math.fma(a, b, c);
    return result;
  }

  /**
   * Example call to new method {@link Math#multiplyExact}
   * @since 9
   * @see Math#multiplyExact
   */
  public static long multiplyExact(long x, int y)
  {
    long result = Math.multiplyExact(x, y);
    return result;
  }

  /**
   * Example call to new method {@link Math#multiplyFull}
   * @since 9
   * @see Math#multiplyFull
   */
  public static long multiplyFull(int x, int y)
  {
    long result = Math.multiplyFull(x, y);
    return result;
  }

  /**
   * Example call to new method {@link Math#multiplyHigh}
   * @since 9
   * @see Math#multiplyHigh
   */
  public static long multiplyHigh(long x, long y)
  {
    long result = Math.multiplyHigh(x, y);
    return result;
  }

  /**
   * Example call to new method {@link Math#floorMod}
   * @since 9
   * @see Math#floorMod
   */
  public static int floorMod(long x, int y)
  {
    int result = Math.floorMod(x, y);
    return result;
  }

  /**
   * Example call to new method {@link Math#floorDiv}
   * @since 9
   * @see Math#floorDiv
   */
  public static long floorDiv(long x, int y)
  {
    long result = Math.floorDiv(x, y);
    return result;
  }

}
