package whatisnewin.java.lang;


/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link Byte}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link Byte} is an old class but has new fields, constructors or methods
 * @since 1.1
 * @see Byte
 */
public final class WhatIsNewInByte
{
  /**
   * Example call to new method {@link Byte#compareUnsigned}
   * @since 9
   * @see Byte#compareUnsigned
   */
  public static int compareUnsigned(byte x, byte y)
  {
    int result = Byte.compareUnsigned(x, y);
    return result;
  }

}
