package whatisnewin.java.lang;


/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link Thread}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link Thread} is an old class but has new fields, constructors or methods
 * @since 1.0
 * @see Thread
 */
public final class WhatIsNewInThread
{
  /**
   * Example call to new constructor {@link Thread#Thread}
   * @since 9
   * @see Thread#Thread
   */
  public WhatIsNewInThread(ThreadGroup group, Runnable target, String name, long stackSize, boolean inheritThreadLocals)
  {
    Thread testee = new Thread(group, target, name, stackSize, inheritThreadLocals);
  }

  /**
   * Example call to new method {@link Thread#onSpinWait}
   * @since 9
   * @see Thread#onSpinWait
   */
  public static void onSpinWait()
  {
    Thread.onSpinWait();
  }

}
