package whatisnewin.java.lang;

import java.lang.System.Logger;
import java.util.ResourceBundle;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link System}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link System} is an old class but has new fields, constructors or methods.
 * @since 1.0
 * @see System
 */
public final class WhatIsNewInSystem
{
  /**
   * Example call to new method {@link System#getLogger(String)}.
   * @since 9
   * @see System#getLogger(String)
   */
  public static Logger getLogger(String name)
  {
    Logger result = System.getLogger(name);
    return result;
  }

  /**
   * Example call to new method {@link System#getLogger(String, ResourceBundle)}.
   * @since 9
   * @see System#getLogger(String, ResourceBundle)
   */
  public static Logger getLogger(String name, ResourceBundle bundle)
  {
    Logger result = System.getLogger(name, bundle);
    return result;
  }

}
