package whatisnewin.java.lang;


/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link StrictMath}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link StrictMath} is an old class but has new fields, constructors or methods.
 * @since 1.3
 * @see StrictMath
 */
public final class WhatIsNewInStrictMath
{
  /**
   * Example call to new method {@link StrictMath#fma(double, double, double)}.
   * @since 9
   * @see StrictMath#fma(double, double, double)
   */
  public static double fma(double a, double b, double c)
  {
    double result = StrictMath.fma(a, b, c);
    return result;
  }

  /**
   * Example call to new method {@link StrictMath#fma(float, float, float)}.
   * @since 9
   * @see StrictMath#fma(float, float, float)
   */
  public static float fma(float a, float b, float c)
  {
    float result = StrictMath.fma(a, b, c);
    return result;
  }

  /**
   * Example call to new method {@link StrictMath#multiplyExact(long, int)}.
   * @since 9
   * @see StrictMath#multiplyExact(long, int)
   */
  public static long multiplyExact(long x, int y)
  {
    long result = StrictMath.multiplyExact(x, y);
    return result;
  }

  /**
   * Example call to new method {@link StrictMath#multiplyHigh(long, long)}.
   * @since 9
   * @see StrictMath#multiplyHigh(long, long)
   */
  public static long multiplyHigh(long x, long y)
  {
    long result = StrictMath.multiplyHigh(x, y);
    return result;
  }

  /**
   * Example call to new method {@link StrictMath#floorMod(long, int)}.
   * @since 9
   * @see StrictMath#floorMod(long, int)
   */
  public static int floorMod(long x, int y)
  {
    int result = StrictMath.floorMod(x, y);
    return result;
  }

  /**
   * Example call to new method {@link StrictMath#floorDiv(long, int)}.
   * @since 9
   * @see StrictMath#floorDiv(long, int)
   */
  public static long floorDiv(long x, int y)
  {
    long result = StrictMath.floorDiv(x, y);
    return result;
  }

  /**
   * Example call to new method {@link StrictMath#multiplyFull(int, int)}.
   * @since 9
   * @see StrictMath#multiplyFull(int, int)
   */
  public static long multiplyFull(int x, int y)
  {
    long result = StrictMath.multiplyFull(x, y);
    return result;
  }

}
