package whatisnewin.java.lang;

import java.lang.ModuleLayer.Controller;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link Controller}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link Controller} is a completely new class.
 * @since 9
 * @see Controller
 */
public final class WhatIsNewInModuleLayer$Controller
{
  /**
   * Example call to new method {@link Controller#addExports(Module, String, Module)}.
   * @since 9
   * @see Controller#addExports(Module, String, Module)
   */
  public Controller addExports(Module source, String pn, Module target)
  {
    Controller testee = $$$();

    Controller result = testee.addExports(source, pn, target);
    return result;
  }

  /**
   * Example call to new method {@link Controller#addOpens(Module, String, Module)}.
   * @since 9
   * @see Controller#addOpens(Module, String, Module)
   */
  public Controller addOpens(Module source, String pn, Module target)
  {
    Controller testee = $$$();

    Controller result = testee.addOpens(source, pn, target);
    return result;
  }

  /**
   * Example call to new method {@link Controller#addReads(Module, Module)}.
   * @since 9
   * @see Controller#addReads(Module, Module)
   */
  public Controller addReads(Module source, Module target)
  {
    Controller testee = $$$();

    Controller result = testee.addReads(source, target);
    return result;
  }

  /**
   * Example call to new method {@link Controller#layer()}.
   * @since 9
   * @see Controller#layer()
   */
  public ModuleLayer layer()
  {
    Controller testee = $$$();

    ModuleLayer result = testee.layer();
    return result;
  }

  private Controller $$$()
  {
    return null;
  }
}
