package whatisnewin.java.nio;

import java.nio.Buffer;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link Buffer}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link Buffer} is an old class but has new fields, constructors or methods.
 * @since 1.4
 * @see Buffer
 */
public final class WhatIsNewInBuffer
{
  /**
   * Example call to new method {@link Buffer#slice()}.
   * @since 9
   * @see Buffer#slice()
   */
  public Buffer slice()
  {
    Buffer testee = $$$();

    Buffer result = testee.slice();
    return result;
  }

  /**
   * Example call to new method {@link Buffer#duplicate()}.
   * @since 9
   * @see Buffer#duplicate()
   */
  public Buffer duplicate()
  {
    Buffer testee = $$$();

    Buffer result = testee.duplicate();
    return result;
  }

  private Buffer $$$()
  {
    return null;
  }
}
