package whatisnewin.javax.lang.model.element;

import javax.lang.model.element.ModuleElement.UsesDirective;
import javax.lang.model.element.TypeElement;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link UsesDirective}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link UsesDirective} is a completely new class
 * @since 9
 * @see UsesDirective
 */
public final class WhatIsNewInModuleElement$UsesDirective
{
  /**
   * Example call to new method {@link UsesDirective#getService}
   * @since 9
   * @see UsesDirective#getService
   */
  public TypeElement getService()
  {
    UsesDirective testee = $$$();

    TypeElement result = testee.getService();
    return result;
  }

  private UsesDirective $$$()
  {
    return null;
  }
}
