package whatisnewin.jdk.management.jfr;

import jdk.management.jfr.SettingDescriptorInfo;
import javax.management.openmbean.CompositeData;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link SettingDescriptorInfo}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link SettingDescriptorInfo} is a completely new class.
 * @since 9
 * @see SettingDescriptorInfo
 */
public final class WhatIsNewInSettingDescriptorInfo
{
  /**
   * Example call to new method {@link SettingDescriptorInfo#getLabel()}.
   * @since 9
   * @see SettingDescriptorInfo#getLabel()
   */
  public String getLabel()
  {
    SettingDescriptorInfo testee = $$$();

    String result = testee.getLabel();
    return result;
  }

  /**
   * Example call to new method {@link SettingDescriptorInfo#getName()}.
   * @since 9
   * @see SettingDescriptorInfo#getName()
   */
  public String getName()
  {
    SettingDescriptorInfo testee = $$$();

    String result = testee.getName();
    return result;
  }

  /**
   * Example call to new method {@link SettingDescriptorInfo#getDescription()}.
   * @since 9
   * @see SettingDescriptorInfo#getDescription()
   */
  public String getDescription()
  {
    SettingDescriptorInfo testee = $$$();

    String result = testee.getDescription();
    return result;
  }

  /**
   * Example call to new method {@link SettingDescriptorInfo#getTypeName()}.
   * @since 9
   * @see SettingDescriptorInfo#getTypeName()
   */
  public String getTypeName()
  {
    SettingDescriptorInfo testee = $$$();

    String result = testee.getTypeName();
    return result;
  }

  /**
   * Example call to new method {@link SettingDescriptorInfo#getContentType()}.
   * @since 9
   * @see SettingDescriptorInfo#getContentType()
   */
  public String getContentType()
  {
    SettingDescriptorInfo testee = $$$();

    String result = testee.getContentType();
    return result;
  }

  /**
   * Example call to new method {@link SettingDescriptorInfo#getDefaultValue()}.
   * @since 9
   * @see SettingDescriptorInfo#getDefaultValue()
   */
  public String getDefaultValue()
  {
    SettingDescriptorInfo testee = $$$();

    String result = testee.getDefaultValue();
    return result;
  }

  /**
   * Example call to new method {@link SettingDescriptorInfo#from(CompositeData)}.
   * @since 9
   * @see SettingDescriptorInfo#from(CompositeData)
   */
  public static SettingDescriptorInfo from(CompositeData cd)
  {
    SettingDescriptorInfo result = SettingDescriptorInfo.from(cd);
    return result;
  }

  private SettingDescriptorInfo $$$()
  {
    return null;
  }
}
