package whatisnewin.jdk.jfr.consumer;

import jdk.jfr.consumer.RecordedFrame;
import jdk.jfr.consumer.RecordedMethod;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link RecordedFrame}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link RecordedFrame} is a completely new class
 * @since 9
 * @see RecordedFrame
 */
public final class WhatIsNewInRecordedFrame
{
  /**
   * Example call to new method {@link RecordedFrame#getLineNumber}
   * @since 9
   * @see RecordedFrame#getLineNumber
   */
  public int getLineNumber()
  {
    RecordedFrame testee = $$$();

    int result = testee.getLineNumber();
    return result;
  }

  /**
   * Example call to new method {@link RecordedFrame#isJavaFrame}
   * @since 9
   * @see RecordedFrame#isJavaFrame
   */
  public boolean isJavaFrame()
  {
    RecordedFrame testee = $$$();

    boolean result = testee.isJavaFrame();
    return result;
  }

  /**
   * Example call to new method {@link RecordedFrame#getBytecodeIndex}
   * @since 9
   * @see RecordedFrame#getBytecodeIndex
   */
  public int getBytecodeIndex()
  {
    RecordedFrame testee = $$$();

    int result = testee.getBytecodeIndex();
    return result;
  }

  /**
   * Example call to new method {@link RecordedFrame#getMethod}
   * @since 9
   * @see RecordedFrame#getMethod
   */
  public RecordedMethod getMethod()
  {
    RecordedFrame testee = $$$();

    RecordedMethod result = testee.getMethod();
    return result;
  }

  /**
   * Example call to new method {@link RecordedFrame#getType}
   * @since 9
   * @see RecordedFrame#getType
   */
  public String getType()
  {
    RecordedFrame testee = $$$();

    String result = testee.getType();
    return result;
  }

  private RecordedFrame $$$()
  {
    return null;
  }
}
