package whatisnewin.jdk.jfr.consumer;

import jdk.jfr.consumer.RecordedEvent;
import java.time.Instant;
import jdk.jfr.EventType;
import java.util.List;
import jdk.jfr.ValueDescriptor;
import jdk.jfr.consumer.RecordedStackTrace;
import java.time.Duration;
import jdk.jfr.consumer.RecordedThread;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link RecordedEvent}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link RecordedEvent} is a completely new class.
 * @since 9
 * @see RecordedEvent
 */
public final class WhatIsNewInRecordedEvent
{
  /**
   * Example call to new method {@link RecordedEvent#getEndTime()}.
   * @since 9
   * @see RecordedEvent#getEndTime()
   */
  public Instant getEndTime()
  {
    RecordedEvent testee = $$$();

    Instant result = testee.getEndTime();
    return result;
  }

  /**
   * Example call to new method {@link RecordedEvent#getEventType()}.
   * @since 9
   * @see RecordedEvent#getEventType()
   */
  public EventType getEventType()
  {
    RecordedEvent testee = $$$();

    EventType result = testee.getEventType();
    return result;
  }

  /**
   * Example call to new method {@link RecordedEvent#getFields()}.
   * @since 9
   * @see RecordedEvent#getFields()
   */
  public List<ValueDescriptor> getFields()
  {
    RecordedEvent testee = $$$();

    List<ValueDescriptor> result = testee.getFields();
    return result;
  }

  /**
   * Example call to new method {@link RecordedEvent#getStackTrace()}.
   * @since 9
   * @see RecordedEvent#getStackTrace()
   */
  public RecordedStackTrace getStackTrace()
  {
    RecordedEvent testee = $$$();

    RecordedStackTrace result = testee.getStackTrace();
    return result;
  }

  /**
   * Example call to new method {@link RecordedEvent#getDuration()}.
   * @since 9
   * @see RecordedEvent#getDuration()
   */
  public Duration getDuration()
  {
    RecordedEvent testee = $$$();

    Duration result = testee.getDuration();
    return result;
  }

  /**
   * Example call to new method {@link RecordedEvent#getThread()}.
   * @since 9
   * @see RecordedEvent#getThread()
   */
  public RecordedThread getThread()
  {
    RecordedEvent testee = $$$();

    RecordedThread result = testee.getThread();
    return result;
  }

  /**
   * Example call to new method {@link RecordedEvent#getStartTime()}.
   * @since 9
   * @see RecordedEvent#getStartTime()
   */
  public Instant getStartTime()
  {
    RecordedEvent testee = $$$();

    Instant result = testee.getStartTime();
    return result;
  }

  private RecordedEvent $$$()
  {
    return null;
  }
}
