package whatisnewin.jdk.jfr.consumer;

import jdk.jfr.consumer.RecordedThread;
import jdk.jfr.consumer.RecordedThreadGroup;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link RecordedThread}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link RecordedThread} is a completely new class.
 * @since 9
 * @see RecordedThread
 */
public final class WhatIsNewInRecordedThread
{
  /**
   * Example call to new method {@link RecordedThread#getOSName()}.
   * @since 9
   * @see RecordedThread#getOSName()
   */
  public String getOSName()
  {
    RecordedThread testee = $$$();

    String result = testee.getOSName();
    return result;
  }

  /**
   * Example call to new method {@link RecordedThread#getOSThreadId()}.
   * @since 9
   * @see RecordedThread#getOSThreadId()
   */
  public long getOSThreadId()
  {
    RecordedThread testee = $$$();

    long result = testee.getOSThreadId();
    return result;
  }

  /**
   * Example call to new method {@link RecordedThread#getThreadGroup()}.
   * @since 9
   * @see RecordedThread#getThreadGroup()
   */
  public RecordedThreadGroup getThreadGroup()
  {
    RecordedThread testee = $$$();

    RecordedThreadGroup result = testee.getThreadGroup();
    return result;
  }

  /**
   * Example call to new method {@link RecordedThread#getJavaName()}.
   * @since 9
   * @see RecordedThread#getJavaName()
   */
  public String getJavaName()
  {
    RecordedThread testee = $$$();

    String result = testee.getJavaName();
    return result;
  }

  /**
   * Example call to new method {@link RecordedThread#getJavaThreadId()}.
   * @since 9
   * @see RecordedThread#getJavaThreadId()
   */
  public long getJavaThreadId()
  {
    RecordedThread testee = $$$();

    long result = testee.getJavaThreadId();
    return result;
  }

  /**
   * Example call to new method {@link RecordedThread#getId()}.
   * @since 9
   * @see RecordedThread#getId()
   */
  public long getId()
  {
    RecordedThread testee = $$$();

    long result = testee.getId();
    return result;
  }

  private RecordedThread $$$()
  {
    return null;
  }
}
