package whatisnewin.jdk.jfr.consumer;

import jdk.jfr.consumer.RecordedMethod;
import jdk.jfr.consumer.RecordedClass;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link RecordedMethod}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link RecordedMethod} is a completely new class
 * @since 9
 * @see RecordedMethod
 */
public final class WhatIsNewInRecordedMethod
{
  /**
   * Example call to new method {@link RecordedMethod#getName}
   * @since 9
   * @see RecordedMethod#getName
   */
  public String getName()
  {
    RecordedMethod testee = $$$();

    String result = testee.getName();
    return result;
  }

  /**
   * Example call to new method {@link RecordedMethod#getModifiers}
   * @since 9
   * @see RecordedMethod#getModifiers
   */
  public int getModifiers()
  {
    RecordedMethod testee = $$$();

    int result = testee.getModifiers();
    return result;
  }

  /**
   * Example call to new method {@link RecordedMethod#getDescriptor}
   * @since 9
   * @see RecordedMethod#getDescriptor
   */
  public String getDescriptor()
  {
    RecordedMethod testee = $$$();

    String result = testee.getDescriptor();
    return result;
  }

  /**
   * Example call to new method {@link RecordedMethod#isHidden}
   * @since 9
   * @see RecordedMethod#isHidden
   */
  public boolean isHidden()
  {
    RecordedMethod testee = $$$();

    boolean result = testee.isHidden();
    return result;
  }

  /**
   * Example call to new method {@link RecordedMethod#getType}
   * @since 9
   * @see RecordedMethod#getType
   */
  public RecordedClass getType()
  {
    RecordedMethod testee = $$$();

    RecordedClass result = testee.getType();
    return result;
  }

  private RecordedMethod $$$()
  {
    return null;
  }
}
