package whatisnewin.javax.annotation.processing;

import javax.annotation.processing.Generated;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link Generated}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link Generated} is a completely new class.
 * @since 9
 * @see Generated
 */
public final class WhatIsNewInGenerated
{
  /**
   * Example call to new method {@link Generated#value()}.
   * @since 9
   * @see Generated#value()
   */
  public String[] value()
  {
    Generated testee = $$$();

    String[] result = testee.value();
    return result;
  }

  /**
   * Example call to new method {@link Generated#date()}.
   * @since 9
   * @see Generated#date()
   */
  public String date()
  {
    Generated testee = $$$();

    String result = testee.date();
    return result;
  }

  /**
   * Example call to new method {@link Generated#comments()}.
   * @since 9
   * @see Generated#comments()
   */
  public String comments()
  {
    Generated testee = $$$();

    String result = testee.comments();
    return result;
  }

  private Generated $$$()
  {
    return null;
  }
}
