package whatisnewin.java.lang.ref;

import java.lang.ref.Cleaner.Cleanable;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link Cleanable}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link Cleanable} is a completely new class
 * @since 9
 * @see Cleanable
 */
public final class WhatIsNewInCleaner$Cleanable
{
  /**
   * Example call to new method {@link Cleanable#clean}
   * @since 9
   * @see Cleanable#clean
   */
  public void clean()
  {
    Cleanable testee = $$$();

    testee.clean();
  }

  private Cleanable $$$()
  {
    return null;
  }
}
