package whatisnewin.javax.tools;

import javax.tools.StandardJavaFileManager.PathFactory;
import java.nio.file.Path;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link PathFactory}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link PathFactory} is a completely new class
 * @since 9
 * @see PathFactory
 */
public final class WhatIsNewInStandardJavaFileManager$PathFactory
{
  /**
   * Example call to new method {@link PathFactory#getPath}
   * @since 9
   * @see PathFactory#getPath
   */
  public Path getPath(String first, String[] more)
  {
    PathFactory testee = $$$();

    Path result = testee.getPath(first, more);
    return result;
  }

  private PathFactory $$$()
  {
    return null;
  }
}
