package whatisnewin.javax.tools;

import javax.tools.JavaCompiler.CompilationTask;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link CompilationTask}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link CompilationTask} is an old class but has new fields, constructors or methods.
 * @since 1.6
 * @see CompilationTask
 */
public final class WhatIsNewInJavaCompiler$CompilationTask
{
  /**
   * Example call to new method {@link CompilationTask#addModules(Iterable)}.
   * @since 9
   * @see CompilationTask#addModules(Iterable)
   */
  public void addModules(Iterable<String> moduleNames)
  {
    CompilationTask testee = $$$();

    testee.addModules(moduleNames);
  }

  private CompilationTask $$$()
  {
    return null;
  }
}
