package whatisnewin.javax.tools;

import javax.tools.StandardJavaFileManager;
import javax.tools.JavaFileManager.Location;
import java.util.Collection;
import java.nio.file.Path;
import java.io.IOException;
import javax.tools.JavaFileObject;
import javax.tools.FileObject;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link StandardJavaFileManager}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link StandardJavaFileManager} is an old class but has new fields, constructors or methods
 * @since 1.6
 * @see StandardJavaFileManager
 */
public final class WhatIsNewInStandardJavaFileManager
{
  /**
   * Example call to new method {@link StandardJavaFileManager#setLocationFromPaths}
   * @since 9
   * @see StandardJavaFileManager#setLocationFromPaths
   */
  public void setLocationFromPaths(Location location, Collection<? extends Path> paths) throws IOException
  {
    StandardJavaFileManager testee = $$$();

    testee.setLocationFromPaths(location, paths);
  }

  /**
   * Example call to new method {@link StandardJavaFileManager#getJavaFileObjectsFromPaths}
   * @since 9
   * @see StandardJavaFileManager#getJavaFileObjectsFromPaths
   */
  public Iterable<? extends JavaFileObject> getJavaFileObjectsFromPaths(Iterable<? extends Path> paths)
  {
    StandardJavaFileManager testee = $$$();

    Iterable<? extends JavaFileObject> result = testee.getJavaFileObjectsFromPaths(paths);
    return result;
  }

  /**
   * Example call to new method {@link StandardJavaFileManager#getJavaFileObjects}
   * @since 9
   * @see StandardJavaFileManager#getJavaFileObjects
   */
  public Iterable<? extends JavaFileObject> getJavaFileObjects(Path[] paths)
  {
    StandardJavaFileManager testee = $$$();

    Iterable<? extends JavaFileObject> result = testee.getJavaFileObjects(paths);
    return result;
  }

  /**
   * Example call to new method {@link StandardJavaFileManager#setLocationForModule}
   * @since 9
   * @see StandardJavaFileManager#setLocationForModule
   */
  public void setLocationForModule(Location location, String moduleName, Collection<? extends Path> paths) throws IOException
  {
    StandardJavaFileManager testee = $$$();

    testee.setLocationForModule(location, moduleName, paths);
  }

  /**
   * Example call to new method {@link StandardJavaFileManager#getLocationAsPaths}
   * @since 9
   * @see StandardJavaFileManager#getLocationAsPaths
   */
  public Iterable<? extends Path> getLocationAsPaths(Location location)
  {
    StandardJavaFileManager testee = $$$();

    Iterable<? extends Path> result = testee.getLocationAsPaths(location);
    return result;
  }

  /**
   * Example call to new method {@link StandardJavaFileManager#asPath}
   * @since 9
   * @see StandardJavaFileManager#asPath
   */
  public Path asPath(FileObject file)
  {
    StandardJavaFileManager testee = $$$();

    Path result = testee.asPath(file);
    return result;
  }

  private StandardJavaFileManager $$$()
  {
    return null;
  }
}
