package whatisnewin.java.util;

import java.util.Enumeration;
import java.util.Iterator;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link Enumeration}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link Enumeration} is an old class but has new fields, constructors or methods.
 * @since 1.0
 * @see Enumeration
 */
public final class WhatIsNewInEnumeration<E>
{
  /**
   * Example call to new method {@link Enumeration#asIterator()}.
   * @since 9
   * @see Enumeration#asIterator()
   */
  public Iterator<E> asIterator()
  {
    Enumeration<E> testee = $$$();

    Iterator<E> result = testee.asIterator();
    return result;
  }

  private Enumeration<E> $$$()
  {
    return null;
  }
}
