package whatisnewin.javax.accessibility;

import javax.accessibility.AccessibilityProvider;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link AccessibilityProvider}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link AccessibilityProvider} is a completely new class
 * @since 9
 * @see AccessibilityProvider
 */
public final class WhatIsNewInAccessibilityProvider
{
  /**
   * Example call to new method {@link AccessibilityProvider#activate}
   * @since 9
   * @see AccessibilityProvider#activate
   */
  public void activate()
  {
    AccessibilityProvider testee = $$$();

    testee.activate();
  }

  /**
   * Example call to new method {@link AccessibilityProvider#getName}
   * @since 9
   * @see AccessibilityProvider#getName
   */
  public String getName()
  {
    AccessibilityProvider testee = $$$();

    String result = testee.getName();
    return result;
  }

  private AccessibilityProvider $$$()
  {
    return null;
  }
}
