package whatisnewin.com.sun.jarsigner;

import com.sun.jarsigner.ContentSignerParameters;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link ContentSignerParameters}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link ContentSignerParameters} is an old class but has new fields, constructors or methods
 * @since 1.5
 * @see ContentSignerParameters
 */
public final class WhatIsNewInContentSignerParameters
{
  /**
   * Example call to new method {@link ContentSignerParameters#getTSADigestAlg}
   * @since 9
   * @see ContentSignerParameters#getTSADigestAlg
   */
  public String getTSADigestAlg()
  {
    ContentSignerParameters testee = $$$();

    String result = testee.getTSADigestAlg();
    return result;
  }

  private ContentSignerParameters $$$()
  {
    return null;
  }
}
