package whatisnewin.java.awt;

import java.awt.Taskbar;
import java.awt.Taskbar.Feature;
import java.awt.Window;
import java.awt.PopupMenu;
import java.awt.Image;
import java.awt.Taskbar.State;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link Taskbar}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link Taskbar} is a completely new class.
 * @since 9
 * @see Taskbar
 */
public final class WhatIsNewInTaskbar
{
  /**
   * Example call to new method {@link Taskbar#isSupported(Feature)}.
   * @since 9
   * @see Taskbar#isSupported(Feature)
   */
  public boolean isSupported(Feature feature)
  {
    Taskbar testee = $$$();

    boolean result = testee.isSupported(feature);
    return result;
  }

  /**
   * Example call to new method {@link Taskbar#getTaskbar()}.
   * @since 9
   * @see Taskbar#getTaskbar()
   */
  public static Taskbar getTaskbar()
  {
    Taskbar result = Taskbar.getTaskbar();
    return result;
  }

  /**
   * Example call to new method {@link Taskbar#isTaskbarSupported()}.
   * @since 9
   * @see Taskbar#isTaskbarSupported()
   */
  public static boolean isTaskbarSupported()
  {
    boolean result = Taskbar.isTaskbarSupported();
    return result;
  }

  /**
   * Example call to new method {@link Taskbar#requestUserAttention(boolean, boolean)}.
   * @since 9
   * @see Taskbar#requestUserAttention(boolean, boolean)
   */
  public void requestUserAttention(boolean enabled, boolean critical)
  {
    Taskbar testee = $$$();

    testee.requestUserAttention(enabled, critical);
  }

  /**
   * Example call to new method {@link Taskbar#requestWindowUserAttention(Window)}.
   * @since 9
   * @see Taskbar#requestWindowUserAttention(Window)
   */
  public void requestWindowUserAttention(Window w)
  {
    Taskbar testee = $$$();

    testee.requestWindowUserAttention(w);
  }

  /**
   * Example call to new method {@link Taskbar#setMenu(PopupMenu)}.
   * @since 9
   * @see Taskbar#setMenu(PopupMenu)
   */
  public void setMenu(PopupMenu menu)
  {
    Taskbar testee = $$$();

    testee.setMenu(menu);
  }

  /**
   * Example call to new method {@link Taskbar#getMenu()}.
   * @since 9
   * @see Taskbar#getMenu()
   */
  public PopupMenu getMenu()
  {
    Taskbar testee = $$$();

    PopupMenu result = testee.getMenu();
    return result;
  }

  /**
   * Example call to new method {@link Taskbar#setIconImage(Image)}.
   * @since 9
   * @see Taskbar#setIconImage(Image)
   */
  public void setIconImage(Image image)
  {
    Taskbar testee = $$$();

    testee.setIconImage(image);
  }

  /**
   * Example call to new method {@link Taskbar#getIconImage()}.
   * @since 9
   * @see Taskbar#getIconImage()
   */
  public Image getIconImage()
  {
    Taskbar testee = $$$();

    Image result = testee.getIconImage();
    return result;
  }

  /**
   * Example call to new method {@link Taskbar#setIconBadge(String)}.
   * @since 9
   * @see Taskbar#setIconBadge(String)
   */
  public void setIconBadge(String badge)
  {
    Taskbar testee = $$$();

    testee.setIconBadge(badge);
  }

  /**
   * Example call to new method {@link Taskbar#setWindowIconBadge(Window, Image)}.
   * @since 9
   * @see Taskbar#setWindowIconBadge(Window, Image)
   */
  public void setWindowIconBadge(Window w, Image badge)
  {
    Taskbar testee = $$$();

    testee.setWindowIconBadge(w, badge);
  }

  /**
   * Example call to new method {@link Taskbar#setProgressValue(int)}.
   * @since 9
   * @see Taskbar#setProgressValue(int)
   */
  public void setProgressValue(int value)
  {
    Taskbar testee = $$$();

    testee.setProgressValue(value);
  }

  /**
   * Example call to new method {@link Taskbar#setWindowProgressValue(Window, int)}.
   * @since 9
   * @see Taskbar#setWindowProgressValue(Window, int)
   */
  public void setWindowProgressValue(Window w, int value)
  {
    Taskbar testee = $$$();

    testee.setWindowProgressValue(w, value);
  }

  /**
   * Example call to new method {@link Taskbar#setWindowProgressState(Window, State)}.
   * @since 9
   * @see Taskbar#setWindowProgressState(Window, State)
   */
  public void setWindowProgressState(Window w, State state)
  {
    Taskbar testee = $$$();

    testee.setWindowProgressState(w, state);
  }

  private Taskbar $$$()
  {
    return null;
  }
}
