package whatisnewin.java.awt;

import java.awt.Desktop.Action;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link Action}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link Action} is an old class but has new fields, constructors or methods.
 * @since 1.6
 * @see Action
 */
public final class WhatIsNewInDesktop$Action
{
  /**
   * Example usage of the new field {@link Action#APP_EVENT_FOREGROUND}.
   * @since 9
   * @see Action#APP_EVENT_FOREGROUND
   */
  public static final Action APP_EVENT_FOREGROUND = Action.APP_EVENT_FOREGROUND;

  /**
   * Example usage of the new field {@link Action#APP_EVENT_HIDDEN}.
   * @since 9
   * @see Action#APP_EVENT_HIDDEN
   */
  public static final Action APP_EVENT_HIDDEN = Action.APP_EVENT_HIDDEN;

  /**
   * Example usage of the new field {@link Action#APP_EVENT_REOPENED}.
   * @since 9
   * @see Action#APP_EVENT_REOPENED
   */
  public static final Action APP_EVENT_REOPENED = Action.APP_EVENT_REOPENED;

  /**
   * Example usage of the new field {@link Action#APP_EVENT_SCREEN_SLEEP}.
   * @since 9
   * @see Action#APP_EVENT_SCREEN_SLEEP
   */
  public static final Action APP_EVENT_SCREEN_SLEEP = Action.APP_EVENT_SCREEN_SLEEP;

  /**
   * Example usage of the new field {@link Action#APP_EVENT_SYSTEM_SLEEP}.
   * @since 9
   * @see Action#APP_EVENT_SYSTEM_SLEEP
   */
  public static final Action APP_EVENT_SYSTEM_SLEEP = Action.APP_EVENT_SYSTEM_SLEEP;

  /**
   * Example usage of the new field {@link Action#APP_EVENT_USER_SESSION}.
   * @since 9
   * @see Action#APP_EVENT_USER_SESSION
   */
  public static final Action APP_EVENT_USER_SESSION = Action.APP_EVENT_USER_SESSION;

  /**
   * Example usage of the new field {@link Action#APP_ABOUT}.
   * @since 9
   * @see Action#APP_ABOUT
   */
  public static final Action APP_ABOUT = Action.APP_ABOUT;

  /**
   * Example usage of the new field {@link Action#APP_PREFERENCES}.
   * @since 9
   * @see Action#APP_PREFERENCES
   */
  public static final Action APP_PREFERENCES = Action.APP_PREFERENCES;

  /**
   * Example usage of the new field {@link Action#APP_OPEN_FILE}.
   * @since 9
   * @see Action#APP_OPEN_FILE
   */
  public static final Action APP_OPEN_FILE = Action.APP_OPEN_FILE;

  /**
   * Example usage of the new field {@link Action#APP_PRINT_FILE}.
   * @since 9
   * @see Action#APP_PRINT_FILE
   */
  public static final Action APP_PRINT_FILE = Action.APP_PRINT_FILE;

  /**
   * Example usage of the new field {@link Action#APP_OPEN_URI}.
   * @since 9
   * @see Action#APP_OPEN_URI
   */
  public static final Action APP_OPEN_URI = Action.APP_OPEN_URI;

  /**
   * Example usage of the new field {@link Action#APP_QUIT_HANDLER}.
   * @since 9
   * @see Action#APP_QUIT_HANDLER
   */
  public static final Action APP_QUIT_HANDLER = Action.APP_QUIT_HANDLER;

  /**
   * Example usage of the new field {@link Action#APP_QUIT_STRATEGY}.
   * @since 9
   * @see Action#APP_QUIT_STRATEGY
   */
  public static final Action APP_QUIT_STRATEGY = Action.APP_QUIT_STRATEGY;

  /**
   * Example usage of the new field {@link Action#APP_SUDDEN_TERMINATION}.
   * @since 9
   * @see Action#APP_SUDDEN_TERMINATION
   */
  public static final Action APP_SUDDEN_TERMINATION = Action.APP_SUDDEN_TERMINATION;

  /**
   * Example usage of the new field {@link Action#APP_REQUEST_FOREGROUND}.
   * @since 9
   * @see Action#APP_REQUEST_FOREGROUND
   */
  public static final Action APP_REQUEST_FOREGROUND = Action.APP_REQUEST_FOREGROUND;

  /**
   * Example usage of the new field {@link Action#APP_HELP_VIEWER}.
   * @since 9
   * @see Action#APP_HELP_VIEWER
   */
  public static final Action APP_HELP_VIEWER = Action.APP_HELP_VIEWER;

  /**
   * Example usage of the new field {@link Action#APP_MENU_BAR}.
   * @since 9
   * @see Action#APP_MENU_BAR
   */
  public static final Action APP_MENU_BAR = Action.APP_MENU_BAR;

  /**
   * Example usage of the new field {@link Action#BROWSE_FILE_DIR}.
   * @since 9
   * @see Action#BROWSE_FILE_DIR
   */
  public static final Action BROWSE_FILE_DIR = Action.BROWSE_FILE_DIR;

  /**
   * Example usage of the new field {@link Action#MOVE_TO_TRASH}.
   * @since 9
   * @see Action#MOVE_TO_TRASH
   */
  public static final Action MOVE_TO_TRASH = Action.MOVE_TO_TRASH;

}
