package whatisnewin.javax.swing.text;

import javax.swing.text.Utilities;
import javax.swing.text.Segment;
import java.awt.Graphics2D;
import javax.swing.text.TabExpander;
import java.awt.FontMetrics;
import javax.swing.text.JTextComponent;
import javax.swing.text.BadLocationException;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link Utilities}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link Utilities} is an old class but has new fields, constructors or methods.
 * @since UNDEFINED
 * @see Utilities
 */
public final class WhatIsNewInUtilities
{
  /**
   * Example call to new method {@link Utilities#drawTabbedText(Segment, float, float, Graphics2D, TabExpander, int)}.
   * @since 9
   * @see Utilities#drawTabbedText(Segment, float, float, Graphics2D, TabExpander, int)
   */
  public static float drawTabbedText(Segment s, float x, float y, Graphics2D g, TabExpander e, int startOffset)
  {
    float result = Utilities.drawTabbedText(s, x, y, g, e, startOffset);
    return result;
  }

  /**
   * Example call to new method {@link Utilities#getTabbedTextWidth(Segment, FontMetrics, float, TabExpander, int)}.
   * @since 9
   * @see Utilities#getTabbedTextWidth(Segment, FontMetrics, float, TabExpander, int)
   */
  public static float getTabbedTextWidth(Segment s, FontMetrics metrics, float x, TabExpander e, int startOffset)
  {
    float result = Utilities.getTabbedTextWidth(s, metrics, x, e, startOffset);
    return result;
  }

  /**
   * Example call to new method {@link Utilities#getTabbedTextOffset(Segment, FontMetrics, float, float, TabExpander, int, boolean)}.
   * @since 9
   * @see Utilities#getTabbedTextOffset(Segment, FontMetrics, float, float, TabExpander, int, boolean)
   */
  public static int getTabbedTextOffset(Segment s, FontMetrics metrics, float x0, float x, TabExpander e, int startOffset, boolean round)
  {
    int result = Utilities.getTabbedTextOffset(s, metrics, x0, x, e, startOffset, round);
    return result;
  }

  /**
   * Example call to new method {@link Utilities#getBreakLocation(Segment, FontMetrics, float, float, TabExpander, int)}.
   * @since 9
   * @see Utilities#getBreakLocation(Segment, FontMetrics, float, float, TabExpander, int)
   */
  public static int getBreakLocation(Segment s, FontMetrics metrics, float x0, float x, TabExpander e, int startOffset)
  {
    int result = Utilities.getBreakLocation(s, metrics, x0, x, e, startOffset);
    return result;
  }

  /**
   * Example call to new method {@link Utilities#getPositionAbove(JTextComponent, int, float)}.
   * @since 9
   * @see Utilities#getPositionAbove(JTextComponent, int, float)
   */
  public static int getPositionAbove(JTextComponent c, int offs, float x) throws BadLocationException
  {
    int result = Utilities.getPositionAbove(c, offs, x);
    return result;
  }

  /**
   * Example call to new method {@link Utilities#getPositionBelow(JTextComponent, int, float)}.
   * @since 9
   * @see Utilities#getPositionBelow(JTextComponent, int, float)
   */
  public static int getPositionBelow(JTextComponent c, int offs, float x) throws BadLocationException
  {
    int result = Utilities.getPositionBelow(c, offs, x);
    return result;
  }

}
