package whatisnewin.jdk.jfr;

import jdk.jfr.Recording;
import java.util.Map;
import jdk.jfr.Configuration;
import java.time.Duration;
import java.nio.file.Path;
import java.io.IOException;
import jdk.jfr.EventSettings;
import jdk.jfr.Event;
import java.time.Instant;
import java.io.InputStream;
import jdk.jfr.RecordingState;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link Recording}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link Recording} is a completely new class
 * @since 9
 * @see Recording
 */
public final class WhatIsNewInRecording
{
  /**
   * Example call to new constructor {@link Recording#Recording}
   * @since 9
   * @see Recording#Recording
   */
  public WhatIsNewInRecording(Map<String, String> settings)
  {
    Recording testee = new Recording(settings);
  }

  /**
   * Example call to new constructor {@link Recording#Recording}
   * @since 9
   * @see Recording#Recording
   */
  public WhatIsNewInRecording()
  {
    Recording testee = new Recording();
  }

  /**
   * Example call to new constructor {@link Recording#Recording}
   * @since 9
   * @see Recording#Recording
   */
  public WhatIsNewInRecording(Configuration configuration)
  {
    Recording testee = new Recording(configuration);
  }

  /**
   * Example call to new method {@link Recording#setToDisk}
   * @since 9
   * @see Recording#setToDisk
   */
  public void setToDisk(boolean disk)
  {
    Recording testee = $$$();

    testee.setToDisk(disk);
  }

  /**
   * Example call to new method {@link Recording#setName}
   * @since 9
   * @see Recording#setName
   */
  public void setName(String name)
  {
    Recording testee = $$$();

    testee.setName(name);
  }

  /**
   * Example call to new method {@link Recording#setDuration}
   * @since 9
   * @see Recording#setDuration
   */
  public void setDuration(Duration duration)
  {
    Recording testee = $$$();

    testee.setDuration(duration);
  }

  /**
   * Example call to new method {@link Recording#getName}
   * @since 9
   * @see Recording#getName
   */
  public String getName()
  {
    Recording testee = $$$();

    String result = testee.getName();
    return result;
  }

  /**
   * Example call to new method {@link Recording#getSettings}
   * @since 9
   * @see Recording#getSettings
   */
  public Map<String, String> getSettings()
  {
    Recording testee = $$$();

    Map<String, String> result = testee.getSettings();
    return result;
  }

  /**
   * Example call to new method {@link Recording#getDestination}
   * @since 9
   * @see Recording#getDestination
   */
  public Path getDestination()
  {
    Recording testee = $$$();

    Path result = testee.getDestination();
    return result;
  }

  /**
   * Example call to new method {@link Recording#setDumpOnExit}
   * @since 9
   * @see Recording#setDumpOnExit
   */
  public void setDumpOnExit(boolean dumpOnExit)
  {
    Recording testee = $$$();

    testee.setDumpOnExit(dumpOnExit);
  }

  /**
   * Example call to new method {@link Recording#getId}
   * @since 9
   * @see Recording#getId
   */
  public long getId()
  {
    Recording testee = $$$();

    long result = testee.getId();
    return result;
  }

  /**
   * Example call to new method {@link Recording#setMaxSize}
   * @since 9
   * @see Recording#setMaxSize
   */
  public void setMaxSize(long maxSize)
  {
    Recording testee = $$$();

    testee.setMaxSize(maxSize);
  }

  /**
   * Example call to new method {@link Recording#setDestination}
   * @since 9
   * @see Recording#setDestination
   */
  public void setDestination(Path destination) throws IOException
  {
    Recording testee = $$$();

    testee.setDestination(destination);
  }

  /**
   * Example call to new method {@link Recording#scheduleStart}
   * @since 9
   * @see Recording#scheduleStart
   */
  public void scheduleStart(Duration delay)
  {
    Recording testee = $$$();

    testee.scheduleStart(delay);
  }

  /**
   * Example call to new method {@link Recording#getMaxSize}
   * @since 9
   * @see Recording#getMaxSize
   */
  public long getMaxSize()
  {
    Recording testee = $$$();

    long result = testee.getMaxSize();
    return result;
  }

  /**
   * Example call to new method {@link Recording#getMaxAge}
   * @since 9
   * @see Recording#getMaxAge
   */
  public Duration getMaxAge()
  {
    Recording testee = $$$();

    Duration result = testee.getMaxAge();
    return result;
  }

  /**
   * Example call to new method {@link Recording#getDuration}
   * @since 9
   * @see Recording#getDuration
   */
  public Duration getDuration()
  {
    Recording testee = $$$();

    Duration result = testee.getDuration();
    return result;
  }

  /**
   * Example call to new method {@link Recording#enable}
   * @since 9
   * @see Recording#enable
   */
  public EventSettings enable(String name)
  {
    Recording testee = $$$();

    EventSettings result = testee.enable(name);
    return result;
  }

  /**
   * Example call to new method {@link Recording#enable}
   * @since 9
   * @see Recording#enable
   */
  public EventSettings enable(Class<? extends Event> eventClass)
  {
    Recording testee = $$$();

    EventSettings result = testee.enable(eventClass);
    return result;
  }

  /**
   * Example call to new method {@link Recording#isToDisk}
   * @since 9
   * @see Recording#isToDisk
   */
  public boolean isToDisk()
  {
    Recording testee = $$$();

    boolean result = testee.isToDisk();
    return result;
  }

  /**
   * Example call to new method {@link Recording#getStartTime}
   * @since 9
   * @see Recording#getStartTime
   */
  public Instant getStartTime()
  {
    Recording testee = $$$();

    Instant result = testee.getStartTime();
    return result;
  }

  /**
   * Example call to new method {@link Recording#copy}
   * @since 9
   * @see Recording#copy
   */
  public Recording copy(boolean stop)
  {
    Recording testee = $$$();

    Recording result = testee.copy(stop);
    return result;
  }

  /**
   * Example call to new method {@link Recording#dump}
   * @since 9
   * @see Recording#dump
   */
  public void dump(Path destination) throws IOException
  {
    Recording testee = $$$();

    testee.dump(destination);
  }

  /**
   * Example call to new method {@link Recording#getStream}
   * @since 9
   * @see Recording#getStream
   */
  public InputStream getStream(Instant start, Instant end) throws IOException
  {
    Recording testee = $$$();

    InputStream result = testee.getStream(start, end);
    return result;
  }

  /**
   * Example call to new method {@link Recording#close}
   * @since 9
   * @see Recording#close
   */
  public void close()
  {
    Recording testee = $$$();

    testee.close();
  }

  /**
   * Example call to new method {@link Recording#setMaxAge}
   * @since 9
   * @see Recording#setMaxAge
   */
  public void setMaxAge(Duration maxAge)
  {
    Recording testee = $$$();

    testee.setMaxAge(maxAge);
  }

  /**
   * Example call to new method {@link Recording#start}
   * @since 9
   * @see Recording#start
   */
  public void start()
  {
    Recording testee = $$$();

    testee.start();
  }

  /**
   * Example call to new method {@link Recording#getDumpOnExit}
   * @since 9
   * @see Recording#getDumpOnExit
   */
  public boolean getDumpOnExit()
  {
    Recording testee = $$$();

    boolean result = testee.getDumpOnExit();
    return result;
  }

  /**
   * Example call to new method {@link Recording#setSettings}
   * @since 9
   * @see Recording#setSettings
   */
  public void setSettings(Map<String, String> settings)
  {
    Recording testee = $$$();

    testee.setSettings(settings);
  }

  /**
   * Example call to new method {@link Recording#getState}
   * @since 9
   * @see Recording#getState
   */
  public RecordingState getState()
  {
    Recording testee = $$$();

    RecordingState result = testee.getState();
    return result;
  }

  /**
   * Example call to new method {@link Recording#getSize}
   * @since 9
   * @see Recording#getSize
   */
  public long getSize()
  {
    Recording testee = $$$();

    long result = testee.getSize();
    return result;
  }

  /**
   * Example call to new method {@link Recording#getStopTime}
   * @since 9
   * @see Recording#getStopTime
   */
  public Instant getStopTime()
  {
    Recording testee = $$$();

    Instant result = testee.getStopTime();
    return result;
  }

  /**
   * Example call to new method {@link Recording#stop}
   * @since 9
   * @see Recording#stop
   */
  public boolean stop()
  {
    Recording testee = $$$();

    boolean result = testee.stop();
    return result;
  }

  /**
   * Example call to new method {@link Recording#disable}
   * @since 9
   * @see Recording#disable
   */
  public EventSettings disable(String name)
  {
    Recording testee = $$$();

    EventSettings result = testee.disable(name);
    return result;
  }

  /**
   * Example call to new method {@link Recording#disable}
   * @since 9
   * @see Recording#disable
   */
  public EventSettings disable(Class<? extends Event> eventClass)
  {
    Recording testee = $$$();

    EventSettings result = testee.disable(eventClass);
    return result;
  }

  private Recording $$$()
  {
    return null;
  }
}
