package whatisnewin.jdk.jfr;

import jdk.jfr.EventType;
import jdk.jfr.ValueDescriptor;
import java.util.List;
import jdk.jfr.Event;
import jdk.jfr.SettingDescriptor;
import jdk.jfr.AnnotationElement;
import java.lang.annotation.Annotation;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link EventType}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link EventType} is a completely new class
 * @since 9
 * @see EventType
 */
public final class WhatIsNewInEventType
{
  /**
   * Example call to new method {@link EventType#getId}
   * @since 9
   * @see EventType#getId
   */
  public long getId()
  {
    EventType testee = $$$();

    long result = testee.getId();
    return result;
  }

  /**
   * Example call to new method {@link EventType#getField}
   * @since 9
   * @see EventType#getField
   */
  public ValueDescriptor getField(String name)
  {
    EventType testee = $$$();

    ValueDescriptor result = testee.getField(name);
    return result;
  }

  /**
   * Example call to new method {@link EventType#getCategoryNames}
   * @since 9
   * @see EventType#getCategoryNames
   */
  public List<String> getCategoryNames()
  {
    EventType testee = $$$();

    List<String> result = testee.getCategoryNames();
    return result;
  }

  /**
   * Example call to new method {@link EventType#getDescription}
   * @since 9
   * @see EventType#getDescription
   */
  public String getDescription()
  {
    EventType testee = $$$();

    String result = testee.getDescription();
    return result;
  }

  /**
   * Example call to new method {@link EventType#getFields}
   * @since 9
   * @see EventType#getFields
   */
  public List<ValueDescriptor> getFields()
  {
    EventType testee = $$$();

    List<ValueDescriptor> result = testee.getFields();
    return result;
  }

  /**
   * Example call to new method {@link EventType#getName}
   * @since 9
   * @see EventType#getName
   */
  public String getName()
  {
    EventType testee = $$$();

    String result = testee.getName();
    return result;
  }

  /**
   * Example call to new method {@link EventType#getLabel}
   * @since 9
   * @see EventType#getLabel
   */
  public String getLabel()
  {
    EventType testee = $$$();

    String result = testee.getLabel();
    return result;
  }

  /**
   * Example call to new method {@link EventType#getEventType}
   * @since 9
   * @see EventType#getEventType
   */
  public static EventType getEventType(Class<? extends Event> eventClass)
  {
    EventType result = EventType.getEventType(eventClass);
    return result;
  }

  /**
   * Example call to new method {@link EventType#getSettingDescriptors}
   * @since 9
   * @see EventType#getSettingDescriptors
   */
  public List<SettingDescriptor> getSettingDescriptors()
  {
    EventType testee = $$$();

    List<SettingDescriptor> result = testee.getSettingDescriptors();
    return result;
  }

  /**
   * Example call to new method {@link EventType#getAnnotationElements}
   * @since 9
   * @see EventType#getAnnotationElements
   */
  public List<AnnotationElement> getAnnotationElements()
  {
    EventType testee = $$$();

    List<AnnotationElement> result = testee.getAnnotationElements();
    return result;
  }

  /**
   * Example call to new method {@link EventType#isEnabled}
   * @since 9
   * @see EventType#isEnabled
   */
  public boolean isEnabled()
  {
    EventType testee = $$$();

    boolean result = testee.isEnabled();
    return result;
  }

  /**
   * Example call to new method {@link EventType#getAnnotation}
   * @since 9
   * @see EventType#getAnnotation
   */
  public <A extends Annotation> A getAnnotation(Class<A> annotationClass)
  {
    EventType testee = $$$();

    A result = testee.getAnnotation(annotationClass);
    return result;
  }

  private EventType $$$()
  {
    return null;
  }
}
