package whatisnewin.jdk.jfr;

import jdk.jfr.SettingControl;
import java.util.Set;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link SettingControl}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link SettingControl} is a completely new class.
 * @since 9
 * @see SettingControl
 */
public final class WhatIsNewInSettingControl
{
  /**
   * Example call to new method {@link SettingControl#getValue()}.
   * @since 9
   * @see SettingControl#getValue()
   */
  public String getValue()
  {
    SettingControl testee = $$$();

    String result = testee.getValue();
    return result;
  }

  /**
   * Example call to new method {@link SettingControl#combine(Set)}.
   * @since 9
   * @see SettingControl#combine(Set)
   */
  public String combine(Set<String> settingValues)
  {
    SettingControl testee = $$$();

    String result = testee.combine(settingValues);
    return result;
  }

  /**
   * Example call to new method {@link SettingControl#setValue(String)}.
   * @since 9
   * @see SettingControl#setValue(String)
   */
  public void setValue(String settingValue)
  {
    SettingControl testee = $$$();

    testee.setValue(settingValue);
  }

  private SettingControl $$$()
  {
    return null;
  }
}
