package whatisnewin.jdk.jfr;

import jdk.jfr.RecordingState;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link RecordingState}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link RecordingState} is a completely new class.
 * @since 9
 * @see RecordingState
 */
public final class WhatIsNewInRecordingState
{
  /**
   * Example usage of the new field {@link RecordingState#NEW}.
   * @since 9
   * @see RecordingState#NEW
   */
  public static final RecordingState NEW = RecordingState.NEW;

  /**
   * Example usage of the new field {@link RecordingState#DELAYED}.
   * @since 9
   * @see RecordingState#DELAYED
   */
  public static final RecordingState DELAYED = RecordingState.DELAYED;

  /**
   * Example usage of the new field {@link RecordingState#RUNNING}.
   * @since 9
   * @see RecordingState#RUNNING
   */
  public static final RecordingState RUNNING = RecordingState.RUNNING;

  /**
   * Example usage of the new field {@link RecordingState#STOPPED}.
   * @since 9
   * @see RecordingState#STOPPED
   */
  public static final RecordingState STOPPED = RecordingState.STOPPED;

  /**
   * Example usage of the new field {@link RecordingState#CLOSED}.
   * @since 9
   * @see RecordingState#CLOSED
   */
  public static final RecordingState CLOSED = RecordingState.CLOSED;

  /**
   * Example call to new method {@link RecordingState#valueOf(String)}.
   * @since 9
   * @see RecordingState#valueOf(String)
   */
  public static RecordingState valueOf(String name)
  {
    RecordingState result = RecordingState.valueOf(name);
    return result;
  }

  /**
   * Example call to new method {@link RecordingState#values()}.
   * @since 9
   * @see RecordingState#values()
   */
  public static RecordingState[] values()
  {
    RecordingState[] result = RecordingState.values();
    return result;
  }

}
