package whatisnewin.jdk.jfr;

import jdk.jfr.Description;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link Description}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link Description} is a completely new class
 * @since 9
 * @see Description
 */
public final class WhatIsNewInDescription
{
  /**
   * Example call to new method {@link Description#value}
   * @since 9
   * @see Description#value
   */
  public String value()
  {
    Description testee = $$$();

    String result = testee.value();
    return result;
  }

  private Description $$$()
  {
    return null;
  }
}
