package whatisnewin.jdk.jfr;

import jdk.jfr.Timespan;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link Timespan}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link Timespan} is a completely new class
 * @since 9
 * @see Timespan
 */
public final class WhatIsNewInTimespan
{
  /**
   * Example usage of the new field {@link Timespan#TICKS}
   * @since 9
   * @see Timespan#TICKS
   */
  public static  final String TICKS = Timespan.TICKS;

  /**
   * Example usage of the new field {@link Timespan#SECONDS}
   * @since 9
   * @see Timespan#SECONDS
   */
  public static  final String SECONDS = Timespan.SECONDS;

  /**
   * Example usage of the new field {@link Timespan#MILLISECONDS}
   * @since 9
   * @see Timespan#MILLISECONDS
   */
  public static  final String MILLISECONDS = Timespan.MILLISECONDS;

  /**
   * Example usage of the new field {@link Timespan#NANOSECONDS}
   * @since 9
   * @see Timespan#NANOSECONDS
   */
  public static  final String NANOSECONDS = Timespan.NANOSECONDS;

  /**
   * Example usage of the new field {@link Timespan#MICROSECONDS}
   * @since 9
   * @see Timespan#MICROSECONDS
   */
  public static  final String MICROSECONDS = Timespan.MICROSECONDS;

  /**
   * Example call to new method {@link Timespan#value}
   * @since 9
   * @see Timespan#value
   */
  public String value()
  {
    Timespan testee = $$$();

    String result = testee.value();
    return result;
  }

  private Timespan $$$()
  {
    return null;
  }
}
