package whatisnewin.jdk.jshell;

import jdk.jshell.Snippet;
import jdk.jshell.Snippet.Kind;
import jdk.jshell.Snippet.SubKind;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link Snippet}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link Snippet} is a completely new class.
 * @since 9
 * @see Snippet
 */
public final class WhatIsNewInSnippet
{
  /**
   * Example call to new method {@link Snippet#kind()}.
   * @since 9
   * @see Snippet#kind()
   */
  public Kind kind()
  {
    Snippet testee = $$$();

    Kind result = testee.kind();
    return result;
  }

  /**
   * Example call to new method {@link Snippet#id()}.
   * @since 9
   * @see Snippet#id()
   */
  public String id()
  {
    Snippet testee = $$$();

    String result = testee.id();
    return result;
  }

  /**
   * Example call to new method {@link Snippet#source()}.
   * @since 9
   * @see Snippet#source()
   */
  public String source()
  {
    Snippet testee = $$$();

    String result = testee.source();
    return result;
  }

  /**
   * Example call to new method {@link Snippet#subKind()}.
   * @since 9
   * @see Snippet#subKind()
   */
  public SubKind subKind()
  {
    Snippet testee = $$$();

    SubKind result = testee.subKind();
    return result;
  }

  private Snippet $$$()
  {
    return null;
  }
}
