package whatisnewin.jdk.jshell;

import jdk.jshell.SourceCodeAnalysis.Suggestion;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link Suggestion}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link Suggestion} is a completely new class.
 * @since 9
 * @see Suggestion
 */
public final class WhatIsNewInSourceCodeAnalysis$Suggestion
{
  /**
   * Example call to new method {@link Suggestion#continuation()}.
   * @since 9
   * @see Suggestion#continuation()
   */
  public String continuation()
  {
    Suggestion testee = $$$();

    String result = testee.continuation();
    return result;
  }

  /**
   * Example call to new method {@link Suggestion#matchesType()}.
   * @since 9
   * @see Suggestion#matchesType()
   */
  public boolean matchesType()
  {
    Suggestion testee = $$$();

    boolean result = testee.matchesType();
    return result;
  }

  private Suggestion $$$()
  {
    return null;
  }
}
