package whatisnewin.jdk.jshell;

import jdk.jshell.SourceCodeAnalysis.QualifiedNames;
import java.util.List;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link QualifiedNames}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link QualifiedNames} is a completely new class.
 * @since 9
 * @see QualifiedNames
 */
public final class WhatIsNewInSourceCodeAnalysis$QualifiedNames
{
  /**
   * Example call to new method {@link QualifiedNames#getNames()}.
   * @since 9
   * @see QualifiedNames#getNames()
   */
  public List<String> getNames()
  {
    QualifiedNames testee = $$$();

    List<String> result = testee.getNames();
    return result;
  }

  /**
   * Example call to new method {@link QualifiedNames#getSimpleNameLength()}.
   * @since 9
   * @see QualifiedNames#getSimpleNameLength()
   */
  public int getSimpleNameLength()
  {
    QualifiedNames testee = $$$();

    int result = testee.getSimpleNameLength();
    return result;
  }

  /**
   * Example call to new method {@link QualifiedNames#isUpToDate()}.
   * @since 9
   * @see QualifiedNames#isUpToDate()
   */
  public boolean isUpToDate()
  {
    QualifiedNames testee = $$$();

    boolean result = testee.isUpToDate();
    return result;
  }

  /**
   * Example call to new method {@link QualifiedNames#isResolvable()}.
   * @since 9
   * @see QualifiedNames#isResolvable()
   */
  public boolean isResolvable()
  {
    QualifiedNames testee = $$$();

    boolean result = testee.isResolvable();
    return result;
  }

  private QualifiedNames $$$()
  {
    return null;
  }
}
