package whatisnewin.java.security;

import java.security.ProtectionDomain;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link ProtectionDomain}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link ProtectionDomain} is an old class but has new fields, constructors or methods.
 * @since 1.2
 * @see ProtectionDomain
 */
public final class WhatIsNewInProtectionDomain
{
  /**
   * Example call to new method {@link ProtectionDomain#staticPermissionsOnly()}.
   * @since 9
   * @see ProtectionDomain#staticPermissionsOnly()
   */
  public boolean staticPermissionsOnly()
  {
    ProtectionDomain testee = $$$();

    boolean result = testee.staticPermissionsOnly();
    return result;
  }

  private ProtectionDomain $$$()
  {
    return null;
  }
}
