package whatisnewin.javax.xml.xpath;

import javax.xml.xpath.XPathFactory;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link XPathFactory}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link XPathFactory} is an old class but has new fields, constructors or methods.
 * @since 1.5
 * @see XPathFactory
 */
public final class WhatIsNewInXPathFactory
{
  /**
   * Example call to new method {@link XPathFactory#newDefaultInstance()}.
   * @since 9
   * @see XPathFactory#newDefaultInstance()
   */
  public static XPathFactory newDefaultInstance()
  {
    XPathFactory result = XPathFactory.newDefaultInstance();
    return result;
  }

}
