package whatisnewin.com.sun.jdi;

import com.sun.jdi.VirtualMachine;
import java.util.List;
import com.sun.jdi.ModuleReference;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link VirtualMachine}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link VirtualMachine} is an old class but has new fields, constructors or methods.
 * @since 1.3
 * @see VirtualMachine
 */
public final class WhatIsNewInVirtualMachine
{
  /**
   * Example call to new method {@link VirtualMachine#canGetModuleInfo()}.
   * @since 9
   * @see VirtualMachine#canGetModuleInfo()
   */
  public boolean canGetModuleInfo()
  {
    VirtualMachine testee = $$$();

    boolean result = testee.canGetModuleInfo();
    return result;
  }

  /**
   * Example call to new method {@link VirtualMachine#allModules()}.
   * @since 9
   * @see VirtualMachine#allModules()
   */
  public List<ModuleReference> allModules()
  {
    VirtualMachine testee = $$$();

    List<ModuleReference> result = testee.allModules();
    return result;
  }

  private VirtualMachine $$$()
  {
    return null;
  }
}
