package whatisnewin.java.util.jar;

import java.util.jar.Attributes.Name;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link Name}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link Name} is an old class but has new fields, constructors or methods.
 * @since UNDEFINED
 * @see Name
 */
public final class WhatIsNewInAttributes$Name
{
  /**
   * Example usage of the new field {@link Name#MULTI_RELEASE}.
   * @since 9
   * @see Name#MULTI_RELEASE
   */
  public static final Name MULTI_RELEASE = Name.MULTI_RELEASE;

}
