package whatisnewin.com.sun.source.util;

import com.sun.source.util.DocTreeFactory;
import com.sun.source.doctree.AttributeTree;
import javax.lang.model.element.Name;
import com.sun.source.doctree.AttributeTree.ValueKind;
import java.util.List;
import com.sun.source.doctree.DocTree;
import com.sun.source.doctree.AuthorTree;
import com.sun.source.doctree.LiteralTree;
import com.sun.source.doctree.TextTree;
import com.sun.source.doctree.CommentTree;
import com.sun.source.doctree.DeprecatedTree;
import com.sun.source.doctree.DocCommentTree;
import com.sun.source.doctree.DocRootTree;
import com.sun.source.doctree.DocTypeTree;
import com.sun.source.doctree.EndElementTree;
import com.sun.source.doctree.EntityTree;
import com.sun.source.doctree.ErroneousTree;
import javax.tools.Diagnostic;
import javax.tools.JavaFileObject;
import com.sun.source.doctree.ThrowsTree;
import com.sun.source.doctree.ReferenceTree;
import com.sun.source.doctree.HiddenTree;
import com.sun.source.doctree.IdentifierTree;
import com.sun.source.doctree.IndexTree;
import com.sun.source.doctree.InheritDocTree;
import com.sun.source.doctree.LinkTree;
import com.sun.source.doctree.ParamTree;
import com.sun.source.doctree.ProvidesTree;
import com.sun.source.doctree.ReturnTree;
import com.sun.source.doctree.SeeTree;
import com.sun.source.doctree.SerialTree;
import com.sun.source.doctree.SerialDataTree;
import com.sun.source.doctree.SerialFieldTree;
import com.sun.source.doctree.SinceTree;
import com.sun.source.doctree.StartElementTree;
import com.sun.source.doctree.SummaryTree;
import com.sun.source.doctree.UnknownBlockTagTree;
import com.sun.source.doctree.UnknownInlineTagTree;
import com.sun.source.doctree.UsesTree;
import com.sun.source.doctree.ValueTree;
import com.sun.source.doctree.VersionTree;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link DocTreeFactory}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link DocTreeFactory} is a completely new class.
 * @since 9
 * @see DocTreeFactory
 */
public final class WhatIsNewInDocTreeFactory
{
  /**
   * Example call to new method {@link DocTreeFactory#newAttributeTree(Name, ValueKind, List)}.
   * @since 9
   * @see DocTreeFactory#newAttributeTree(Name, ValueKind, List)
   */
  public AttributeTree newAttributeTree(Name name, ValueKind vkind, List<? extends DocTree> value)
  {
    DocTreeFactory testee = $$$();

    AttributeTree result = testee.newAttributeTree(name, vkind, value);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newAuthorTree(List)}.
   * @since 9
   * @see DocTreeFactory#newAuthorTree(List)
   */
  public AuthorTree newAuthorTree(List<? extends DocTree> name)
  {
    DocTreeFactory testee = $$$();

    AuthorTree result = testee.newAuthorTree(name);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newCodeTree(TextTree)}.
   * @since 9
   * @see DocTreeFactory#newCodeTree(TextTree)
   */
  public LiteralTree newCodeTree(TextTree text)
  {
    DocTreeFactory testee = $$$();

    LiteralTree result = testee.newCodeTree(text);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newCommentTree(String)}.
   * @since 9
   * @see DocTreeFactory#newCommentTree(String)
   */
  public CommentTree newCommentTree(String text)
  {
    DocTreeFactory testee = $$$();

    CommentTree result = testee.newCommentTree(text);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newDeprecatedTree(List)}.
   * @since 9
   * @see DocTreeFactory#newDeprecatedTree(List)
   */
  public DeprecatedTree newDeprecatedTree(List<? extends DocTree> text)
  {
    DocTreeFactory testee = $$$();

    DeprecatedTree result = testee.newDeprecatedTree(text);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newDocCommentTree(List, List)}.
   * @since 9
   * @see DocTreeFactory#newDocCommentTree(List, List)
   */
  public DocCommentTree newDocCommentTree(List<? extends DocTree> fullBody, List<? extends DocTree> tags)
  {
    DocTreeFactory testee = $$$();

    DocCommentTree result = testee.newDocCommentTree(fullBody, tags);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newDocCommentTree(List, List, List, List)}.
   * @since 10
   * @see DocTreeFactory#newDocCommentTree(List, List, List, List)
   */
  public DocCommentTree newDocCommentTree(List<? extends DocTree> fullBody, List<? extends DocTree> tags, List<? extends DocTree> preamble, List<? extends DocTree> postamble)
  {
    DocTreeFactory testee = $$$();

    DocCommentTree result = testee.newDocCommentTree(fullBody, tags, preamble, postamble);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newDocRootTree()}.
   * @since 9
   * @see DocTreeFactory#newDocRootTree()
   */
  public DocRootTree newDocRootTree()
  {
    DocTreeFactory testee = $$$();

    DocRootTree result = testee.newDocRootTree();
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newDocTypeTree(String)}.
   * @since 10
   * @see DocTreeFactory#newDocTypeTree(String)
   */
  public DocTypeTree newDocTypeTree(String text)
  {
    DocTreeFactory testee = $$$();

    DocTypeTree result = testee.newDocTypeTree(text);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newEndElementTree(Name)}.
   * @since 9
   * @see DocTreeFactory#newEndElementTree(Name)
   */
  public EndElementTree newEndElementTree(Name name)
  {
    DocTreeFactory testee = $$$();

    EndElementTree result = testee.newEndElementTree(name);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newEntityTree(Name)}.
   * @since 9
   * @see DocTreeFactory#newEntityTree(Name)
   */
  public EntityTree newEntityTree(Name name)
  {
    DocTreeFactory testee = $$$();

    EntityTree result = testee.newEntityTree(name);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newErroneousTree(String, Diagnostic)}.
   * @since 9
   * @see DocTreeFactory#newErroneousTree(String, Diagnostic)
   */
  public ErroneousTree newErroneousTree(String text, Diagnostic<JavaFileObject> diag)
  {
    DocTreeFactory testee = $$$();

    ErroneousTree result = testee.newErroneousTree(text, diag);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newExceptionTree(ReferenceTree, List)}.
   * @since 9
   * @see DocTreeFactory#newExceptionTree(ReferenceTree, List)
   */
  public ThrowsTree newExceptionTree(ReferenceTree name, List<? extends DocTree> description)
  {
    DocTreeFactory testee = $$$();

    ThrowsTree result = testee.newExceptionTree(name, description);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newHiddenTree(List)}.
   * @since 9
   * @see DocTreeFactory#newHiddenTree(List)
   */
  public HiddenTree newHiddenTree(List<? extends DocTree> text)
  {
    DocTreeFactory testee = $$$();

    HiddenTree result = testee.newHiddenTree(text);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newIdentifierTree(Name)}.
   * @since 9
   * @see DocTreeFactory#newIdentifierTree(Name)
   */
  public IdentifierTree newIdentifierTree(Name name)
  {
    DocTreeFactory testee = $$$();

    IdentifierTree result = testee.newIdentifierTree(name);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newIndexTree(DocTree, List)}.
   * @since 9
   * @see DocTreeFactory#newIndexTree(DocTree, List)
   */
  public IndexTree newIndexTree(DocTree term, List<? extends DocTree> description)
  {
    DocTreeFactory testee = $$$();

    IndexTree result = testee.newIndexTree(term, description);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newInheritDocTree()}.
   * @since 9
   * @see DocTreeFactory#newInheritDocTree()
   */
  public InheritDocTree newInheritDocTree()
  {
    DocTreeFactory testee = $$$();

    InheritDocTree result = testee.newInheritDocTree();
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newLinkTree(ReferenceTree, List)}.
   * @since 9
   * @see DocTreeFactory#newLinkTree(ReferenceTree, List)
   */
  public LinkTree newLinkTree(ReferenceTree ref, List<? extends DocTree> label)
  {
    DocTreeFactory testee = $$$();

    LinkTree result = testee.newLinkTree(ref, label);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newLinkPlainTree(ReferenceTree, List)}.
   * @since 9
   * @see DocTreeFactory#newLinkPlainTree(ReferenceTree, List)
   */
  public LinkTree newLinkPlainTree(ReferenceTree ref, List<? extends DocTree> label)
  {
    DocTreeFactory testee = $$$();

    LinkTree result = testee.newLinkPlainTree(ref, label);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newLiteralTree(TextTree)}.
   * @since 9
   * @see DocTreeFactory#newLiteralTree(TextTree)
   */
  public LiteralTree newLiteralTree(TextTree text)
  {
    DocTreeFactory testee = $$$();

    LiteralTree result = testee.newLiteralTree(text);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newParamTree(boolean, IdentifierTree, List)}.
   * @since 9
   * @see DocTreeFactory#newParamTree(boolean, IdentifierTree, List)
   */
  public ParamTree newParamTree(boolean isTypeParameter, IdentifierTree name, List<? extends DocTree> description)
  {
    DocTreeFactory testee = $$$();

    ParamTree result = testee.newParamTree(isTypeParameter, name, description);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newProvidesTree(ReferenceTree, List)}.
   * @since 9
   * @see DocTreeFactory#newProvidesTree(ReferenceTree, List)
   */
  public ProvidesTree newProvidesTree(ReferenceTree name, List<? extends DocTree> description)
  {
    DocTreeFactory testee = $$$();

    ProvidesTree result = testee.newProvidesTree(name, description);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newReferenceTree(String)}.
   * @since 9
   * @see DocTreeFactory#newReferenceTree(String)
   */
  public ReferenceTree newReferenceTree(String signature)
  {
    DocTreeFactory testee = $$$();

    ReferenceTree result = testee.newReferenceTree(signature);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newReturnTree(List)}.
   * @since 9
   * @see DocTreeFactory#newReturnTree(List)
   */
  public ReturnTree newReturnTree(List<? extends DocTree> description)
  {
    DocTreeFactory testee = $$$();

    ReturnTree result = testee.newReturnTree(description);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newSeeTree(List)}.
   * @since 9
   * @see DocTreeFactory#newSeeTree(List)
   */
  public SeeTree newSeeTree(List<? extends DocTree> reference)
  {
    DocTreeFactory testee = $$$();

    SeeTree result = testee.newSeeTree(reference);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newSerialTree(List)}.
   * @since 9
   * @see DocTreeFactory#newSerialTree(List)
   */
  public SerialTree newSerialTree(List<? extends DocTree> description)
  {
    DocTreeFactory testee = $$$();

    SerialTree result = testee.newSerialTree(description);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newSerialDataTree(List)}.
   * @since 9
   * @see DocTreeFactory#newSerialDataTree(List)
   */
  public SerialDataTree newSerialDataTree(List<? extends DocTree> description)
  {
    DocTreeFactory testee = $$$();

    SerialDataTree result = testee.newSerialDataTree(description);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newSerialFieldTree(IdentifierTree, ReferenceTree, List)}.
   * @since 9
   * @see DocTreeFactory#newSerialFieldTree(IdentifierTree, ReferenceTree, List)
   */
  public SerialFieldTree newSerialFieldTree(IdentifierTree name, ReferenceTree type, List<? extends DocTree> description)
  {
    DocTreeFactory testee = $$$();

    SerialFieldTree result = testee.newSerialFieldTree(name, type, description);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newSinceTree(List)}.
   * @since 9
   * @see DocTreeFactory#newSinceTree(List)
   */
  public SinceTree newSinceTree(List<? extends DocTree> text)
  {
    DocTreeFactory testee = $$$();

    SinceTree result = testee.newSinceTree(text);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newStartElementTree(Name, List, boolean)}.
   * @since 9
   * @see DocTreeFactory#newStartElementTree(Name, List, boolean)
   */
  public StartElementTree newStartElementTree(Name name, List<? extends DocTree> attrs, boolean selfClosing)
  {
    DocTreeFactory testee = $$$();

    StartElementTree result = testee.newStartElementTree(name, attrs, selfClosing);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newSummaryTree(List)}.
   * @since 10
   * @see DocTreeFactory#newSummaryTree(List)
   */
  public SummaryTree newSummaryTree(List<? extends DocTree> summary)
  {
    DocTreeFactory testee = $$$();

    SummaryTree result = testee.newSummaryTree(summary);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newTextTree(String)}.
   * @since 9
   * @see DocTreeFactory#newTextTree(String)
   */
  public TextTree newTextTree(String text)
  {
    DocTreeFactory testee = $$$();

    TextTree result = testee.newTextTree(text);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newThrowsTree(ReferenceTree, List)}.
   * @since 9
   * @see DocTreeFactory#newThrowsTree(ReferenceTree, List)
   */
  public ThrowsTree newThrowsTree(ReferenceTree name, List<? extends DocTree> description)
  {
    DocTreeFactory testee = $$$();

    ThrowsTree result = testee.newThrowsTree(name, description);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newUnknownBlockTagTree(Name, List)}.
   * @since 9
   * @see DocTreeFactory#newUnknownBlockTagTree(Name, List)
   */
  public UnknownBlockTagTree newUnknownBlockTagTree(Name name, List<? extends DocTree> content)
  {
    DocTreeFactory testee = $$$();

    UnknownBlockTagTree result = testee.newUnknownBlockTagTree(name, content);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newUnknownInlineTagTree(Name, List)}.
   * @since 9
   * @see DocTreeFactory#newUnknownInlineTagTree(Name, List)
   */
  public UnknownInlineTagTree newUnknownInlineTagTree(Name name, List<? extends DocTree> content)
  {
    DocTreeFactory testee = $$$();

    UnknownInlineTagTree result = testee.newUnknownInlineTagTree(name, content);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newUsesTree(ReferenceTree, List)}.
   * @since 9
   * @see DocTreeFactory#newUsesTree(ReferenceTree, List)
   */
  public UsesTree newUsesTree(ReferenceTree name, List<? extends DocTree> description)
  {
    DocTreeFactory testee = $$$();

    UsesTree result = testee.newUsesTree(name, description);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newValueTree(ReferenceTree)}.
   * @since 9
   * @see DocTreeFactory#newValueTree(ReferenceTree)
   */
  public ValueTree newValueTree(ReferenceTree ref)
  {
    DocTreeFactory testee = $$$();

    ValueTree result = testee.newValueTree(ref);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newVersionTree(List)}.
   * @since 9
   * @see DocTreeFactory#newVersionTree(List)
   */
  public VersionTree newVersionTree(List<? extends DocTree> text)
  {
    DocTreeFactory testee = $$$();

    VersionTree result = testee.newVersionTree(text);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#at(int)}.
   * @since 9
   * @see DocTreeFactory#at(int)
   */
  public DocTreeFactory at(int pos)
  {
    DocTreeFactory testee = $$$();

    DocTreeFactory result = testee.at(pos);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#getFirstSentence(List)}.
   * @since 9
   * @see DocTreeFactory#getFirstSentence(List)
   */
  public List<DocTree> getFirstSentence(List<? extends DocTree> list)
  {
    DocTreeFactory testee = $$$();

    List<DocTree> result = testee.getFirstSentence(list);
    return result;
  }

  private DocTreeFactory $$$()
  {
    return null;
  }
}
