package whatisnewin.com.sun.source.util;

import com.sun.source.util.DocTreeFactory;
import com.sun.source.doctree.DocRootTree;
import com.sun.source.doctree.IdentifierTree;
import javax.lang.model.element.Name;
import com.sun.source.doctree.ThrowsTree;
import com.sun.source.doctree.ReferenceTree;
import java.util.List;
import com.sun.source.doctree.DocTree;
import com.sun.source.doctree.HiddenTree;
import com.sun.source.doctree.LiteralTree;
import com.sun.source.doctree.TextTree;
import com.sun.source.doctree.DocTypeTree;
import com.sun.source.doctree.DeprecatedTree;
import com.sun.source.doctree.DocCommentTree;
import com.sun.source.doctree.LinkTree;
import com.sun.source.doctree.ProvidesTree;
import com.sun.source.doctree.EntityTree;
import com.sun.source.doctree.SerialFieldTree;
import com.sun.source.doctree.SeeTree;
import com.sun.source.doctree.ErroneousTree;
import javax.tools.Diagnostic;
import javax.tools.JavaFileObject;
import com.sun.source.doctree.SerialTree;
import com.sun.source.doctree.SinceTree;
import com.sun.source.doctree.UnknownBlockTagTree;
import com.sun.source.doctree.ValueTree;
import com.sun.source.doctree.IndexTree;
import com.sun.source.doctree.ParamTree;
import com.sun.source.doctree.ReturnTree;
import com.sun.source.doctree.VersionTree;
import com.sun.source.doctree.UnknownInlineTagTree;
import com.sun.source.doctree.StartElementTree;
import com.sun.source.doctree.UsesTree;
import com.sun.source.doctree.CommentTree;
import com.sun.source.doctree.SerialDataTree;
import com.sun.source.doctree.SummaryTree;
import com.sun.source.doctree.EndElementTree;
import com.sun.source.doctree.AttributeTree;
import com.sun.source.doctree.AttributeTree.ValueKind;
import com.sun.source.doctree.InheritDocTree;
import com.sun.source.doctree.AuthorTree;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link DocTreeFactory}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link DocTreeFactory} is a completely new class
 * @since 9
 * @see DocTreeFactory
 */
public final class WhatIsNewInDocTreeFactory
{
  /**
   * Example call to new method {@link DocTreeFactory#newDocRootTree}
   * @since 9
   * @see DocTreeFactory#newDocRootTree
   */
  public DocRootTree newDocRootTree()
  {
    DocTreeFactory testee = $$$();

    DocRootTree result = testee.newDocRootTree();
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newIdentifierTree}
   * @since 9
   * @see DocTreeFactory#newIdentifierTree
   */
  public IdentifierTree newIdentifierTree(Name name)
  {
    DocTreeFactory testee = $$$();

    IdentifierTree result = testee.newIdentifierTree(name);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#at}
   * @since 9
   * @see DocTreeFactory#at
   */
  public DocTreeFactory at(int pos)
  {
    DocTreeFactory testee = $$$();

    DocTreeFactory result = testee.at(pos);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newThrowsTree}
   * @since 9
   * @see DocTreeFactory#newThrowsTree
   */
  public ThrowsTree newThrowsTree(ReferenceTree name, List<? extends DocTree> description)
  {
    DocTreeFactory testee = $$$();

    ThrowsTree result = testee.newThrowsTree(name, description);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newHiddenTree}
   * @since 9
   * @see DocTreeFactory#newHiddenTree
   */
  public HiddenTree newHiddenTree(List<? extends DocTree> text)
  {
    DocTreeFactory testee = $$$();

    HiddenTree result = testee.newHiddenTree(text);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newLiteralTree}
   * @since 9
   * @see DocTreeFactory#newLiteralTree
   */
  public LiteralTree newLiteralTree(TextTree text)
  {
    DocTreeFactory testee = $$$();

    LiteralTree result = testee.newLiteralTree(text);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newDocTypeTree}
   * @since 10
   * @see DocTreeFactory#newDocTypeTree
   */
  public DocTypeTree newDocTypeTree(String text)
  {
    DocTreeFactory testee = $$$();

    DocTypeTree result = testee.newDocTypeTree(text);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newDeprecatedTree}
   * @since 9
   * @see DocTreeFactory#newDeprecatedTree
   */
  public DeprecatedTree newDeprecatedTree(List<? extends DocTree> text)
  {
    DocTreeFactory testee = $$$();

    DeprecatedTree result = testee.newDeprecatedTree(text);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newDocCommentTree}
   * @since 9
   * @see DocTreeFactory#newDocCommentTree
   */
  public DocCommentTree newDocCommentTree(List<? extends DocTree> fullBody, List<? extends DocTree> tags)
  {
    DocTreeFactory testee = $$$();

    DocCommentTree result = testee.newDocCommentTree(fullBody, tags);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newDocCommentTree}
   * @since 10
   * @see DocTreeFactory#newDocCommentTree
   */
  public DocCommentTree newDocCommentTree(List<? extends DocTree> fullBody, List<? extends DocTree> tags, List<? extends DocTree> preamble, List<? extends DocTree> postamble)
  {
    DocTreeFactory testee = $$$();

    DocCommentTree result = testee.newDocCommentTree(fullBody, tags, preamble, postamble);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newTextTree}
   * @since 9
   * @see DocTreeFactory#newTextTree
   */
  public TextTree newTextTree(String text)
  {
    DocTreeFactory testee = $$$();

    TextTree result = testee.newTextTree(text);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newLinkPlainTree}
   * @since 9
   * @see DocTreeFactory#newLinkPlainTree
   */
  public LinkTree newLinkPlainTree(ReferenceTree ref, List<? extends DocTree> label)
  {
    DocTreeFactory testee = $$$();

    LinkTree result = testee.newLinkPlainTree(ref, label);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newProvidesTree}
   * @since 9
   * @see DocTreeFactory#newProvidesTree
   */
  public ProvidesTree newProvidesTree(ReferenceTree name, List<? extends DocTree> description)
  {
    DocTreeFactory testee = $$$();

    ProvidesTree result = testee.newProvidesTree(name, description);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newEntityTree}
   * @since 9
   * @see DocTreeFactory#newEntityTree
   */
  public EntityTree newEntityTree(Name name)
  {
    DocTreeFactory testee = $$$();

    EntityTree result = testee.newEntityTree(name);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newSerialFieldTree}
   * @since 9
   * @see DocTreeFactory#newSerialFieldTree
   */
  public SerialFieldTree newSerialFieldTree(IdentifierTree name, ReferenceTree type, List<? extends DocTree> description)
  {
    DocTreeFactory testee = $$$();

    SerialFieldTree result = testee.newSerialFieldTree(name, type, description);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newSeeTree}
   * @since 9
   * @see DocTreeFactory#newSeeTree
   */
  public SeeTree newSeeTree(List<? extends DocTree> reference)
  {
    DocTreeFactory testee = $$$();

    SeeTree result = testee.newSeeTree(reference);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newErroneousTree}
   * @since 9
   * @see DocTreeFactory#newErroneousTree
   */
  public ErroneousTree newErroneousTree(String text, Diagnostic<JavaFileObject> diag)
  {
    DocTreeFactory testee = $$$();

    ErroneousTree result = testee.newErroneousTree(text, diag);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newSerialTree}
   * @since 9
   * @see DocTreeFactory#newSerialTree
   */
  public SerialTree newSerialTree(List<? extends DocTree> description)
  {
    DocTreeFactory testee = $$$();

    SerialTree result = testee.newSerialTree(description);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newReferenceTree}
   * @since 9
   * @see DocTreeFactory#newReferenceTree
   */
  public ReferenceTree newReferenceTree(String signature)
  {
    DocTreeFactory testee = $$$();

    ReferenceTree result = testee.newReferenceTree(signature);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newSinceTree}
   * @since 9
   * @see DocTreeFactory#newSinceTree
   */
  public SinceTree newSinceTree(List<? extends DocTree> text)
  {
    DocTreeFactory testee = $$$();

    SinceTree result = testee.newSinceTree(text);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newUnknownBlockTagTree}
   * @since 9
   * @see DocTreeFactory#newUnknownBlockTagTree
   */
  public UnknownBlockTagTree newUnknownBlockTagTree(Name name, List<? extends DocTree> content)
  {
    DocTreeFactory testee = $$$();

    UnknownBlockTagTree result = testee.newUnknownBlockTagTree(name, content);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newLinkTree}
   * @since 9
   * @see DocTreeFactory#newLinkTree
   */
  public LinkTree newLinkTree(ReferenceTree ref, List<? extends DocTree> label)
  {
    DocTreeFactory testee = $$$();

    LinkTree result = testee.newLinkTree(ref, label);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newValueTree}
   * @since 9
   * @see DocTreeFactory#newValueTree
   */
  public ValueTree newValueTree(ReferenceTree ref)
  {
    DocTreeFactory testee = $$$();

    ValueTree result = testee.newValueTree(ref);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newIndexTree}
   * @since 9
   * @see DocTreeFactory#newIndexTree
   */
  public IndexTree newIndexTree(DocTree term, List<? extends DocTree> description)
  {
    DocTreeFactory testee = $$$();

    IndexTree result = testee.newIndexTree(term, description);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newExceptionTree}
   * @since 9
   * @see DocTreeFactory#newExceptionTree
   */
  public ThrowsTree newExceptionTree(ReferenceTree name, List<? extends DocTree> description)
  {
    DocTreeFactory testee = $$$();

    ThrowsTree result = testee.newExceptionTree(name, description);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newParamTree}
   * @since 9
   * @see DocTreeFactory#newParamTree
   */
  public ParamTree newParamTree(boolean isTypeParameter, IdentifierTree name, List<? extends DocTree> description)
  {
    DocTreeFactory testee = $$$();

    ParamTree result = testee.newParamTree(isTypeParameter, name, description);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newReturnTree}
   * @since 9
   * @see DocTreeFactory#newReturnTree
   */
  public ReturnTree newReturnTree(List<? extends DocTree> description)
  {
    DocTreeFactory testee = $$$();

    ReturnTree result = testee.newReturnTree(description);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newVersionTree}
   * @since 9
   * @see DocTreeFactory#newVersionTree
   */
  public VersionTree newVersionTree(List<? extends DocTree> text)
  {
    DocTreeFactory testee = $$$();

    VersionTree result = testee.newVersionTree(text);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newUnknownInlineTagTree}
   * @since 9
   * @see DocTreeFactory#newUnknownInlineTagTree
   */
  public UnknownInlineTagTree newUnknownInlineTagTree(Name name, List<? extends DocTree> content)
  {
    DocTreeFactory testee = $$$();

    UnknownInlineTagTree result = testee.newUnknownInlineTagTree(name, content);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#getFirstSentence}
   * @since 9
   * @see DocTreeFactory#getFirstSentence
   */
  public List<DocTree> getFirstSentence(List<? extends DocTree> list)
  {
    DocTreeFactory testee = $$$();

    List<DocTree> result = testee.getFirstSentence(list);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newStartElementTree}
   * @since 9
   * @see DocTreeFactory#newStartElementTree
   */
  public StartElementTree newStartElementTree(Name name, List<? extends DocTree> attrs, boolean selfClosing)
  {
    DocTreeFactory testee = $$$();

    StartElementTree result = testee.newStartElementTree(name, attrs, selfClosing);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newUsesTree}
   * @since 9
   * @see DocTreeFactory#newUsesTree
   */
  public UsesTree newUsesTree(ReferenceTree name, List<? extends DocTree> description)
  {
    DocTreeFactory testee = $$$();

    UsesTree result = testee.newUsesTree(name, description);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newCommentTree}
   * @since 9
   * @see DocTreeFactory#newCommentTree
   */
  public CommentTree newCommentTree(String text)
  {
    DocTreeFactory testee = $$$();

    CommentTree result = testee.newCommentTree(text);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newCodeTree}
   * @since 9
   * @see DocTreeFactory#newCodeTree
   */
  public LiteralTree newCodeTree(TextTree text)
  {
    DocTreeFactory testee = $$$();

    LiteralTree result = testee.newCodeTree(text);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newSerialDataTree}
   * @since 9
   * @see DocTreeFactory#newSerialDataTree
   */
  public SerialDataTree newSerialDataTree(List<? extends DocTree> description)
  {
    DocTreeFactory testee = $$$();

    SerialDataTree result = testee.newSerialDataTree(description);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newSummaryTree}
   * @since 10
   * @see DocTreeFactory#newSummaryTree
   */
  public SummaryTree newSummaryTree(List<? extends DocTree> summary)
  {
    DocTreeFactory testee = $$$();

    SummaryTree result = testee.newSummaryTree(summary);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newEndElementTree}
   * @since 9
   * @see DocTreeFactory#newEndElementTree
   */
  public EndElementTree newEndElementTree(Name name)
  {
    DocTreeFactory testee = $$$();

    EndElementTree result = testee.newEndElementTree(name);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newAttributeTree}
   * @since 9
   * @see DocTreeFactory#newAttributeTree
   */
  public AttributeTree newAttributeTree(Name name, ValueKind vkind, List<? extends DocTree> value)
  {
    DocTreeFactory testee = $$$();

    AttributeTree result = testee.newAttributeTree(name, vkind, value);
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newInheritDocTree}
   * @since 9
   * @see DocTreeFactory#newInheritDocTree
   */
  public InheritDocTree newInheritDocTree()
  {
    DocTreeFactory testee = $$$();

    InheritDocTree result = testee.newInheritDocTree();
    return result;
  }

  /**
   * Example call to new method {@link DocTreeFactory#newAuthorTree}
   * @since 9
   * @see DocTreeFactory#newAuthorTree
   */
  public AuthorTree newAuthorTree(List<? extends DocTree> name)
  {
    DocTreeFactory testee = $$$();

    AuthorTree result = testee.newAuthorTree(name);
    return result;
  }

  private DocTreeFactory $$$()
  {
    return null;
  }
}
