package whatisnewin.java.lang.instrument;

import java.lang.instrument.UnmodifiableModuleException;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link UnmodifiableModuleException}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link UnmodifiableModuleException} is a completely new class
 * @since 9
 * @see UnmodifiableModuleException
 */
public final class WhatIsNewInUnmodifiableModuleException
{
  /**
   * Example call to new constructor {@link UnmodifiableModuleException#UnmodifiableModuleException}
   * @since 9
   * @see UnmodifiableModuleException#UnmodifiableModuleException
   */
  public WhatIsNewInUnmodifiableModuleException()
  {
    UnmodifiableModuleException testee = new UnmodifiableModuleException();
  }

  /**
   * Example call to new constructor {@link UnmodifiableModuleException#UnmodifiableModuleException}
   * @since 9
   * @see UnmodifiableModuleException#UnmodifiableModuleException
   */
  public WhatIsNewInUnmodifiableModuleException(String msg)
  {
    UnmodifiableModuleException testee = new UnmodifiableModuleException(msg);
  }

}
