package whatisnewin.java.lang.instrument;

import java.lang.instrument.ClassFileTransformer;
import java.security.ProtectionDomain;
import java.lang.instrument.IllegalClassFormatException;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link ClassFileTransformer}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link ClassFileTransformer} is an old class but has new fields, constructors or methods.
 * @since 1.5
 * @see ClassFileTransformer
 */
public final class WhatIsNewInClassFileTransformer
{
  /**
   * Example call to new method {@link ClassFileTransformer#transform(Module, ClassLoader, String, Class, ProtectionDomain, byte[])}.
   * @since 9
   * @see ClassFileTransformer#transform(Module, ClassLoader, String, Class, ProtectionDomain, byte[])
   */
  public byte[] transform(Module module, ClassLoader loader, String className, Class<?> classBeingRedefined, ProtectionDomain protectionDomain, byte[] classfileBuffer) throws IllegalClassFormatException
  {
    ClassFileTransformer testee = $$$();

    byte[] result = testee.transform(module, loader, className, classBeingRedefined, protectionDomain, classfileBuffer);
    return result;
  }

  private ClassFileTransformer $$$()
  {
    return null;
  }
}
