package whatisnewin.java.lang.reflect;

import java.lang.reflect.AnnotatedWildcardType;
import java.lang.reflect.AnnotatedType;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link AnnotatedWildcardType}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link AnnotatedWildcardType} is an old class but has new fields, constructors or methods.
 * @since 1.8
 * @see AnnotatedWildcardType
 */
public final class WhatIsNewInAnnotatedWildcardType
{
  /**
   * Example call to new method {@link AnnotatedWildcardType#getAnnotatedOwnerType()}.
   * @since 9
   * @see AnnotatedWildcardType#getAnnotatedOwnerType()
   */
  public AnnotatedType getAnnotatedOwnerType()
  {
    AnnotatedWildcardType testee = $$$();

    AnnotatedType result = testee.getAnnotatedOwnerType();
    return result;
  }

  private AnnotatedWildcardType $$$()
  {
    return null;
  }
}
