package whatisnewin.java.lang.reflect;

import java.lang.reflect.AnnotatedTypeVariable;
import java.lang.reflect.AnnotatedType;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link AnnotatedTypeVariable}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link AnnotatedTypeVariable} is an old class but has new fields, constructors or methods.
 * @since 1.8
 * @see AnnotatedTypeVariable
 */
public final class WhatIsNewInAnnotatedTypeVariable
{
  /**
   * Example call to new method {@link AnnotatedTypeVariable#getAnnotatedOwnerType()}.
   * @since 9
   * @see AnnotatedTypeVariable#getAnnotatedOwnerType()
   */
  public AnnotatedType getAnnotatedOwnerType()
  {
    AnnotatedTypeVariable testee = $$$();

    AnnotatedType result = testee.getAnnotatedOwnerType();
    return result;
  }

  private AnnotatedTypeVariable $$$()
  {
    return null;
  }
}
