package whatisnewin.java.lang.reflect;

import java.lang.reflect.AnnotatedParameterizedType;
import java.lang.reflect.AnnotatedType;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link AnnotatedParameterizedType}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link AnnotatedParameterizedType} is an old class but has new fields, constructors or methods.
 * @since 1.8
 * @see AnnotatedParameterizedType
 */
public final class WhatIsNewInAnnotatedParameterizedType
{
  /**
   * Example call to new method {@link AnnotatedParameterizedType#getAnnotatedOwnerType()}.
   * @since 9
   * @see AnnotatedParameterizedType#getAnnotatedOwnerType()
   */
  public AnnotatedType getAnnotatedOwnerType()
  {
    AnnotatedParameterizedType testee = $$$();

    AnnotatedType result = testee.getAnnotatedOwnerType();
    return result;
  }

  private AnnotatedParameterizedType $$$()
  {
    return null;
  }
}
