package whatisnewin.java.lang.reflect;

import java.lang.reflect.AnnotatedType;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link AnnotatedType}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link AnnotatedType} is an old class but has new fields, constructors or methods.
 * @since 1.8
 * @see AnnotatedType
 */
public final class WhatIsNewInAnnotatedType
{
  /**
   * Example call to new method {@link AnnotatedType#getAnnotatedOwnerType()}.
   * @since 9
   * @see AnnotatedType#getAnnotatedOwnerType()
   */
  public AnnotatedType getAnnotatedOwnerType()
  {
    AnnotatedType testee = $$$();

    AnnotatedType result = testee.getAnnotatedOwnerType();
    return result;
  }

  private AnnotatedType $$$()
  {
    return null;
  }
}
