package whatisnewin.com.sun.source.tree;

import com.sun.source.tree.OpensTree;
import java.util.List;
import com.sun.source.tree.ExpressionTree;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link OpensTree}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link OpensTree} is a completely new class.
 * @since 9
 * @see OpensTree
 */
public final class WhatIsNewInOpensTree
{
  /**
   * Example call to new method {@link OpensTree#getModuleNames()}.
   * @since 9
   * @see OpensTree#getModuleNames()
   */
  public List<? extends ExpressionTree> getModuleNames()
  {
    OpensTree testee = $$$();

    List<? extends ExpressionTree> result = testee.getModuleNames();
    return result;
  }

  /**
   * Example call to new method {@link OpensTree#getPackageName()}.
   * @since 9
   * @see OpensTree#getPackageName()
   */
  public ExpressionTree getPackageName()
  {
    OpensTree testee = $$$();

    ExpressionTree result = testee.getPackageName();
    return result;
  }

  private OpensTree $$$()
  {
    return null;
  }
}
