package whatisnewin.com.sun.source.tree;

import com.sun.source.tree.RequiresTree;
import com.sun.source.tree.ExpressionTree;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link RequiresTree}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link RequiresTree} is a completely new class
 * @since 9
 * @see RequiresTree
 */
public final class WhatIsNewInRequiresTree
{
  /**
   * Example call to new method {@link RequiresTree#isTransitive}
   * @since 9
   * @see RequiresTree#isTransitive
   */
  public boolean isTransitive()
  {
    RequiresTree testee = $$$();

    boolean result = testee.isTransitive();
    return result;
  }

  /**
   * Example call to new method {@link RequiresTree#getModuleName}
   * @since 9
   * @see RequiresTree#getModuleName
   */
  public ExpressionTree getModuleName()
  {
    RequiresTree testee = $$$();

    ExpressionTree result = testee.getModuleName();
    return result;
  }

  /**
   * Example call to new method {@link RequiresTree#isStatic}
   * @since 9
   * @see RequiresTree#isStatic
   */
  public boolean isStatic()
  {
    RequiresTree testee = $$$();

    boolean result = testee.isStatic();
    return result;
  }

  private RequiresTree $$$()
  {
    return null;
  }
}
