package whatisnewin.com.sun.source.tree;

import com.sun.source.tree.CompilationUnitTree;
import com.sun.source.tree.PackageTree;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link CompilationUnitTree}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link CompilationUnitTree} is an old class but has new fields, constructors or methods
 * @since 1.6
 * @see CompilationUnitTree
 */
public final class WhatIsNewInCompilationUnitTree
{
  /**
   * Example call to new method {@link CompilationUnitTree#getPackage}
   * @since 9
   * @see CompilationUnitTree#getPackage
   */
  public PackageTree getPackage()
  {
    CompilationUnitTree testee = $$$();

    PackageTree result = testee.getPackage();
    return result;
  }

  private CompilationUnitTree $$$()
  {
    return null;
  }
}
