package whatisnewin.com.sun.source.tree;

import com.sun.source.tree.UsesTree;
import com.sun.source.tree.ExpressionTree;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link UsesTree}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link UsesTree} is a completely new class.
 * @since 9
 * @see UsesTree
 */
public final class WhatIsNewInUsesTree
{
  /**
   * Example call to new method {@link UsesTree#getServiceName()}.
   * @since 9
   * @see UsesTree#getServiceName()
   */
  public ExpressionTree getServiceName()
  {
    UsesTree testee = $$$();

    ExpressionTree result = testee.getServiceName();
    return result;
  }

  private UsesTree $$$()
  {
    return null;
  }
}
