package whatisnewin.com.sun.source.tree;

import com.sun.source.tree.PackageTree;
import java.util.List;
import com.sun.source.tree.AnnotationTree;
import com.sun.source.tree.ExpressionTree;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link PackageTree}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link PackageTree} is a completely new class.
 * @since 9
 * @see PackageTree
 */
public final class WhatIsNewInPackageTree
{
  /**
   * Example call to new method {@link PackageTree#getAnnotations()}.
   * @since 9
   * @see PackageTree#getAnnotations()
   */
  public List<? extends AnnotationTree> getAnnotations()
  {
    PackageTree testee = $$$();

    List<? extends AnnotationTree> result = testee.getAnnotations();
    return result;
  }

  /**
   * Example call to new method {@link PackageTree#getPackageName()}.
   * @since 9
   * @see PackageTree#getPackageName()
   */
  public ExpressionTree getPackageName()
  {
    PackageTree testee = $$$();

    ExpressionTree result = testee.getPackageName();
    return result;
  }

  private PackageTree $$$()
  {
    return null;
  }
}
