package whatisnewin.com.sun.source.tree;

import com.sun.source.tree.ProvidesTree;
import com.sun.source.tree.ExpressionTree;
import java.util.List;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link ProvidesTree}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link ProvidesTree} is a completely new class.
 * @since 9
 * @see ProvidesTree
 */
public final class WhatIsNewInProvidesTree
{
  /**
   * Example call to new method {@link ProvidesTree#getServiceName()}.
   * @since 9
   * @see ProvidesTree#getServiceName()
   */
  public ExpressionTree getServiceName()
  {
    ProvidesTree testee = $$$();

    ExpressionTree result = testee.getServiceName();
    return result;
  }

  /**
   * Example call to new method {@link ProvidesTree#getImplementationNames()}.
   * @since 9
   * @see ProvidesTree#getImplementationNames()
   */
  public List<? extends ExpressionTree> getImplementationNames()
  {
    ProvidesTree testee = $$$();

    List<? extends ExpressionTree> result = testee.getImplementationNames();
    return result;
  }

  private ProvidesTree $$$()
  {
    return null;
  }
}
