package whatisnewin.java.time.chrono;

import java.time.chrono.IsoChronology;
import java.time.ZoneOffset;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link IsoChronology}
 * that were newly introduced in Java versions 9, 10, 11.<br>
 *
 * {@link IsoChronology} is an old class but has new fields, constructors or methods.
 * @since 1.8
 * @see IsoChronology
 */
public final class WhatIsNewInIsoChronology
{
  /**
   * Example call to new method {@link IsoChronology#epochSecond(int, int, int, int, int, int, ZoneOffset)}.
   * @since 9
   * @see IsoChronology#epochSecond(int, int, int, int, int, int, ZoneOffset)
   */
  public long epochSecond(int prolepticYear, int month, int dayOfMonth, int hour, int minute, int second, ZoneOffset zoneOffset)
  {
    IsoChronology testee = $$$();

    long result = testee.epochSecond(prolepticYear, month, dayOfMonth, hour, minute, second, zoneOffset);
    return result;
  }

  private IsoChronology $$$()
  {
    return null;
  }
}
